#!/usr/bin/bash

# module: install

# For this file --> chmod u=rwx,g=rx,o=rx
# Activate the mamba environment:  mamba activate saskan
# Then tun with sudo permissions:  sudo bash ./saskan_install

python /home/dave/Dropbox/GitHub/saskan-app/Saskantinon/install_app.py

