CREATE TABLE IF NOT EXISTS RIVER (
river_uid_pk TEXT DEFAULT '',
gloss_common_uid_fk TEXT DEFAULT '',
river_course_points_json JSON DEFAULT '',
river_bank_points_json JSON DEFAULT '',
river_type TEXT DEFAULT 'perrenial',
avg_width_m NUMERIC DEFAULT 0.0,
avg_depth_m NUMERIC DEFAULT 0.0,
total_length_km NUMERIC DEFAULT 0.0,
drainage_basin_km NUMERIC DEFAULT 0.0,
avg_velocity_m_per_h NUMERIC DEFAULT 0.0,
gradient_m_per_km NUMERIC DEFAULT 0.0,
river_hazards_json JSON DEFAULT '',
river_features_json JSON DEFAULT '',
river_nav_type TEXT DEFAULT 'none',
flora_and_fauna TEXT DEFAULT '',
water_quality TEXT DEFAULT '',
historical_events TEXT DEFAULT '',
current_conditions TEXT DEFAULT '',
CHECK (river_type IN ('perrenial', 'periodic', 'episodic', 'exotic', 'tributary', 'distributary', 'underground', 'aqueduct', 'canal', 'rapids', 'winding', 'stream', 'glacier')),
CHECK (river_nav_type IN ('small craft', 'large craft', 'none')),
FOREIGN KEY (gloss_common_uid_fk) REFERENCES GLOSS_COMMON(gloss_common_uid_pk) ON DELETE CASCADE,
PRIMARY KEY (river_uid_pk));
