CREATE TABLE IF NOT EXISTS SOLAR_CALENDAR (
solar_calendar_uid_pk TEXT DEFAULT '',
solar_year_uid_fk TEXT DEFAULT '',
year_name_gloss_common_uid_fk TEXT DEFAULT '',
season_start_uid_fk TEXT DEFAULT '',
solar_calendar_id TEXT DEFAULT '',
solar_calendar_desc TEXT DEFAULT '',
version_id TEXT DEFAULT '',
epoch_start_offset INTEGER DEFAULT 0,
months_in_year INTEGER DEFAULT 0,
watches_in_day INTEGER DEFAULT 0,
hours_in_watch INTEGER DEFAULT 0,
minutes_in_hour INTEGER DEFAULT 0,
seconds_in_minute INTEGER DEFAULT 0,
leap_year INTEGER DEFAULT 0,
leap_month INTEGER DEFAULT 0,
leap_days INTEGER DEFAULT 0,
leap_rule TEXT DEFAULT 'add_to_end_of_nth_month',
delete_dt TEXT DEFAULT '',
CHECK (leap_rule IN ('add_to_start_of_nth_month', 'add_to_end_of_nth_month', 'add_special_month')),
FOREIGN KEY (solar_year_uid_fk) REFERENCES SOLAR_YEAR(solar_year_uid_pk) ON DELETE CASCADE,
FOREIGN KEY (year_name_gloss_common_uid_fk) REFERENCES GLOSS_COMMON(gloss_common_uid_pk) ON DELETE CASCADE,
FOREIGN KEY (season_start_uid_fk) REFERENCES SEASON(season_uid_pk) ON DELETE CASCADE,
PRIMARY KEY (solar_calendar_uid_pk));
