CREATE TABLE IF NOT EXISTS MOON (
moon_uid_pk TEXT DEFAULT '',
world_uid_fk TEXT DEFAULT '',
moon_name TEXT DEFAULT '',
mass_kg NUMERIC DEFAULT 0.0,
radius_km NUMERIC DEFAULT 0.0,
obliquity_dg NUMERIC DEFAULT 0.0,
is_tidally_locked BOOLEAN DEFAULT 1,
rotation_direction TEXT DEFAULT 'prograde',
orbit_direction TEXT DEFAULT 'prograde',
orbit_world_days NUMERIC DEFAULT 0.0,
rotation_world_days NUMERIC DEFAULT 0.0,
initial_velocity NUMERIC DEFAULT 0.0,
angular_velocity NUMERIC DEFAULT 0.0,
delete_dt TEXT DEFAULT '',
CHECK (rotation_direction IN ('prograde', 'retrograde')),
CHECK (orbit_direction IN ('prograde', 'retrograde')),
FOREIGN KEY (world_uid_fk) REFERENCES WORLD(world_uid_pk) ON DELETE CASCADE,
PRIMARY KEY (moon_uid_pk));
