CREATE TABLE IF NOT EXISTS STAR_SYSTEM (
star_system_uid_pk TEXT DEFAULT '',
galaxy_uid_fk TEXT DEFAULT '',
star_system_name TEXT DEFAULT '',
is_black_hole BOOLEAN DEFAULT 0,
is_pulsar BOOLEAN DEFAULT 0,
boundary_pc_x NUMERIC DEFAULT 0.0,
boundary_pc_y NUMERIC DEFAULT 0.0,
boundary_pc_z NUMERIC DEFAULT 0.0,
volume_pc3 NUMERIC DEFAULT 0.0,
mass_kg NUMERIC DEFAULT 0.0,
system_shape TEXT DEFAULT 'ellipsoid',
center_from_galaxy_center_pc_x NUMERIC DEFAULT 0.0,
center_from_galaxy_center_pc_y NUMERIC DEFAULT 0.0,
center_from_galaxy_center_pc_z NUMERIC DEFAULT 0.0,
system_dim_axes_a NUMERIC DEFAULT 0.0,
system_dim_axes_b NUMERIC DEFAULT 0.0,
system_dim_axes_c NUMERIC DEFAULT 0.0,
system_dim_rot_pitch NUMERIC DEFAULT 0.0,
system_dim_rot_yaw NUMERIC DEFAULT 0.0,
system_dim_rot_roll NUMERIC DEFAULT 0.0,
relative_size TEXT DEFAULT 'medium',
spectral_class TEXT DEFAULT 'G',
aprox_age_gyr NUMERIC DEFAULT 0.0,
luminosity_class TEXT DEFAULT 'V',
frequency_of_flares TEXT DEFAULT 'rare',
intensity_of_flares TEXT DEFAULT 'low',
frequency_of_comets TEXT DEFAULT 'rare',
unbound_planets_cnt INTEGER DEFAULT 0,
orbiting_planets_cnt INTEGER DEFAULT 0,
inner_habitable_boundary_au NUMERIC DEFAULT 0.0,
outer_habitable_boundary_au NUMERIC DEFAULT 0.0,
planetary_orbits_shape TEXT DEFAULT 'circular',
orbital_stability TEXT DEFAULT 'stable',
asteroid_belt_density TEXT DEFAULT 'sparse',
asteroid_belt_loc TEXT DEFAULT 'inner',
delete_dt TEXT DEFAULT '',
CHECK (relative_size IN ('small', 'medium', 'large')),
CHECK (spectral_class IN ('O', 'B', 'A', 'F', 'G', 'K', 'M')),
CHECK (luminosity_class IN ('I', 'II', 'III', 'IV', 'V')),
CHECK (system_shape IN ('ellipsoid', 'spherical')),
CHECK (planetary_orbits_shape IN ('circular', 'elliptical')),
CHECK (orbital_stability IN ('stable', 'unstable')),
CHECK (asteroid_belt_density IN ('sparse', 'dense')),
CHECK (asteroid_belt_loc IN ('inner', 'outer', 'multiple')),
CHECK (frequency_of_flares IN ('rare', 'occasional', 'frequent')),
CHECK (intensity_of_flares IN ('low', 'medium', 'high')),
CHECK (frequency_of_comets IN ('rare', 'occasional', 'frequent')),
FOREIGN KEY (galaxy_uid_fk) REFERENCES GALAXY(galaxy_uid_pk) ON DELETE CASCADE,PRIMARY KEY (star_system_uid_pk));
