CREATE TABLE IF NOT EXISTS GRID_INFO (
grid_info_uid_pk TEXT DEFAULT '',
grid_uid_fk TEXT DEFAULT '',
grid_cell_uid_fk TEXT DEFAULT '',
grid_name TEXT DEFAULT '',
grid_cell_name TEXT DEFAULT '',
grid_info_id TEXT DEFAULT '',
grid_info_name TEXT DEFAULT '',
grid_info_int INTEGER DEFAULT 0,
grid_info_float NUMERIC DEFAULT 0.0,
grid_info_str TEXT DEFAULT '',
grid_info_json TEXT DEFAULT '',
grid_info_img_path TEXT DEFAULT '',
grid_info_img BLOB DEFAULT 'b''',
delete_dt TEXT DEFAULT '',
FOREIGN KEY (grid_cell_uid_fk) REFERENCES GRID_CELL(grid_cell_uid_pk) ON DELETE CASCADE,
FOREIGN KEY (grid_uid_fk) REFERENCES GRID(grid_uid_pk) ON DELETE CASCADE,PRIMARY KEY (grid_info_uid_pk));
