CREATE TABLE IF NOT EXISTS OCEAN_BODY (
ocean_body_uid_pk TEXT DEFAULT '',
gloss_common_uid_fk TEXT DEFAULT '',
body_shoreline_points_json TEXT DEFAULT '',
is_coastal BOOLEAN DEFAULT 1,
is_frozen BOOLEAN DEFAULT 0,
ocean_body_type TEXT DEFAULT '',
water_type TEXT DEFAULT '',
is_tidal_influence BOOLEAN DEFAULT 0,
tidal_flows_per_day INTEGER DEFAULT 0,
avg_high_tide_m NUMERIC DEFAULT 0.0,
avg_low_tide_m NUMERIC DEFAULT 0.0,
max_high_tide_m NUMERIC DEFAULT 0.0,
ocean_wave_type TEXT DEFAULT '',
body_surface_area_m2 NUMERIC DEFAULT 0.0,
body_surface_altitude_m NUMERIC DEFAULT 0.0,
max_depth_m NUMERIC DEFAULT 0.0,
avg_depth_m NUMERIC DEFAULT 0.0,
ocean_hazards_json JSON DEFAULT '',
ocean_features_json JSON DEFAULT '',
delete_dt TEXT DEFAULT '',
CHECK (ocean_body_type IN ('fjord', 'sea', 'ocean', 'harbor', 'lagoon', 'bay', 'gulf', 'sound', 'bight', 'delta', 'estuary', 'strait', 'ice field', 'ice sheet', 'ice shelf', 'iceberg', 'ice floe', 'ice pack', 'roadstead', 'tidal pool', 'salt marsh')),
CHECK (water_type IN ('freshwater', 'saline', 'brackish')),
CHECK (ocean_wave_type IN ('low', 'medium', 'high', 'none')),
FOREIGN KEY (gloss_common_uid_fk) REFERENCES GLOSS_COMMON(gloss_common_uid_pk) ON DELETE CASCADE,
PRIMARY KEY (ocean_body_uid_pk));
