CREATE TABLE IF NOT EXISTS GALAXY (
galaxy_uid_pk TEXT DEFAULT '',
galactic_cluster_uid_fk TEXT DEFAULT '',
galaxy_name TEXT DEFAULT '',
relative_size TEXT DEFAULT 'medium',
center_from_univ_center_kpc_x NUMERIC DEFAULT 0.0,
center_from_univ_center_kpc_y NUMERIC DEFAULT 0.0,
center_from_univ_center_kpc_z NUMERIC DEFAULT 0.0,
halo_radius_pc NUMERIC DEFAULT 0.0,
boundary_pc_x NUMERIC DEFAULT 0.0,
boundary_pc_y NUMERIC DEFAULT 0.0,
boundary_pc_z NUMERIC DEFAULT 0.0,
volume_gpc3 NUMERIC DEFAULT 0.0,
mass_kg NUMERIC DEFAULT 0.0,
bulge_shape TEXT DEFAULT 'ellipsoid',
bulge_center_from_center_ly_x NUMERIC DEFAULT 0.0,
bulge_center_from_center_ly_y NUMERIC DEFAULT 0.0,
bulge_center_from_center_ly_z NUMERIC DEFAULT 0.0,
bulge_dim_axes_a NUMERIC DEFAULT 0.0,
bulge_dim_axes_b NUMERIC DEFAULT 0.0,
bulge_dim_axes_c NUMERIC DEFAULT 0.0,
bulge_dim_rot_pitch NUMERIC DEFAULT 0.0,
bulge_dim_rot_yaw NUMERIC DEFAULT 0.0,
bulge_dim_rot_roll NUMERIC DEFAULT 0.0,
bulge_black_hole_mass_kg NUMERIC DEFAULT 0.0,
bulge_volume_ly3 NUMERIC DEFAULT 0.0,
bulge_total_mass_kg NUMERIC DEFAULT 0.0,
star_field_shape TEXT DEFAULT 'ellipsoid',
star_field_dim_from_center_ly_x NUMERIC DEFAULT 0.0,
star_field_dim_from_center_ly_y NUMERIC DEFAULT 0.0,
star_field_dim_from_center_ly_z NUMERIC DEFAULT 0.0,
star_field_dim_axes_a NUMERIC DEFAULT 0.0,
star_field_dim_axes_b NUMERIC DEFAULT 0.0,
star_field_dim_axes_c NUMERIC DEFAULT 0.0,
star_field_dim_rot_pitch NUMERIC DEFAULT 0.0,
star_field_dim_rot_yaw NUMERIC DEFAULT 0.0,
star_field_dim_rot_roll NUMERIC DEFAULT 0.0,
star_field_vol_ly3 NUMERIC DEFAULT 0.0,
star_field_mass_kg NUMERIC DEFAULT 0.0,
interstellar_mass_kg NUMERIC DEFAULT 0.0,
delete_dt TEXT DEFAULT '',
CHECK (relative_size IN ('small', 'medium', 'large')),
CHECK (bulge_shape IN ('ellipsoid', 'spherical')),
CHECK (star_field_shape IN ('ellipsoid', 'spherical')),
FOREIGN KEY (galactic_cluster_uid_fk) REFERENCES GALACTIC_CLUSTER(galactic_cluster_uid_pk) ON DELETE CASCADE,PRIMARY KEY (galaxy_uid_pk));
