CREATE TABLE IF NOT EXISTS LINKS (
link_uid_pk TEXT DEFAULT '',
lang_code TEXT DEFAULT '',
link_id TEXT DEFAULT '',
frame_id TEXT DEFAULT '',
link_protocol TEXT DEFAULT '',
mime_type TEXT DEFAULT '',
link_name TEXT DEFAULT '',
link_value TEXT DEFAULT '',
link_icon TEXT DEFAULT '',
delete_dt TEXT DEFAULT '',
CHECK (link_protocol IN ('https', 'http', 'ftp', 'sftp', 'ssh', 'wc')),
CHECK (lang_code IN ('en')),
CHECK (mime_type IN ('image/png', 'image/jpeg', 'image/gif', 'image/svg+xml', 'image/tiff', 'image/bmp', 'image/webp', 'text/plain', 'text/html', 'text/css', 'text/csv', 'text/xml', 'text/javascript', 'application/pdf', 'application/json', 'application/xml', 'audio/mpeg', 'audio/wav', 'audio/ogg', 'video/mp4', 'video/ogg', 'video/webm')),
PRIMARY KEY (link_uid_pk));
