CREATE TABLE IF NOT EXISTS MAP (
map_uid_pk TEXT DEFAULT '',
version_id TEXT DEFAULT '',
map_name TEXT DEFAULT '',
map_type TEXT DEFAULT '',
unit_of_measure TEXT DEFAULT '',
origin_2d_lat NUMERIC DEFAULT 0.0,
origin_2d_lon NUMERIC DEFAULT 0.0,
width_e_w_2d NUMERIC DEFAULT 0.0,
height_n_s_2d NUMERIC DEFAULT 0.0,
avg_alt_m NUMERIC DEFAULT 0.0,
min_alt_m NUMERIC DEFAULT 0.0,
max_alt_m NUMERIC DEFAULT 0.0,
origin_3d_x NUMERIC DEFAULT 0.0,
origin_3d_y NUMERIC DEFAULT 0.0,
origin_3d_z NUMERIC DEFAULT 0.0,
width_3d NUMERIC DEFAULT 0.0,
height_3d NUMERIC DEFAULT 0.0,
depth_3d NUMERIC DEFAULT 0.0,
delete_dt TEXT DEFAULT '',
CHECK (map_type IN ('geo', 'astro', 'underwater', 'underground', 'informational', 'political')),
PRIMARY KEY (map_uid_pk));
