CREATE TABLE IF NOT EXISTS MAP_SPHERE (
map_sphere_uid_pk TEXT DEFAULT '',
map_shape TEXT DEFAULT '',
map_type TEXT DEFAULT '',
map_name TEXT DEFAULT '',
map_desc TEXT DEFAULT '',
origin_lat NUMERIC DEFAULT 0.0,
origin_lon NUMERIC DEFAULT 0.0,
z_value NUMERIC DEFAULT 0.0,
unit_of_measure TEXT DEFAULT '',
sphere_radius NUMERIC DEFAULT 0.0,
delete_dt TEXT DEFAULT '',
CHECK (map_shape IN ('rectangle', 'box', 'sphere')),
CHECK (map_type IN ('geo', 'astro', 'underwater', 'underground', 'info', 'political')),
CHECK (unit_of_measure IN ('AU', 'GLY', 'GPC', 'KPC', 'LM', 'LS', 'LY', 'MPC', 'CM', 'FT', 'GA', 'IN', 'KA', 'KM', 'M', 'MI', 'MM', 'NM', 'NOB', 'THWAB', 'TWA', 'YUZA', 'DGLAT', 'DGLONG')),
PRIMARY KEY (map_sphere_uid_pk));
