CREATE TABLE IF NOT EXISTS FRAMES (
frame_uid_pk TEXT DEFAULT '',
lang_uid_fk TEXT DEFAULT '',
app_catg TEXT DEFAULT '',
version_id TEXT DEFAULT '',
frame_name TEXT DEFAULT '',
frame_title TEXT DEFAULT '',
frame_desc TEXT DEFAULT '',
size_w NUMERIC DEFAULT 0.0,
size_h NUMERIC DEFAULT 0.0,
ibar_x NUMERIC DEFAULT 0.0,
ibar_y NUMERIC DEFAULT 0.0,
pg_hdr_x NUMERIC DEFAULT 0.0,
pg_hdr_y NUMERIC DEFAULT 0.0,
pg_hdr_w NUMERIC DEFAULT 0.0,
pg_hdr_h NUMERIC DEFAULT 0.0,
pg_hdr_txt TEXT DEFAULT '',
CHECK (app_catg IN ('admin', 'game')),
FOREIGN KEY (lang_uid_fk) REFERENCES LANGUAGE(lang_uid_pk) ON DELETE CASCADE,
PRIMARY KEY (frame_uid_pk));
