CREATE TABLE IF NOT EXISTS APP_CONFIG (
config_uid_pk TEXT DEFAULT '',
version_id TEXT DEFAULT '',
root_dir TEXT DEFAULT '',
mem_dir TEXT DEFAULT '',
cfg_dir TEXT DEFAULT '',
dat_dir TEXT DEFAULT '',
html_dir TEXT DEFAULT '',
img_dir TEXT DEFAULT '',
snd_dir TEXT DEFAULT '',
py_dir TEXT DEFAULT '',
db_dir TEXT DEFAULT '',
log_dir TEXT DEFAULT '',
mon_dir TEXT DEFAULT '',
dbg_dir TEXT DEFAULT '',
PRIMARY KEY (config_uid_pk));
