INSERT INTO `METADATA` (
`meta_uid_pk`,
`name_space`,
`model_name`,
`tbl_name`,
`col_name`,
`col_def`,
`delete_ts`) VALUES 
("xamAn9W8tipinQCWAYPKRvPkSnmb3On93aj5snGzz10", "app", "Metadata", "METADATA", "meta_uid_pk", "Primary key", ""),
("5jIwDjFFq2jP-K1IdaG38ul8g3shw_qxFjHIPMXn5uE", "app", "Metadata", "METADATA", "name_space", "[app|story]", ""),
("optsJCqZB7HylsFeHAYq7l7qCYu_d5UznNzdVaxh0Rw", "app", "Metadata", "METADATA", "model_name", "name of the data model class", ""),
("WEwW1vSxGKDo4srN6XtclvUvL5_k8DR8mlg2Nuk2AI8", "app", "Metadata", "METADATA", "tbl_name", "name of the SQL table", ""),
("pOC-DU59upO4L3sIRKcyCeua_iZttvIkULKiyLqPQCs", "app", "Metadata", "METADATA", "col_name", "name of the SQL column", ""),
("G4bSSMP31T5sVmSVqchIBw-rSgCLmrlswMadlLchxC0", "app", "Metadata", "METADATA", "col_def", "definition of the SQL column", ""),
("vIxV51r6QpfhTH1bBWW6jhZ4xKkrgug9cRbI0TJZ1eQ", "app", "Metadata", "METADATA", "delete_ts", "date/time of virtual deletion", ""),
("oTdubJOaE1fvHWNXDhUguOzY5aNykjX0AcSMKouWqd8", "app", "Backup", "BACKUP", "bkup_uid_pk", "Primary key", ""),
("RdOsTarbTd6Y5wgByWXGkAmae0guKBN4HdJKqsN3ReE", "app", "Backup", "BACKUP", "bkup_name", "Name of the backup", ""),
("KxVNYdOJ-1yu07LI1JYT76bTV4mWqjQzRXZZtaNbB-k", "app", "Backup", "BACKUP", "bkup_dttm", "Date and time of the backup", ""),
("r8tYRToCR7AZD7CST-evhfnT1qU7uUfSs39J0QLywrs", "app", "Backup", "BACKUP", "bkup_type", "Type of backup, e.g., full, incremental", ""),
("yt2IC6c0gWdTEtn6AV0ts5q9V4ieIKbp-dDRH5GLSUs", "app", "Backup", "BACKUP", "file_from", "Source file or directory", ""),
("40G51wy-eKp0-1K1wOd1Tpt8nRpXSIQNCQGihFaemEU", "app", "Backup", "BACKUP", "file_to", "Destination file or directory", ""),
("GWE9Unz3q6Avectd9mNU-TDYrxeub67FnecBtKr5-k4", "app", "Backup", "BACKUP", "delete_dt", "Date and time the record was deleted", ""),
("UuiT_6UoH57uiNGAQGd2C0wPxxr8T1aMsZQYkT_tSWM", "app", "Texts", "TEXTS", "text_uid_pk", "Primary key, unique identifier for each text entry", ""),
("gkE2XhMCY6ebGUKWTkkTr4LWZqJOrpp9IC12QAuXHLw", "app", "Texts", "TEXTS", "lang_code", "Language code of the text, e.g., en, de, fr", ""),
("XKceqG2XqYwifTRpj1GcW4-OCMEsSB-XY8vryeKIHqI", "app", "Texts", "TEXTS", "text_name", "Name/ID/label of a text string, not unique, shared across languages", ""),
("zUoK23KjBS1j4sHcm5ajz4MB7gmEPxvipYDOUN5SCDg", "app", "Texts", "TEXTS", "text_value", "Text string value", ""),
("Td8kbZfH3eKRPVVHip7ftMTwoebLfkfm_vm55LTToY0", "app", "Texts", "TEXTS", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("4qA881VYOqaWvMmyZQG_u8MY9saoZI_FqbaZ3J2mUsA", "app", "Frames", "FRAMES", "frame_uid_pk", "Primary key, unique identifier for each frame entry", ""),
("dk5VEP2jG_Oj0kPrpOQ1EKiz6r61htANj5cuyEJNJvo", "app", "Frames", "FRAMES", "lang_code", "Language code of the frame, e.g., en, de, fr", ""),
("KSbDSqVFNrHpMQqgyEPc60iGi1DUURRj5MxkBYFBJbo", "app", "Frames", "FRAMES", "frame_id", "Not unique, can be shared by apps, e.g., admin or game", ""),
("qIVxPOBeGJ7YMpdKQu96tdBhp2hmkSVj8RLdPtzBd6c", "app", "Frames", "FRAMES", "frame_title", "Title of the frame", ""),
("vh0Qf-olHVDdAm3g2nWwknoIuY5AQoslhck6NtHJ-G0", "app", "Frames", "FRAMES", "frame_desc", "Description of the frame", ""),
("p2-Cned0enfB5d3JBS4N8B0oWfziLd6Awz41DO5oWlw", "app", "Frames", "FRAMES", "frame_w", "Width of the frame", ""),
("uks6WbymdciN5x6Aow6gNpEQY_peVXk7u4oHKqMDqDo", "app", "Frames", "FRAMES", "frame_h", "Height of the frame", ""),
("zrYSZOkibL5bVcP33gEcXlsMl3Xgv34kt2mGcA3ghrA", "app", "Frames", "FRAMES", "pg_hdr_x", "X-coordinate of the page header", ""),
("gs_KSlFERqzEXl5-bSKRXtNs94qh0URrwPPGZfnkDIU", "app", "Frames", "FRAMES", "pg_hdr_y", "Y-coordinate of the page header", ""),
("B0UoDJGrDWQpqWbLriivwoKlhfxQrf3SX2ON0RSdrTg", "app", "Frames", "FRAMES", "pg_hdr_w", "Width of the page header", ""),
("GgZuP2FONYPK0MDRiuNKBqJhthtQFhAbdMYJsVypoEQ", "app", "Frames", "FRAMES", "pg_hdr_h", "Height of the page header", ""),
("ORiaV7jMxEvOHDxwYJWTcBb7jc2IWREhoyRtqVcSfxI", "app", "Frames", "FRAMES", "pg_hdr_txt", "Text displayed in the page header", ""),
("zdDLcWcXoRqmGlKS5GZkW8hfrrZAj5rlzab3rFmtuvc", "app", "Frames", "FRAMES", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("tebbvcu9OYWsS_nhhgGSvAJQ56oxQ2WAJg0wl88mkF8", "app", "MenuBars", "MENU_BARS", "menu_bar_uid_pk", "Primary key, unique identifier for each menu bar entry", ""),
("kraivqYq9qT-B4ZnhAFrcm7L-HMirybchqzFqLJ9uQQ", "app", "MenuBars", "MENU_BARS", "frame_uid_fk", "Foreign key referencing the frames unique identifier", ""),
("1lQS7EcK8hAqpm2L8JUwoJswPoHY8KoO8jWWBRcmOo0", "app", "MenuBars", "MENU_BARS", "frame_id", "Identifier to match with corresponding frame records", ""),
("Jemj06IR9b6Hwnh5zI09zZCUMgLiVH_sod3aNHSBZC8", "app", "MenuBars", "MENU_BARS", "mbar_margin", "Margin around the menu bar", ""),
("_xFX0PnaXmPKI1dRpNzxtFgKykYdyih2jzrlrNqsnmo", "app", "MenuBars", "MENU_BARS", "mbar_h", "Height of the menu bar", ""),
("Ol2xLu2ARzwDlzIVX5fcQ5affWiPakbon_Vm8v8cTPA", "app", "MenuBars", "MENU_BARS", "mbar_x", "X-coordinate of the top-left corner relative to the frame", ""),
("WHCoaY_Ez79N8ceqF_1zbd5fvOMDHZ0G5V0qdHm0kQM", "app", "MenuBars", "MENU_BARS", "mbar_y", "Y-coordinate of the top-left corner relative to the frame", ""),
("1zPUfHDpVCwGQ_KyFsBTXlP_kl1FrL_IBODTkI4A_Bg", "app", "MenuBars", "MENU_BARS", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("EA182Hj8uyjqJdvnN9CkSf-DtB1DeZ5XLNtfKayQWuk", "app", "Menus", "MENUS", "menu_uid_pk", "Primary key, unique identifier for each menu entry", ""),
("kbEIykdlA4zXrph2fJVJaPvgGmu6c6ptMkUEntnDJQE", "app", "Menus", "MENUS", "menu_bar_uid_fk", "Foreign key referencing the associated menu bar", ""),
("11X58EbnQyur5ZcM6XB7K_o2YUElFNSXcpWgcp6preY", "app", "Menus", "MENUS", "frame_id", "Identifier to match with corresponding frame records", ""),
("2KiurWk2yxNxExIug3bO4tlKiwbIj2THBkLcsGQS7Kc", "app", "Menus", "MENUS", "lang_code", "Language code for the menu text", ""),
("tSzISbtFnn1WmwVgZ3RCEQksjzEO-NWz7rJx0LxSE88", "app", "Menus", "MENUS", "menu_id", "Generic string label ID or key for menu", ""),
("lCcpYEjarLLaJNXPyMk-sjx3YkoEgqP3Ac3p8BvbSm0", "app", "Menus", "MENUS", "menu_name", "Text string label for menu in designated language", ""),
("1fMxg_0tUX-bqyczu7xLUx7YCxPcCbQliYa2HwftAas", "app", "Menus", "MENUS", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("tUpgiuW6M-7fK6YCSjMO4MT41shetqosrawY-1PrqyI", "app", "MenuItems", "MENU_ITEMS", "item_uid_pk", "Primary key, unique identifier for each menu item entry", ""),
("HmZy04TDucctQrWKle7iHHgKoOpXAY1arjB2cCITvlE", "app", "MenuItems", "MENU_ITEMS", "menu_uid_fk", "Foreign key referencing the associated menu", ""),
("GcjaNR73bd7_Xk1arubrOGtNIqtKtkUYBo1hsYfW9ow", "app", "MenuItems", "MENU_ITEMS", "lang_code", "Language code for the menu item text", ""),
("5apzQ70QYMAZU_P5lw3QvfLvDu3tBi88pLsjeHUYsBE", "app", "MenuItems", "MENU_ITEMS", "frame_id", "Identifier to match with corresponding frame records", ""),
("0NC_VwjlKmg80gTHIBPBXD9uXr-7WlLfKbRddTb-azo", "app", "MenuItems", "MENU_ITEMS", "item_id", "Generic string label ID or key for menu item", ""),
("_peSXvP2vcCWCnym1GaDBTyNVVdTK6Xf4Eym1qLSOEo", "app", "MenuItems", "MENU_ITEMS", "item_order", "Order of the item within the menu", ""),
("7k-1wLshbeN-9d8720dMxflsFgZ_O-qtTzlGw5gT5UQ", "app", "MenuItems", "MENU_ITEMS", "item_name", "Text string label for menu item in designated language", ""),
("onLCWBXfyfo4d1dC6GdCRCUWGMqX1vSl_nePwvawnZs", "app", "MenuItems", "MENU_ITEMS", "key_binding", "Shortcut key binding for the menu item", ""),
("gHm9UiMRQGfq3cGcuCF1RY-64sli_JzTrJRqi8qiwIk", "app", "MenuItems", "MENU_ITEMS", "help_text", "Help text or description for the menu item", ""),
("g8nuWZYkYW37B8Jfy0PDHNmkXFyJmuDPNgH26jaNCuE", "app", "MenuItems", "MENU_ITEMS", "enabled_by_default", "Boolean indicating if the item is enabled by default", ""),
("tpnHESdJYqhO0KHPzT4lYyQC61toaM3q0xZ7XBI67ao", "app", "MenuItems", "MENU_ITEMS", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("-vTCOcxdwN123_F9XzBYvCjtIxqHCZEv0eVY_oduaNk", "app", "Windows", "WINDOWS", "win_uid_pk", "Primary key, unique identifier for each window entry", ""),
("jgSEGTLB1qKr-JDJ-iuUapUY9elECN8MfipGkgYh7pM", "app", "Windows", "WINDOWS", "frame_uid_fk", "Foreign key referencing the associated frame", ""),
("FGBEG4hvNb3JjLm5e_eYWFq81zaaj4ShX6KV34S1GQ4", "app", "Windows", "WINDOWS", "frame_id", "Identifier to match with corresponding frame records", ""),
("lADSD19Oa4WSfuTwaYsCWb-KMC2fdazoi7pYglUsmAg", "app", "Windows", "WINDOWS", "lang_code", "Language code for the window text", ""),
("TKdGTWtb3vdQbGZ5IsUMjtsgJfxqcbFBw6wDlBRexX0", "app", "Windows", "WINDOWS", "win_id", "Generic string label ID or key for the window", ""),
("hiE1pqO1pjn9W6b6vaM85wXgAy4J-ROTackjytZUB9M", "app", "Windows", "WINDOWS", "win_title", "Title of the window in designated language", ""),
("7ppWM7NIonesL7NQugG6MUahXnqBs90B5rBtIR28bRw", "app", "Windows", "WINDOWS", "win_margin", "Margin size around the window", ""),
("8mj4s6-YvQ3cNx47gzRJUDuP30z97I5beF6-0QHvCFY", "app", "Windows", "WINDOWS", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("s6wbvzp2xEOiNxuIvQqz5hMsjo1jl6QuUtWs6qCe6EQ", "app", "Links", "LINKS", "link_uid_pk", "Primary key, unique identifier for each link entry", ""),
("1g5BZfWL8SwGh0AJly6iQbwxJ9BBzapZKK97bmSaGlQ", "app", "Links", "LINKS", "lang_code", "Language code associated with the link", ""),
("NID-Eb11mCeYRflOqhpCKAW5Mtv8VzggMHHtIrMQNWQ", "app", "Links", "LINKS", "link_id", "Identifier for the specific link", ""),
("YDo-vaAh66ZvUjYm1MEDYWka0-z1rUFYmO-N8sJEqW8", "app", "Links", "LINKS", "frame_id", "Identifier for the frame associated with the link", ""),
("r-vefBLLFzn7_MliAFJWx2yGivU5js6a_UJYtMMO4m0", "app", "Links", "LINKS", "link_protocol", "Protocol type (e.g., HTTP, HTTPS), used by the link", ""),
("JYNQewh5v_fzSt1JFX3T_L1zvweDollV36IySKAsQz0", "app", "Links", "LINKS", "mime_type", "MIME type specifying the nature of the link content", ""),
("34YLubh3i8cgVRDajBMixlKWjwkvy7Nb_t4rExUqe0o", "app", "Links", "LINKS", "link_name", "Descriptive name of the link", ""),
("DdQHZ3-_sTYPqbnWHTmQ16IBHh-EQDV1J9z7Lp9AyEg", "app", "Links", "LINKS", "link_value", "The actual URI or address represented by the link", ""),
("qN51Csz-ycdXUXHaNlAGUEm6y1_dAr2dA7qzULKiZ6A", "app", "Links", "LINKS", "link_icon", "Icon representing the link visually (stored as BLOB),", ""),
("FMFo6LRy87LcNDFtjPeQs1tTe9bae1rumrG2yrmrs7I", "app", "Links", "LINKS", "link_icon_path", "Path to the icon file", ""),
("oyVV6QqXbxU10ZesBGQFFBc2qXwklk5nQXtmH4mQLhc", "app", "Links", "LINKS", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("eNlLoXOUDozlZco2Z3XBh7c2TPLkAqNcdmOnfSgJxAA", "app", "ButtonSingle", "BUTTON_SINGLE", "button_single_uid_pk", "Primary key, unique identifier for each button entry", ""),
("YNrtGHOfEeN1e1W4b9taecUpepYWmLMB3sH0Odl2T24", "app", "ButtonSingle", "BUTTON_SINGLE", "button_type", "Type of button (e.g., submit, reset),", ""),
("34uVr_ufBCIUYyYQVNaWwxOEdblNJ1KIUq25xqXjTyk", "app", "ButtonSingle", "BUTTON_SINGLE", "button_name", "Displayed name for the button", ""),
("SXTdnmUeUsW17VXgkd78Ani0BLq3bDF9ZTELkdQZf-c", "app", "ButtonSingle", "BUTTON_SINGLE", "button_icon", "Binary data representing the buttons icon image", ""),
("g2rEINHpx6d3xAbGZv7qenJtIJ5tX_2K8_ofCzxCMfk", "app", "ButtonSingle", "BUTTON_SINGLE", "button_icon_path", "Path to the icon file in the app images directory", ""),
("v0tOyQoJT2quUWE_Xi4MS3NFRvzmBPQsjexMg4mRcsc", "app", "ButtonSingle", "BUTTON_SINGLE", "button_key", "Key to press to activate the button", ""),
("2yoVuzzBIG2v6OkvJwIdfuqc3B0Us_canw03BDc-dUA", "app", "ButtonSingle", "BUTTON_SINGLE", "frame_uid_fk", "Foreign key linking to the associated frame", ""),
("cgC5ln8VBSNhWNsLxPnf6s93x28pnAmrcFIDWy1i97s", "app", "ButtonSingle", "BUTTON_SINGLE", "window_uid_fk", "Foreign key linking to the associated window", ""),
("JbfReIsITlnr_La1kdaYYY3GVUFbhKH6hs2Zg8LvtW8", "app", "ButtonSingle", "BUTTON_SINGLE", "left_x", "X-coordinate position of top-left corner relative to the window", ""),
("gfsuutGc1enA3BKrUYGHPLirxHTcMDFh7r5WSW-m7m0", "app", "ButtonSingle", "BUTTON_SINGLE", "top_y", "Y-coordinate position of top-left corner relative to the window", ""),
("oUX5aeoTccxfBkDHKXOHZx9LAwI0cuAlRiqOFern2aE", "app", "ButtonSingle", "BUTTON_SINGLE", "enabled_by_default", "True to enable, False to disable the button", ""),
("Nes_ZEozFT_e4oRUu6Wvc5Ryh5H9MAC0XzJcwxIeoGU", "app", "ButtonSingle", "BUTTON_SINGLE", "help_text", "Text to display when the mouse hovers over the button", ""),
("hPTsTkAGdYKt85o4HCdheeDCTNF1lP0v9G9PhYBLeLU", "app", "ButtonSingle", "BUTTON_SINGLE", "action", "Name of the function to call when the button is clicked", ""),
("d5L0r2apy1UH__MwaB9YB2k_m8HPy-mmXsiX0WFx5M8", "app", "ButtonSingle", "BUTTON_SINGLE", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("QBtU_8fw7osRcIGX6-OBJHx1WIxRSe7w52bEtDyFtXM", "app", "ButtonMulti", "BUTTON_MULTI", "button_multi_uid_pk", "Primary key, unique identifier for each button group entry", ""),
("M0bMk_Hgn2uPAxtBWEzTHywZ3aXLj7b-Y5bXB7dlFJM", "app", "ButtonMulti", "BUTTON_MULTI", "button_type", "Type of button group (e.g., radio, checkbox),", ""),
("uRtNr5x5EgssHURF_ewjsrRxOUNX_l6yoD9cU44hkyA", "app", "ButtonMulti", "BUTTON_MULTI", "button_name", "Displayed name for the button group", ""),
("ap50Sr4uEJjLLdm7OpKsxOXPTR2MAtXUKm-lL3bD26k", "app", "ButtonMulti", "BUTTON_MULTI", "button_icon", "Binary data representing the button groups icon image", ""),
("rnWpI1QTfgW149M-1Ec-3IJHaI_esgY1kO2AOqkEVf8", "app", "ButtonMulti", "BUTTON_MULTI", "button_icon_path", "Path to the icon file in the app images directory", ""),
("4H3_XxrG8YvPImvO39G_W4Vc6NQv3XZT0_TulrjYoN4", "app", "ButtonMulti", "BUTTON_MULTI", "frame_uid_fk", "Foreign key linking to the associated frame", ""),
("3xm3QEy4UwXIjB3TQIRplRrkrqg4lbrzvlvDbdOGPDY", "app", "ButtonMulti", "BUTTON_MULTI", "window_uid_fk", "Foreign key linking to the associated window", ""),
("IlIbLd0LH_EWoqxJtnwHx_FjbZqMkRvJ2gHFPDmnmFA", "app", "ButtonMulti", "BUTTON_MULTI", "x", "X-coordinate position of top-left corner relative to the window", ""),
("W7K3Qfs1mqouyej1rEqQ7x4UcQJ5sp5NYsJFZz13aDw", "app", "ButtonMulti", "BUTTON_MULTI", "y", "Y-coordinate position of top-left corner relative to the window", ""),
("dd9iSHY-nmiPDE1RNzSZxr8LKymN-65NMdWD3YxTwqQ", "app", "ButtonMulti", "BUTTON_MULTI", "enabled_by_default", "True to enable, False to disable the button group", ""),
("Mmynk2AtJ97DCdXxnzGnF0dey6PP7Tm3UeIxPuNWBhE", "app", "ButtonMulti", "BUTTON_MULTI", "help_text", "Text to display when the mouse hovers over the button group", ""),
("VWm7gZ4uVpFdbghwN6KVr6O4paj5yNKGKJHfeT5rm3k", "app", "ButtonMulti", "BUTTON_MULTI", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("an4Genwe0fs3qfPcHtN418uRJQphbJm3EOEq1KKhduE", "app", "ButtonItem", "BUTTON_ITEM", "button_item_uid_pk", "Primary key, unique identifier for each button item", ""),
("BIoDlsq_qEqHRHX2McoQ1TKb-Dad2V1nmfXU3QnLSCI", "app", "ButtonItem", "BUTTON_ITEM", "button_multi_uid_fk", "Foreign key linking to the associated multi-choice button group", ""),
("1YkeQVWGXHSJsK_iigjQQJRV7r-ePJRefEgNoVbXQ-k", "app", "ButtonItem", "BUTTON_ITEM", "button_name", "Displayed name for the button item", ""),
("zE9fY-aipYrE8YFPk4abKlKAXxgX_yahLeNzGK62H3s", "app", "ButtonItem", "BUTTON_ITEM", "button_icon", "Binary data representing the button items icon image", ""),
("10Ex41reCVW-EDzuIExm1eLuKnYFNgMGuwZXWRU_knM", "app", "ButtonItem", "BUTTON_ITEM", "button_icon_path", "Path to the icon file in the app images directory", ""),
("WhyHzJUt2p-LxEfwZQgPxGUSSJi0-knNHEeLKHjOGWI", "app", "ButtonItem", "BUTTON_ITEM", "button_order", "Integer defining the display order of the button item within the group", ""),
("6mLcruAbXPfA2SK2ubI941jerARE6w4Iipu5O93a7FI", "app", "ButtonItem", "BUTTON_ITEM", "button_action", "Action or command executed when the button is pressed", ""),
("QEin1z7qEOO1KyUAY04cV0Xaj2xmxSI91MnBYBDxh-4", "app", "ButtonItem", "BUTTON_ITEM", "enabled_by_default", "True to enable, False to disable the button item by default", ""),
("tWAs0M9dlhMCcXG2LWciBmWWw8dVw4r33cL6k9R4aVg", "app", "ButtonItem", "BUTTON_ITEM", "is_enabled", "Indicates if the button item is currently enabled", ""),
("AM39ZR8E1mlhVNM8aygrvHzQjmPCoGsehwUt0JSLt24", "app", "ButtonItem", "BUTTON_ITEM", "help_text", "Text to display when the mouse hovers over the button item", ""),
("il8NIp_S1OVyqhwgZgTB-tRle8Z4-0D8YiyQgk5PCa8", "app", "ButtonItem", "BUTTON_ITEM", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("oQ7BKdJuuATOc9y2vsYMXcXkiq6RWTDyQUpy3eZ2JbA", "story", "MapRect", "MAP_RECT", "map_rect_uid_pk", "Primary key, unique identifier for each map rectangle", ""),
("3yoCkA9rA9dUmdSPXcE_4HpryVRLzBC3tA5cyLhNk2g", "story", "MapRect", "MAP_RECT", "map_shape", "Shape of the map area (e.g., rectangle, box, sphere),", ""),
("1pBnvlUGE5IOwWJN5gud59KKlHBwQHhZoOFcGZAIHWc", "story", "MapRect", "MAP_RECT", "map_type", "Type of map area (e.g., geo, astro, underwater),", ""),
("mtIfcEC89nXJIydwiqBYp1mkHs_pLSSRzBmT5cxbdiw", "story", "MapRect", "MAP_RECT", "map_name", "Name of the map rectangle", ""),
("3bSp706R_9htpMgfFAoD30GQSWYGYrUSuxZJXmAqbFo", "story", "MapRect", "MAP_RECT", "map_desc", "Description of the map rectangle", ""),
("rRb44YRuzvSkojb042Zuc7AlJDSCvpnaMoqQSQeS_R8", "story", "MapRect", "MAP_RECT", "north_lat", "Northern latitude boundary of the map rectangle", ""),
("lWn7bIVUA7B2kETyfRvRBiSydZcYLdzg43h2DVQuzhg", "story", "MapRect", "MAP_RECT", "south_lat", "Southern latitude boundary of the map rectangle", ""),
("JVt5tFIsD06eTcKHM8mUFsT-FgN5hgumeA3MU9xrBP8", "story", "MapRect", "MAP_RECT", "east_lon", "Eastern longitude boundary of the map rectangle", ""),
("7R6GFPuIsOOOrgHmMCI944_G-aGTCUVpFDfB0hcX4dk", "story", "MapRect", "MAP_RECT", "west_lon", "Western longitude boundary of the map rectangle", ""),
("4e3RLechPC9X8yOJfFoH0URUk8uOvOi2MZ_Hr0uHvSA", "story", "MapRect", "MAP_RECT", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("isEp35OMnnRwclhUayOQS7la_G2uJSurGVyQTgaYwEY", "story", "MapBox", "MAP_BOX", "map_box_uid_pk", "Primary key, unique identifier for each map box", ""),
("QKqPk_E2EXWEzJ2i9fXl7NHuNqwTdkm3MRu9nC41NS4", "story", "MapBox", "MAP_BOX", "map_shape", "Shape of the map area (e.g., box),", ""),
("Bv_SEyZH7Cin3pXWKuKFXDVxajeEjxbZE_n6njDztv8", "story", "MapBox", "MAP_BOX", "map_type", "Type of map area (e.g., geo, astro, underwater),", ""),
("XlPy7ZOHtWrvWYt9BloGcb_QMBnDcwrwI2bolMeRt0o", "story", "MapBox", "MAP_BOX", "map_name", "Name of the map box", ""),
("oFbPPqtbVGmY3AurBBq0Y2H0c4d8-v0VN77x-rjqs-U", "story", "MapBox", "MAP_BOX", "map_desc", "Description of the map box", ""),
("x9PJjllfc32FQKgyXcnc_gD7nPqbzFLoWmqQd4XkiFA", "story", "MapBox", "MAP_BOX", "north_lat", "Northern latitude boundary of the map box", ""),
("6WAYvEBEOqUr64rpujfIdgM6nb3cKQ6ruXcADmp8z1g", "story", "MapBox", "MAP_BOX", "south_lat", "Southern latitude boundary of the map box", ""),
("o8SXvdbsM8KWJwaNkS3R9zGBvU8SNECkr9Ew3UxhkO8", "story", "MapBox", "MAP_BOX", "east_lon", "Eastern longitude boundary of the map box", ""),
("xStybGtsDfCw_aOyYfRU2AsPup_gW6z1ErBbAYuJfJc", "story", "MapBox", "MAP_BOX", "west_lon", "Western longitude boundary of the map box", ""),
("K_iNftiHBbzPbV0bq6ydyBZx0JW5NCZOoL1HhheNcy0", "story", "MapBox", "MAP_BOX", "up_m", "Maximum meters upwards from the base level", ""),
("YM18rAmAsoaJ42RyFsreaLpHMCJXlNgKH-8mWT0ofVs", "story", "MapBox", "MAP_BOX", "down_m", "Maximum meters downwards from the base level", ""),
("yQ5v5cSQ5oySGLOgBX7pPmLv9CALge8CBPz_Bcu_b3g", "story", "MapBox", "MAP_BOX", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("FJ812DwQCuhohOqFL7063nhQyW3ZhhhOGVxDn23uF7k", "story", "MapSphere", "MAP_SPHERE", "map_sphere_uid_pk", "Primary key, unique identifier for each map sphere", ""),
("R3_emhPAQ2MD_apm9SesnBu2UCgs3MVUAw9rhaWGDv8", "story", "MapSphere", "MAP_SPHERE", "map_shape", "Shape of the map area (e.g., sphere),", ""),
("EqPgJ_UCfmVIO_F4p3zzTyN0lP7TcsuGeujFIEQ6DO8", "story", "MapSphere", "MAP_SPHERE", "map_type", "Type of map area (e.g., geo, astro, underwater),", ""),
("3UjXu9weTdLDgTfpI-ef42L3P02m7jQV0GYfQj685sw", "story", "MapSphere", "MAP_SPHERE", "map_name", "Name of the map sphere", ""),
("QWfkdXQh0nT49TZBxXqFur2HieHKSDn6jJ0xqIVpE10", "story", "MapSphere", "MAP_SPHERE", "map_desc", "Description of the map sphere", ""),
("ASpTDUd8LkihPit1qi2wE7rgCFUESPPSYkMxUS2FP5s", "story", "MapSphere", "MAP_SPHERE", "origin_lat", "Latitudinal coordinate of the spheres origin", ""),
("GiXFPY48FIvm8MHGaQ7XEF-nD1gup-_b9wmmxeAFggY", "story", "MapSphere", "MAP_SPHERE", "origin_lon", "Longitudinal coordinate of the spheres origin", ""),
("Yfke8LhdINDY29hAKNWT_XbUHYsaf01q0hyZ21Ygds4", "story", "MapSphere", "MAP_SPHERE", "z_value", "Z coordinate value, indicating height or depth from a reference point", ""),
("kiX0sKWw92nFaiM5diGS65TOwryU2PQ66tCM6D5SBig", "story", "MapSphere", "MAP_SPHERE", "unit_of_measure", "Unit of measure used for dimensions (e.g., meters, parsecs),", ""),
("-j5psReLVKHa6sYNjTZrKxlJ-GJpJ81eEmJeJmxc9fY", "story", "MapSphere", "MAP_SPHERE", "sphere_radius", "Radius of the sphere", ""),
("D2yjJtANsmrF7vaGU1QjHmZ5wrH_Gg4M-M3_SO74e-U", "story", "MapSphere", "MAP_SPHERE", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("LqflA2vCZOVnG3_5EfgCkzOd_6ndEoMKtxS7wTnR4w0", "story", "Grid", "GRID", "grid_uid_pk", "Primary key, unique identifier for each grid", ""),
("8V6Q3oDJ7u_cihAs6gM7yNk5fiKKEEW5ZOvcYoHEcH4", "story", "Grid", "GRID", "grid_name", "Name of the grid", ""),
("K4hB8QKJ2hKzRDxtupNcqYGMM28uFzrdTs_P8iYDVAs", "story", "Grid", "GRID", "x_col_cnt", "Number of columns (east-west direction),", ""),
("4BxYFjIo6rdf4twGUjGkRZmtWCaIbpIckB0zHDXcq6o", "story", "Grid", "GRID", "y_row_cnt", "Number of rows (north-south direction),", ""),
("IsyChLAIh8E7u6plqr0vAQvMhgxk0l1OfUb0IB6va2Y", "story", "Grid", "GRID", "z_up_cnt", "Number of layers above the zeroth row", ""),
("nis55eE6Iv9T2JmJzgFI2OOQhp6SFwQQbVYHbfqvjDQ", "story", "Grid", "GRID", "z_down_cnt", "Number of layers below the zeroth row", ""),
("csYF5aTa770wS6Btv_lzz55hwRYSLhZb0e0LZnzbnwI", "story", "Grid", "GRID", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("U9W4Alp2YHXHYZ3cnkEy_D6HjbUoTHELs-4Pvr9qNKQ", "story", "GridCell", "GRID_CELL", "grid_cell_uid_pk", "Primary key, unique identifier for each grid cell", ""),
("aWPC2DYrT4BpIZ5nLYt0Mi5Wpznp9hDbYJoNnE6yXNQ", "story", "GridCell", "GRID_CELL", "grid_uid_fk", "Foreign key linking to the Grid table", ""),
("Y8G6olcFvry98IPraKjaowseGq-otZ-7SGtMHiAs4Ew", "story", "GridCell", "GRID_CELL", "grid_name", "Name of the grid this cell belongs to", ""),
("t5dAfz2yOSP5DLzNLNFkH76VmxEG_XkLud7wXM0GcLQ", "story", "GridCell", "GRID_CELL", "grid_cell_name", "Optional descriptive name for the grid cell", ""),
("ROfEbK7XJpqegRXznlIwegZcgtUs-recQQ1jCK8IBQM", "story", "GridCell", "GRID_CELL", "x_col_ix", "Zero-based column index (east-west direction),", ""),
("kMvM43FxetTrNUDUrLZgyAPHYgAHNeB90pR0mKt6_zY", "story", "GridCell", "GRID_CELL", "y_row_ix", "Zero-based row index (north-south direction),", ""),
("YA03VG5994CNofJ0z0CM-t7dMPF03-9rb38rA2AtaGU", "story", "GridCell", "GRID_CELL", "z_up_down_ix", "Index indicating vertical position (positive for up, negative for down),", ""),
("s5KCDbQs5y1vf_FtT8sIWhTRTM8HDAXotb5mQmw7L4A", "story", "GridCell", "GRID_CELL", "grid_cell_id", "Tuple representing the x, y, z location in the Grid matrix", ""),
("l2vzV5vCRHcz6v90N2XxWtxIsc8Czx0iHxLJHZgw8m4", "story", "GridCell", "GRID_CELL", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("WvI_UgY6bGD13AQkr404n5Y8qjhx73r3oz8VtohmOAY", "story", "GridInfo", "GRID_INFO", "grid_info_uid_pk", "Primary key, unique ID for each grid info record", ""),
("nZDBhCQMBFEoW0T0K_WLDKo_GASh7Gj6HvvsixxExUc", "story", "GridInfo", "GRID_INFO", "grid_uid_fk", "Foreign key linking to the Grid table", ""),
("fp-XbJnBOv-kSn-AYns87_B0GGaxIANndzjA_V-AAp4", "story", "GridInfo", "GRID_INFO", "grid_cell_uid_fk", "Foreign key linking to the GridCell table", ""),
("SPTYiZJU3bNIr7TO3oQC4k6BsvFR6mRNxPcD9OEqgTM", "story", "GridInfo", "GRID_INFO", "grid_name", "Name of the grid this information belongs to", ""),
("z23WzhrlU1M5BrDqbcJrraCs_9JUzDQzR6kY6FlGtxc", "story", "GridInfo", "GRID_INFO", "grid_cell_name", "Name of grid cell this info is associated with", ""),
("UV-6yt7WZpf0ENnj9GSoncsvTR7YeWx91ZTQ0sq3-uY", "story", "GridInfo", "GRID_INFO", "grid_info_id", "Short descriptive tag for the cell value", ""),
("ZITo5JbbjU3RapgmP6OAC0Ox5PWc87wNUjmC6x5UfAU", "story", "GridInfo", "GRID_INFO", "grid_info_data_type", "Data type of the value (e.g., string, integer),", ""),
("vXaO-Z-FiuTMNWzA4uaP1D7yv9N2jNzW8_YJ0YaqIM0", "story", "GridInfo", "GRID_INFO", "grid_info_name", "Label for value, providing context or description", ""),
("WGU0rU7wnGoWbkFZ93S9xqtidZeNNKZ9QQhAzZ_YPHI", "story", "GridInfo", "GRID_INFO", "grid_info_value", "Actual value, which might be binary data", ""),
("x4xyldOK_VZH7iYUaHHcurX_5xO47GOPOjIswl_VAyE", "story", "GridInfo", "GRID_INFO", "grid_info_path", "Path for storing data outside the database", ""),
("BXJCf9th-RIOuB9HGQ5d2Lf1sQ1Rn2sehSYtprJitZc", "story", "GridInfo", "GRID_INFO", "delete_dt", "Deletion date, when the record was marked for deletion", ""),
("Odfcmvw09gidvQCrU1sLoiGwCycvsF1-ZWqyk7X4dxw", "story", "MapXMap", "MAP_X_MAP", "map_x_map_uid_pk", "Primary key, unique ID for each map-to-map association", ""),
("Fza7dZe0DmSCmtqpOJk7fCjCdBJ9MpmS1p78Ww7VO04", "story", "MapXMap", "MAP_X_MAP", "map_uid_1_vfk", "Virtual foreign key representing the first map in the association", ""),
("obotn4PJu3BFrU_L1wIyVzOONRYRG-0Qg3BCkvDEVqM", "story", "MapXMap", "MAP_X_MAP", "map_uid_2_vfk", "Virtual foreign key representing the second map in the association", ""),
("_oJOLHUxiLkHnwApkGvmpfJQshatCL6K0owYA1B3R74", "story", "MapXMap", "MAP_X_MAP", "touch_type", "Describes the relationship type between the two maps (e.g.,", ""),
("2WkRb4-Zm08ILb7xJDABbWjdklF6ientzV7pgIRyjI4", "story", "MapXMap", "MAP_X_MAP", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("PguyGlQHiV_Ji_i5Th4dNOqLzksgv1Zr0Li3KJyvrQY", "story", "GridXMap", "GRID_X_MAP", "grid_x_map_uid_pk", "Primary key, unique identifier for", ""),
("qC4UF3aTbWoCcMHl7-Pl_KccI8bBr2hnWwOe7iorRcE", "story", "GridXMap", "GRID_X_MAP", "grid_uid_fk", "Foreign key representing the associated grid, indexed for performance", ""),
("nhWdGkmUQFlShPoaKbE0rybMla-Kgug4skcajzea2xs", "story", "GridXMap", "GRID_X_MAP", "map_uid_vfk", "Virtual foreign key representing the associated map,", ""),
("J9lneW9OFOM0nuCIP8u1R-3rT8wUhcePWdoiQy8W6aU", "story", "GridXMap", "GRID_X_MAP", "delete_dt", "Deletion date, indicating when the record was", ""),
("MD7Ilthic4Q9XH2U1RL6tchyCQWdr1kBVZGZjJ_Q3Pw", "story", "CharSet", "CHAR_SET", "char_set_uid_pk", "Primary key, unique ID for each character set", ""),
("v4VN4bZNRxWDAzsJdutUSSZGlvupzKYFyfNsvxmOB4M", "story", "CharSet", "CHAR_SET", "font_name", "Name of the font associated with the character set,", ""),
("AART9_-gtm-YfEO5HaIY0wEyhqz351YGpPAvV1OPdAY", "story", "CharSet", "CHAR_SET", "char_set_type", "Type of the character set, default is alphabet,", ""),
("JI-KUXEiGUha6gYKHX3LH85tUT0Yq1M4C83OwTiyVGs", "story", "CharSet", "CHAR_SET", "char_set_desc", "Description of the character set, providing", ""),
("8ICHLMSST0AhDovh-Z8qOE5feoXafGF2wC_FqLXPUm4", "story", "CharSet", "CHAR_SET", "delete_dt", "Deletion date, indicating when the record was", ""),
("3tuWyPO8ozCPn8ddn6CoSrf4TdwHJn7gGU8-5DFHbD4", "story", "CharMember", "CHAR_MEMBER", "char_member_uid_pk", "Primary key, unique identifier for each character member", ""),
("LXtdGbTS9Uu1r9I60e0F9j-dmDNkGzHHQUBFPqJS0O4", "story", "CharMember", "CHAR_MEMBER", "char_set_uid_fk", "Foreign key referencing the character set this member belongs to", ""),
("iOrnYJoJo4DGhX2E96J_reuYlqnqjX-yz6PkOHPRVUI", "story", "CharMember", "CHAR_MEMBER", "char_member_name", "Name of the character member", ""),
("SBDTM-haM0O0GDVphpwWxHIs5cLCDihwHvZVJNVDKiA", "story", "CharMember", "CHAR_MEMBER", "char_member_image", "Binary data representing the image of", ""),
("EV5LN4KaNWwvcKkpxRmTrSZCCNiw_uSb4y-cDsUrbrc", "story", "CharMember", "CHAR_MEMBER", "char_member_path", "File path to the image or representation of the character", ""),
("FLo2R2bd3ZtYd4uF3ppjotfKKl-guN0NEX76cNsxqsQ", "story", "CharMember", "CHAR_MEMBER", "char_member_desc", "Description providing additional details about the character member", ""),
("J0kr67bSCmB1Py2XqMG26A9uXeohb-T_P3t20GvQDwo", "story", "CharMember", "CHAR_MEMBER", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("BjkTq_piLFgr9axj-eeBkmMnVkxjVhlypTGwI_RHHco", "story", "LangFamily", "LANG_FAMILY", "lang_family_uid_pk", "Primary key, unique identifier for each language family", ""),
("5oF_fnw8AdF4kO67qJCGJricwtc_T-tmAtXpMGN5hIk", "story", "LangFamily", "LANG_FAMILY", "char_set_uid_fk", "Foreign key referencing the character set used by the language family", ""),
("7rHBc5kFsvxWvZykVWTJcP8Bq0G-_wEsvUvsu-HV10I", "story", "LangFamily", "LANG_FAMILY", "lang_family_name", "Name of the language family", ""),
("suGI6qRPSj6OqR78-BJ6b9xIjYi7wj0ZoVYE16XyFXI", "story", "LangFamily", "LANG_FAMILY", "lang_family_desc", "Description of the language family", ""),
("im1Jpjip-VAg0CtKehjaMa14Xb-yZInhhHqJ1gEkIiA", "story", "LangFamily", "LANG_FAMILY", "phonetics", "Description of the phonetics of the language family", ""),
("nvnMEcHOPKXRvt-Z0ZNa1AKgMbuilownw_nM3eDZTGo", "story", "LangFamily", "LANG_FAMILY", "cultural_influences", "Description of the cultural influences on the language family", ""),
("VNv1s43c_KIm57vubvIYksb0UyT_67rXbbYf10crxZo", "story", "LangFamily", "LANG_FAMILY", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("jbKG535y78TXAfmkUeNn4xRBxxAbNmEAdBEVnpvXTAw", "story", "Language", "LANGUAGE", "lang_uid_pk", "Primary key, unique identifier for each language", ""),
("NGksxz8yYQjC2r9tKpH1zqf_SOMnJBrcTlvSPBoGiOE", "story", "Language", "LANGUAGE", "lang_family_uid_fk", "Foreign key referencing the language family this language belongs to", ""),
("foq_bhGGobOb9KmMea4gj7aN3fgIPr-JsIDOKxbkl38", "story", "Language", "LANGUAGE", "lang_name", "Name of the language", ""),
("nLTgLhdM8JCyWxy7-e_Ta3Q551hTjm7Mt2ww2dLq9u0", "story", "Language", "LANGUAGE", "lang_desc", "Description of the language", ""),
("f4mvMuFb-Oez5FBSUEqRuTZdKsrzXiSGHmqjlT8Dce4", "story", "Language", "LANGUAGE", "gramatics", "Description of the gramatics of the language", ""),
("OMZXmsilU7-GV1vezR9FHOVgMbMhYai-wctZ0B4aC3A", "story", "Language", "LANGUAGE", "lexicals", "Description of the lexicals of the language", ""),
("v_w5ddCp9TLx0HXUNntI0KSQmd7uTjRHAD8OSw5t6vQ", "story", "Language", "LANGUAGE", "social_influences", "Description of the social influences on the language", ""),
("X6QLJEzYODohSeOvcaIi2w1VYaUpfVhACHSdvazM6ck", "story", "Language", "LANGUAGE", "word_formations", "Description of the word formations of the language", ""),
("42MWCrOdZlR4rIK3dBshLKE28hmbyLV941wEiaF9veU", "story", "Language", "LANGUAGE", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("okdNN6OHYMAEuicN2vtuYCQMtM-7bTwre7rS1HLZFvY", "story", "LangDialect", "LANG_DIALECT", "dialect_uid_pk", "Primary key, unique identifier for each dialect", ""),
("rxQXTDmEV8QmZC1OheRe1SE6Mw3GrfHNSPZOSF74Xe0", "story", "LangDialect", "LANG_DIALECT", "lang_uid_fk", "Foreign key referencing the language this dialect belongs to", ""),
("3fdnXqxzYeS5ZyfCvKHsMXts7UIHZ2NdCLdwLr8K6EY", "story", "LangDialect", "LANG_DIALECT", "dialect_name", "Name of the dialect", ""),
("Jgfk58DAdD70aVTHBfy8WK0rBaE8XYAtm1woGGOFwOw", "story", "LangDialect", "LANG_DIALECT", "dialect_desc", "Description of the dialect", ""),
("FWjemqxlZPmIrs16vbMZhp425sWiTDbUmj3Dwybn3KU", "story", "LangDialect", "LANG_DIALECT", "divergence_factors", "Description of the divergence factors of the dialect", ""),
("nXY7osfv9PTUbiqSRKZsIhlD4G6ahTt_GGJj1Dt2IlE", "story", "LangDialect", "LANG_DIALECT", "syncretic_factors", "Description of the syncretic factors of the dialect", ""),
("OrptsmsZrgcN-UWenBM8QbttSeS5AQduIeB22ZHYH1E", "story", "LangDialect", "LANG_DIALECT", "preservation_factors", "Description of the preservation factors of the dialect", ""),
("xaeNEea9yKS9pzQ__uQLKIRoQ75Fs-MsHlwcKKkRZPE", "story", "LangDialect", "LANG_DIALECT", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("k59TdCes3QFoE2Av1a5CWu8TtYJKTc4Npoa3euhM5bs", "story", "GlossCommon", "GLOSS_COMMON", "gloss_common_uid_pk", "Primary key, unique identifier for each common glossary item", ""),
("6DZpz6XxEjtwcsRkayVpQjZDgOd7p3L4YDzt_CsWstg", "story", "GlossCommon", "GLOSS_COMMON", "dialect_uid_fk", "Foreign key referencing the dialect this glossary item belongs to", ""),
("C9aROB88roeIRnWsm6AECOc01IUkSiGwq_unug-lzWo", "story", "GlossCommon", "GLOSS_COMMON", "gloss_type", "Type of the glossary item", ""),
("oIJejQGd3V-30NZlDxxlqwbTlmHyqkqp3Z3hPxx7oAI", "story", "GlossCommon", "GLOSS_COMMON", "gloss_name", "Name of the glossary item", ""),
("TClJjequLUXfXZSsLVguS7bgeIBMBqThDdGyy1RaIHE", "story", "GlossCommon", "GLOSS_COMMON", "gloss_value", "Value of the glossary item", ""),
("OrrCm1ycYSlNU00Ut70XCXuqk_WaH4YsGlJ4TYpiIhg", "story", "GlossCommon", "GLOSS_COMMON", "gloss_uri", "URI of the glossary item", ""),
("1PiRG3z-VOmxx5YyLBmCp-59l1IIb4ON9LpiBApy2Cs", "story", "GlossCommon", "GLOSS_COMMON", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("NUrwk4a-YyXtDBCemU-XZlk2yJSgcTBlkC2ZeGU6EkY", "story", "Glossary", "GLOSSARY", "glossary_uid_pk", "Primary key, unique identifier for each glossary item", ""),
("3ccL_IlILzgfC0rcNL3WC7H7w7odD-6-u0eUn1ms_O8", "story", "Glossary", "GLOSSARY", "gloss_common_uid_fk", "Foreign key referencing the common glossary item", ""),
("CMCKxq8G02xPaiYEF7Pqwfxb8pO5gsQ_p89YAfD282w", "story", "Glossary", "GLOSSARY", "dialect_uid_fk", "Foreign key referencing the dialect this glossary item belongs to", ""),
("3e104Bb9nq5doXuN_2t1N-E4UTdc4Fp7U90E4kgBoFw", "story", "Glossary", "GLOSSARY", "gloss_type", "Type of the glossary item", ""),
("YOtFmi8JQDVaNG7rBexeyDq7Eu1LGRqTn6_KLLWY-0s", "story", "Glossary", "GLOSSARY", "gloss_name", "Name of the glossary item", ""),
("MhYB8DODb0I-RESe8oU8gIfRaj3IoD8d-4GrdPZun2s", "story", "Glossary", "GLOSSARY", "gloss_value", "Value of the glossary item", ""),
("NEv2cMliNv6nOfCIurzPPUmG4fI3hzyMXZocjJ6ydGo", "story", "Glossary", "GLOSSARY", "gloss_uri", "URI of the glossary item", ""),
("043YyrTpSrAw53qh4L1r6-bL58r6pbdKo4CiJNF-2cM", "story", "Glossary", "GLOSSARY", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("elCLQralmJEB81x8m7CtfzZAuhk2eMT_Gh7cGZ-KB5M", "story", "Universe", "UNIVERSE", "univ_uid_pk", "Primary key, unique identifier for each universe", ""),
("_tY9yoPK2Tqx1HkxIo9XSlJAEFgC3CKMLgQTNEQ_Itg", "story", "Universe", "UNIVERSE", "univ_name", "Name of the universe", ""),
("zYR1oHhMmsaMd7IMpfF5_XtTm3vB7bvSkke7383PBnQ", "story", "Universe", "UNIVERSE", "radius_gly", "Radius of the universe in gigalightyears", ""),
("3szpL2M8cSdL2zmV2nqrQClCaABA-i49RuJHNnyHXWY", "story", "Universe", "UNIVERSE", "volume_gly3", "Volume of the universe in gigalightyears cubed", ""),
("YZax5wNAoFlY8353ElpNg3lZH81otmSS0CQ7GFsIJ0M", "story", "Universe", "UNIVERSE", "volume_pc3", "Volume of the universe in parsecs cubed", ""),
("hEcWZTEgPxgzk8EhJblniJ_J7pgOmsK0NeeDdJCkxjg", "story", "Universe", "UNIVERSE", "age_gyr", "Age of the universe in gigayears", ""),
("1BAZiGpN_tVuKKiT2iAkKXjKO8_aiKEnPJqPYCzstWc", "story", "Universe", "UNIVERSE", "expansion_rate_kmpsec_per_mpc", "Expansion rate of the universe in km/sec per megaparsec", ""),
("7eI9O15ztMEZ_WGRxmYnJjAUMM7RSdj0a7PaVogCr98", "story", "Universe", "UNIVERSE", "total_mass_kg", "Total mass of the universe in kilograms", ""),
("9VWoM87BuGCjq_tQzWGqkZYRESaL8VLqkMqMRQD7fzY", "story", "Universe", "UNIVERSE", "dark_energy_kg", "Amount of dark energy in the universe in kilograms", ""),
("-xbuLTyjEAiWTiHUpCcQh1t12SdLDXU-LKYpGJrOoHY", "story", "Universe", "UNIVERSE", "dark_matter_kg", "Amount of dark matter in the universe in kilograms", ""),
("CHLBFOpjkUM12CQKfz_pS7SfWfKiy44ltcOlXQhT1lE", "story", "Universe", "UNIVERSE", "baryonic_matter_kg", "Amount of baryonic matter in the universe in kilograms", ""),
("IE0hmj7J_sRdwDhApp_iRfnGZuBUWvtlXuumDIwyMiI", "story", "Universe", "UNIVERSE", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("fVdjNp0JnRS8xE8mhN2ipyGIFvRSQcgn1tIuB2CqTmM", "story", "ExternalUniv", "EXTERNAL_UNIVERSE", "external_univ_uid_pk", "Primary key, unique identifier for each external universe", ""),
("LruU_ticdWVrqd9_3o7S2JrYX8ciD85q-3SNQmdFfAU", "story", "ExternalUniv", "EXTERNAL_UNIVERSE", "univ_uid_fk", "Foreign key linking to the Universe table", ""),
("Kw_Y3K-bsdRDsFu4vHucdcZAscpdpDip0NEWNPqF2pk", "story", "ExternalUniv", "EXTERNAL_UNIVERSE", "external_univ_name", "Name of the external universe", ""),
("Se3-3Mo7DN-KVecpTnW9p0zSoJrgZYtCJzxSS4nbvVA", "story", "ExternalUniv", "EXTERNAL_UNIVERSE", "mass_kg", "Mass of the external universe in kilograms", ""),
("rseJUxwGZavPUC0ptLyKol3ns6jPogQvaMsqJc7YqS0", "story", "ExternalUniv", "EXTERNAL_UNIVERSE", "dark_energy_kg", "Amount of dark energy in the external universe in kilograms", ""),
("GVewLqINIzij1QNxr-aDap0z-2fYvxKxaDOnkzIB1LQ", "story", "ExternalUniv", "EXTERNAL_UNIVERSE", "dark_matter_kg", "Amount of dark matter in the external universe in kilograms", ""),
("_s24GBxGXJSYPfEtdyCE_8EG0rXZPN1XdGoqRa86-FM", "story", "ExternalUniv", "EXTERNAL_UNIVERSE", "baryonic_matter_kg", "Amount of baryonic matter in the external universe in kilograms", ""),
("I_sNNs3kTzjsGIp3CjwEaMBCnr92BdHKw0aA78xW_II", "story", "ExternalUniv", "EXTERNAL_UNIVERSE", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("Klu9jBIiPmmJIuN9p-jsnC9SvysKB7SFnoo7Nys-lyc", "story", "GalacticCluster", "GALACTIC_CLUSTER", "galactic_cluster_uid_pk", "Primary key, unique identifier for each galactic cluster", ""),
("V_oxMnlrfmZWZjhQ3YAD40IQ5K9PcZ26jyQkK4GuuzI", "story", "GalacticCluster", "GALACTIC_CLUSTER", "univ_uid_fk", "Foreign key linking to the Universe table", ""),
("HXguSM6lffZgIimXuMWLhRdOQZ_p4OGmiNmRBF2xU3M", "story", "GalacticCluster", "GALACTIC_CLUSTER", "galactic_cluster_name", "Name of the galactic cluster", ""),
("Tf-uki3RVXRifSeQ5LkxtpV5cqPkua1aoMnWaLxSZO8", "story", "GalacticCluster", "GALACTIC_CLUSTER", "center_from_univ_center_gly_x", "X coordinate of the center of the cluster in gigalightyears", ""),
("isHuJmTEn1B_DgjgPYcEdgPJiJCYZK8q5rb3XN7oiFw", "story", "GalacticCluster", "GALACTIC_CLUSTER", "center_from_univ_center_gly_y", "Y coordinate of the center of the cluster in gigalightyears", ""),
("0bXGgN3Bf83_qTpnmTN4A60IMvt0GRjIqG2CsuwyUsc", "story", "GalacticCluster", "GALACTIC_CLUSTER", "center_from_univ_center_gly_z", "Z coordinate of the center of the cluster in gigalightyears", ""),
("vXXq8VhgWuk6Adnwad4QncYCxaGellHZMTJKw7abxGI", "story", "GalacticCluster", "GALACTIC_CLUSTER", "boundary_gly_x", "X coordinate of the boundary of the cluster in gigalightyears", ""),
("3O1-OBfQMc4tB_eG_K7HJKUOKpubS4BCl3I1tIVZyI4", "story", "GalacticCluster", "GALACTIC_CLUSTER", "boundary_gly_y", "Y coordinate of the boundary of the cluster in gigalightyears", ""),
("slr40RUfsZl6NVEU0tztEjgIpNHAkYrOTGAr-UdTn68", "story", "GalacticCluster", "GALACTIC_CLUSTER", "boundary_gly_z", "Z coordinate of the boundary of the cluster in gigalightyears", ""),
("xV3E0X4id5ik0EI_ZJGgSJX8Zs_8G3w4LzuZ66Di2qE", "story", "GalacticCluster", "GALACTIC_CLUSTER", "cluster_shape", "Shape of the cluster, default is ellipsoid", ""),
("RsqRYUc2EJl6kLnSK2dPBpsRq-v0iXJarvWXYwmZIEA", "story", "GalacticCluster", "GALACTIC_CLUSTER", "shape_pc_x", "X coordinate of the shape of the cluster in parsecs", ""),
("KFKGwDoxCKC1EChOjGF9nb9e1CkgGJw9P4xxmc3N6l0", "story", "GalacticCluster", "GALACTIC_CLUSTER", "shape_pc_y", "Y coordinate of the shape of the cluster in parsecs", ""),
("v9W60fGgtpQW2__IasDyjJ2SSznyF5ZYB7qQg7B7SSc", "story", "GalacticCluster", "GALACTIC_CLUSTER", "shape_pc_z", "Z coordinate of the shape of the cluster in parsecs", ""),
("dMPaA_x6W0T2v-nyyxpH3HgStpJsZF_z4B_xDVmCEIE", "story", "GalacticCluster", "GALACTIC_CLUSTER", "shape_axes_a", "Length of the major axis of the cluster in parsecs", ""),
("CdwcPGfM0LHktCrxsXZ6s4WBcmNLG-m4phoea3bmlXY", "story", "GalacticCluster", "GALACTIC_CLUSTER", "shape_axes_b", "Length of the minor axis of the cluster in parsecs", ""),
("iyY1X-u9fuDc38HyORdLzXdG3FiMCzWQ-SnJdJ2PiiY", "story", "GalacticCluster", "GALACTIC_CLUSTER", "shape_axes_c", "Length of the tertiary axis of the cluster in parsecs", ""),
("LMOkzeRKuRTq7cMK2G7bIvb4r0BTwD6t0ZJB0OBAzN8", "story", "GalacticCluster", "GALACTIC_CLUSTER", "shape_rot_pitch", "Pitch rotation of the cluster in degrees", ""),
("9OASd7e1jRXZSxL2fE60in3o_03GmrtJFwLNX5rCW4E", "story", "GalacticCluster", "GALACTIC_CLUSTER", "shape_rot_yaw", "Yaw rotation of the cluster in degrees", ""),
("Xpw3GJizF_rlsiM8ZmaWrZ8QeD9r_gcwbEjVyX2L3R4", "story", "GalacticCluster", "GALACTIC_CLUSTER", "shape_rot_roll", "Roll rotation of the cluster in degrees", ""),
("aD8EkHDYAWB8eR6Hj1qJYBs1TD5WGraln7D78llwc7s", "story", "GalacticCluster", "GALACTIC_CLUSTER", "volume_pc3", "Volume of the cluster in parsecs cubed", ""),
("t_QlN8Z0GUnnTYWSHgo0hpWVRKRAaS3V5x5LgpiA6RM", "story", "GalacticCluster", "GALACTIC_CLUSTER", "mass_kg", "Mass of the cluster in kilograms", ""),
("X229E58TMnDeRsJQTErXGtZ9yYZDt7na_QfInkeRx88", "story", "GalacticCluster", "GALACTIC_CLUSTER", "dark_energy_kg", "Amount of dark energy in the cluster in kilograms", ""),
("QrkoqCvTmI7D8-7uSvoe9DqaETyW5fQMFeT0MoGw8Zk", "story", "GalacticCluster", "GALACTIC_CLUSTER", "dark_matter_kg", "Amount of dark matter in the cluster in kilograms", ""),
("wKfBMRN5pWI3FaqLZKP7P3j-B41HnZQQ4G1arukGl1A", "story", "GalacticCluster", "GALACTIC_CLUSTER", "baryonic_matter_kg", "Amount of baryonic matter in the cluster in kilograms", ""),
("VREE_-vq9lUnsbwYj10fdjGcsZY4lfKqKkOek498ZPA", "story", "GalacticCluster", "GALACTIC_CLUSTER", "timing_pulsar_pulse_per_ms", "Timing of the pulsar pulse in milliseconds", ""),
("7ADjfIFMoCnNaiaCutV5u00Joy-tIeR3u7xKvhz6E9w", "story", "GalacticCluster", "GALACTIC_CLUSTER", "timing_pulsar_loc_gly_x", "X coordinate of the pulsar location in gigalightyears", ""),
("O6ClRklz2Okkx_bkwt9rbWtQewwHxlUOwwuf_6SYU1s", "story", "GalacticCluster", "GALACTIC_CLUSTER", "timing_pulsar_loc_gly_y", "Y coordinate of the pulsar location in gigalightyears", ""),
("_RuMttL25qsugta4YutD7ix1gYfxPiW9ufBFOhp1qYg", "story", "GalacticCluster", "GALACTIC_CLUSTER", "timing_pulsar_loc_gly_z", "Z coordinate of the pulsar location in gigalightyears", ""),
("Jnrh_hGZBDfwPffo11Lr6xx_MvRHE1V5Tn6vr44P5yE", "story", "GalacticCluster", "GALACTIC_CLUSTER", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("0sNm6Tr-MLY1X2JgrJyCX601WFh6IO14bbPwFh07c_M", "story", "Galaxy", "GALAXY", "galaxy_uid_pk", "Primary key, unique identifier for each galaxy", ""),
("rsFk_UU7eW-KnYgIl1GRLicN5PjcYXok4VM-qrhLIHY", "story", "Galaxy", "GALAXY", "galactic_cluster_uid_fk", "Foreign key linking to the Galactic Cluster table", ""),
("7qxy6sWNmFpTQ4DB-mRy2VADX49YL2fLorZPsES9CU8", "story", "Galaxy", "GALAXY", "galaxy_name", "Name of the galaxy", ""),
("KWJcc90coQreY1b27wCPXfV1Te_FCCa0yDeSo9uVA4M", "story", "Galaxy", "GALAXY", "relative_size", "Relative size of the galaxy, default is medium", ""),
("gF53Gs7W_T_qFK4yHS6MnVqBmcvl4WSH4Yw0p5YvgU0", "story", "Galaxy", "GALAXY", "center_from_univ_center_kpc_x", "X coordinate of the center of the galaxy in kiloparsecs", ""),
("czOjc46oS7gASUw8fTnDiMtIWz0eNnmxIJmRSlogQzs", "story", "Galaxy", "GALAXY", "center_from_univ_center_kpc_y", "Y coordinate of the center of the galaxy in kiloparsecs", ""),
("xpH8bHHc-H9pm-ttkvX3nYnjhd0QQqvgEXyiaiq391I", "story", "Galaxy", "GALAXY", "center_from_univ_center_kpc_z", "Z coordinate of the center of the galaxy in kiloparsecs", ""),
("R00PFdcABJPerrpE5jr7_i2waLqOBMoIddqZTvv0PsQ", "story", "Galaxy", "GALAXY", "halo_radius_pc", "Radius of the halo of the galaxy in parsecs", ""),
("wc2m1q0ocFfCGGXt7EN-wN4bkHqQI0spTfG98R1X9Bc", "story", "Galaxy", "GALAXY", "boundary_pc_x", "X coordinate of the boundary of the galaxy in parsecs", ""),
("X_J3RFv7rrfjJsmmpNqCDlH2tC9ydRcR-R7KZPeNb-I", "story", "Galaxy", "GALAXY", "boundary_pc_y", "Y coordinate of the boundary of the galaxy in parsecs", ""),
("z8tvXIChT7wko1DyMUYsDUCqD65x-oGs96svDoYELZA", "story", "Galaxy", "GALAXY", "boundary_pc_z", "Z coordinate of the boundary of the galaxy in parsecs", ""),
("Yy3stSXnBr-pC1frdCR2ynJAdxjSYlkIahbn4CoYgi0", "story", "Galaxy", "GALAXY", "volume_gpc3", "Volume of the galaxy in gigaparsecs cubed", ""),
("ovl5jEoL_rVe0rO2LT6VuP2A7QWaITOnzbK8UWd7Flc", "story", "Galaxy", "GALAXY", "mass_kg", "Mass of the galaxy in kilograms", ""),
("3mWjNpylkx9Q7aehRu8jfcuS6HUxJpGrvFTf9WPvWOc", "story", "Galaxy", "GALAXY", "bulge_shape", "Shape of the bulge of the galaxy, default is ellipsoid", ""),
("zGORHXhVjAz9lkManDNJ8WvdGa_lHc1eQMF5IyVSosw", "story", "Galaxy", "GALAXY", "bulge_center_from_center_ly_x", "X coordinate of the center of the bulge", ""),
("jzFfZqd2CULtjkRxUHk7nQ5-Gh7ZgKQcvKBGg2p0SP8", "story", "Galaxy", "GALAXY", "bulge_center_from_center_ly_y", "Y coordinate of the center of the bulge", ""),
("qmFUQnB-r8Czb5cdKxSigRFx5EVULFZz3FwvVDdItM4", "story", "Galaxy", "GALAXY", "bulge_center_from_center_ly_z", "Z coordinate of the center of the bulge", ""),
("4fQkOnLvFaGEAn7AVuhLCyfBDHyQhySCY6BlJXvN8sM", "story", "Galaxy", "GALAXY", "bulge_dim_axes_a", "Length of the major axis of the bulge in lightyears", ""),
("-PcI5RLfkNtsn8pRYGpsgJXIBYfkNScNTaAHQKjVVYs", "story", "Galaxy", "GALAXY", "bulge_dim_axes_b", "Length of the minor axis of the bulge in lightyears", ""),
("Q-hRdFjuBtFTUhccEdO1jWDa4v88uRBUDRIEqEf5gHA", "story", "Galaxy", "GALAXY", "bulge_dim_axes_c", "Length of the tertiary axis of the bulge in lightyears", ""),
("nrrgGvWTMIiS7xFQ3vlMSw_qxYU8ea8rYaB2eSLxKM0", "story", "Galaxy", "GALAXY", "bulge_dim_rot_pitch", "Pitch rotation of the bulge in degrees", ""),
("MIl-GGrdW4R-OlhKFxsKeerADD3Q5WJIggDC7-23jIY", "story", "Galaxy", "GALAXY", "bulge_dim_rot_yaw", "Yaw rotation of the bulge in degrees", ""),
("4pH84n81_U4PKeOfgN8Iprn3SooWfRSKcKrwMLlOh_Y", "story", "Galaxy", "GALAXY", "bulge_dim_rot_roll", "Roll rotation of the bulge in degrees", ""),
("AxMx4EhIMqf_sRWtn2tY6T1rnkzOJ1vWsoyteQpAVOU", "story", "Galaxy", "GALAXY", "bulge_black_hole_mass_kg", "Mass of the black hole in the bulge in kilograms", ""),
("bMvLQkLMVwCCIKmkNn298jAlRioXed-rdEjt658ojLY", "story", "Galaxy", "GALAXY", "bulge_volume_ly3", "Volume of the bulge in lightyears cubed", ""),
("FVeEU-K6kWuen3fKpCti217VkF1OMoQ6V_g7jH3LeKM", "story", "Galaxy", "GALAXY", "bulge_total_mass_kg", "Total mass of the bulge in kilograms", ""),
("BC9daqdZdOpSeEQmAoXD-7B5NczfHeSH8gkBHrJRZBw", "story", "Galaxy", "GALAXY", "star_field_shape", "Shape of the star field of the galaxy, default is ellipsoid", ""),
("t05jdQ1NmYEhN9NghY1IjEZ3mL7ol_tTiPNmM1uplto", "story", "Galaxy", "GALAXY", "star_field_dim_from_center_ly_x", "X coordinate of the center of the star field", ""),
("viuD4rzJkQ0lpqfFFf9EWf4BckP8MPgySO7K0HVYeCg", "story", "Galaxy", "GALAXY", "star_field_dim_from_center_ly_y", "Y coordinate of the center of the star field", ""),
("6WiEptepVQ_Ivg8kXbWrWk-0mQoLMAIx4SIjk67E_Yo", "story", "Galaxy", "GALAXY", "star_field_dim_from_center_ly_z", "Z coordinate of the center of the star field", ""),
("_1-MEtVb-3goOuewRNKfLVy4rILvO7O9J9ut-hDHIis", "story", "Galaxy", "GALAXY", "star_field_dim_axes_a", "Length of the major axis of the star field in lightyears", ""),
("cyyfOKfRUXVM4FUnSUYx7zp4aANGly2_O4HZy5jRCJo", "story", "Galaxy", "GALAXY", "star_field_dim_axes_b", "Length of the minor axis of the star field in lightyears", ""),
("L7qgndMJAN8H8tZhxSt-PDJso3CjgzXw_0QqOjtB3gA", "story", "Galaxy", "GALAXY", "star_field_dim_axes_c", "Length of the tertiary axis of the star field in lightyears", ""),
("IvasNx1iV5oX727kjaV-CxoDNkoOoL2i5j6ypy02QEQ", "story", "Galaxy", "GALAXY", "star_field_dim_rot_pitch", "Pitch rotation of the star field in degrees", ""),
("s1YwrwCDm0Pw5A651dK5io8DqNo_mskLkmThW3RTFlE", "story", "Galaxy", "GALAXY", "star_field_dim_rot_yaw", "Yaw rotation of the star field in degrees", ""),
("tdSgLgfxnrns6Nk7NgrLnyRPsKH7_TBY_dO-yOb6yXM", "story", "Galaxy", "GALAXY", "star_field_dim_rot_roll", "Roll rotation of the star field in degrees", ""),
("1b4diOzIHqUkNj1wVhNtVaj4U_DHTIo1cIoSInjR2Cs", "story", "Galaxy", "GALAXY", "star_field_vol_ly3", "Volume of the star field in lightyears cubed", ""),
("ynybOG-8bRDjpUiux2DDtV429fhrsCnim8niytKp83Q", "story", "Galaxy", "GALAXY", "star_field_mass_kg", "Mass of the star field in kilograms", ""),
("YGst6Jcj4VdBfOl2KHxKs0W_loYoui-gHZBN42djj54", "story", "Galaxy", "GALAXY", "interstellar_mass_kg", "Mass of", ""),
("WFhhv1UocReCaCgDLeCUX5lC7qoREmdtyKqsWpUQHVQ", "story", "Galaxy", "GALAXY", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("Ec-j-t2Q12LuhIs49Y_PJn3LwmvWY9uQbcU1DizfHzg", "story", "StarSystem", "STAR_SYSTEM", "star_system_uid_pk", "Primary key, unique identifier for each star system", ""),
("cGG5o1oyeZ_2KTKp5NptfETpyqi3cOwdiJQwoqRqJwM", "story", "StarSystem", "STAR_SYSTEM", "galaxy_uid_fk", "Foreign key linking to the Galaxy table", ""),
("vgSc7YyMZakcTgejjnWc4Y9mxyJ8c1KGimlinTv5iSc", "story", "StarSystem", "STAR_SYSTEM", "star_system_name", "Name of the star system", ""),
("i-jjnn0Pgv6JOZuydEVYO6CJ59k59u2nyrSfSP1AfrY", "story", "StarSystem", "STAR_SYSTEM", "is_black_hole", "Indicates if the star system contains a black hole", ""),
("kJ5aonlfOIt-cxR18pyZImItVITuWCzC7SJ2fwUGyZ4", "story", "StarSystem", "STAR_SYSTEM", "is_pulsar", "Indicates if the star system contains a pulsar", ""),
("QI2Kwf90E2Fo8-pZw3jTPo-WXNdXIqTjORv8TTTmKM8", "story", "StarSystem", "STAR_SYSTEM", "boundary_pc_x", "X coordinate of the boundary of the star system in parsecs", ""),
("OUnnP32M4fjZVqB8APk2sKCBJnPP1jqkTRHO6dTWw2o", "story", "StarSystem", "STAR_SYSTEM", "boundary_pc_y", "Y coordinate of the boundary of the star system in parsecs", ""),
("QUhE8jOavntOYN9ufwBsHhygHKqkwHJg0mJT-mEwqdY", "story", "StarSystem", "STAR_SYSTEM", "boundary_pc_z", "Z coordinate of the boundary of the star system in parsecs", ""),
("Omzt7bNiqfd4YhdMczNJTyBC6IFCF3R73n4lLXUKAGE", "story", "StarSystem", "STAR_SYSTEM", "volume_pc3", "Volume of the star system in parsecs cubed", ""),
("4ZFCYdS9cNH1jkziEar4JPDiy1XlIjsJQIGTMDfSmdc", "story", "StarSystem", "STAR_SYSTEM", "mass_kg", "Mass of the star system in kilograms", ""),
("qMMUvRwfQCkqG_jCUBqilfJ4gUROu82nzYqVLJNXqVU", "story", "StarSystem", "STAR_SYSTEM", "system_shape", "Shape of the star system, default is ellipsoid", ""),
("MY8uaiK_LzZkuwBvII50gybz7YNUAUOFjF_e_8Xu2Ps", "story", "StarSystem", "STAR_SYSTEM", "center_from_galaxy_center_pc_x", "X coordinate of the center of the star system", ""),
("ifuLno_SaXuf0RhjNKNw5Zpa6SJdsQmSIklckM6KSAI", "story", "StarSystem", "STAR_SYSTEM", "center_from_galaxy_center_pc_y", "Y coordinate of the center of the star system", ""),
("pbyyVXWwYwWgtcwQZ32Y2jDx-Zx-jDN_Gp7_gXntUXk", "story", "StarSystem", "STAR_SYSTEM", "center_from_galaxy_center_pc_z", "Z coordinate of the center of the star system", ""),
("-2dnxQZzGB1Q1wrrTXVTV0vwThyJ6xIf-zbB2rGSizE", "story", "StarSystem", "STAR_SYSTEM", "system_dim_axes_a", "Length of the major axis of the star system in parsecs", ""),
("xYningMJOdR6YdeRHULwC79IhRFtw_aY7TjyJNuySHo", "story", "StarSystem", "STAR_SYSTEM", "system_dim_axes_b", "Length of the minor axis of the star system in parsecs", ""),
("WmFRt2HACYZF9eR3eR57unRldcOpIsPKrMIoaiMpmbM", "story", "StarSystem", "STAR_SYSTEM", "system_dim_axes_c", "Length of the tertiary axis of the star system in parsecs", ""),
("bAZ75eIftbmmlfDmc7qZaNjGxuPtbC932eolSa5h8xo", "story", "StarSystem", "STAR_SYSTEM", "system_dim_rot_pitch", "Pitch rotation of the star system in degrees", ""),
("J-gkpsIzrxrmCcS6qlpxwRDWQgFBiNa1wULNBXMAOQc", "story", "StarSystem", "STAR_SYSTEM", "system_dim_rot_yaw", "Yaw rotation of the star system in degrees", ""),
("76sxvhsyuPzRxfrN63Od-bJAdh4RmElEozDUeEhDDfM", "story", "StarSystem", "STAR_SYSTEM", "system_dim_rot_roll", "Roll rotation of the star system in degrees", ""),
("cEyAJA21rv5evs-UwbtXw7Et-ckb-S1ocOBLkghuQTA", "story", "StarSystem", "STAR_SYSTEM", "relative_size", "Relative size of the star system, default is medium", ""),
("7NT1AilmoZ3vfh2biLRvhPSFou0MHiN-oUqVYsBUSYM", "story", "StarSystem", "STAR_SYSTEM", "spectral_class", "Spectral class of the star, default is G", ""),
("Ho0MAZ41N6VIX0NTySLiCV-loOKkyJz9-J71WkOROsw", "story", "StarSystem", "STAR_SYSTEM", "aprox_age_gyr", "Approximate age of the star system in gigayears", ""),
("bQjnanWlHe7YjQVcyuw478tsWz--1mlmGW6Rqx-DI6M", "story", "StarSystem", "STAR_SYSTEM", "luminosity_class", "Luminosity class of the star, default is V", ""),
("lzxpIt7NppIQgtrcvtI9J5tBYDsJLBg3kGrG-dbYJQw", "story", "StarSystem", "STAR_SYSTEM", "frequency_of_flares", "Frequency of solar flares, default is rare", ""),
("ZboKLPgNLxyvfsHmbRwkr-LKdt4LZvJhkcFx7GHl_90", "story", "StarSystem", "STAR_SYSTEM", "intensity_of_flares", "Intensity of solar flares, default is low", ""),
("4ghGnE_RNacbjktWnEh_H1oPowngnEhNZKlevqf8qwg", "story", "StarSystem", "STAR_SYSTEM", "frequency_of_comets", "Frequency of comets, default is rare", ""),
("sKfrk0eDOP3S2KIQ6yiezIpYOQqCVw27FjYoikIYY6Q", "story", "StarSystem", "STAR_SYSTEM", "unbound_planets_cnt", "Number of unbound planets in the star system", ""),
("HSf9hAjAWr-BX4jpYVfdf5n1OrfPH_S5hbixjskTjcI", "story", "StarSystem", "STAR_SYSTEM", "orbiting_planets_cnt", "Number of planets orbiting the star", ""),
("fW-bW96C3mdZ4WpFtWEhHCDAHba6Z_GshtThXrYpUzM", "story", "StarSystem", "STAR_SYSTEM", "inner_habitable_boundary_au", "Inner boundary of the habitable zone in astronomical units", ""),
("SYoLbc1NyH4T79opOXMcd4Dy58-ziKYlpHKe4oh0CSw", "story", "StarSystem", "STAR_SYSTEM", "outer_habitable_boundary_au", "Outer boundary of the habitable zone in astronomical units", ""),
("3Ax0N-G8qIaLZdghEIiEP-H9d67tYnTS9br72Lum4D8", "story", "StarSystem", "STAR_SYSTEM", "planetary_orbits_shape", "Shape of the planetary orbits, default is circular", ""),
("k66tyX8Cpfnqw4H6jSPvrxXq3jsvOu0FJrrkOGXJ8bg", "story", "StarSystem", "STAR_SYSTEM", "orbital_stability", "Stability of the planetary orbits, default is stable", ""),
("Pmpi6VEx_uBdP4F2iDycuyFoO6fkdm6YovH3A19P0Hw", "story", "StarSystem", "STAR_SYSTEM", "asteroid_belt_density", "Density of the asteroid belt, default is sparse", ""),
("wE3rUf1YpN6o2ZFmmpIySLASI9VQj-W1PkrQ-grw8C8", "story", "StarSystem", "STAR_SYSTEM", "asteroid_belt_loc", "Location of the asteroid belt, default is inner", ""),
("NT5vJR7fmPU13jLh_xfrfclaez083Dl-wEyOAr88HO8", "story", "StarSystem", "STAR_SYSTEM", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("FF_dFECvUzg-2ypJcpasxeRMjqK13POuaAy7Ph1uwig", "story", "World", "WORLD", "world_uid_pk", "Primary key, unique identifier for each world", ""),
("-QB_YFV02MrSDmgTbFwRtr418qJouC-dZlyEudMvBY0", "story", "World", "WORLD", "star_system_uid_fk", "Foreign key referencing the Star System table", ""),
("LCthJizxkZBVZoC-XOY6UJkSUWmlT6WyAZZ5FHpCpHE", "story", "World", "WORLD", "world_name", "Name of the world", ""),
("4TWw3-P0sgApT-X_3LYvXwXquULpOG3cNWmZEyUBm60", "story", "World", "WORLD", "world_type", "Type of the world, default is habitable", ""),
("8s4bTtzZdmP6L_05IOLEPFq581mm1DanqCkPmdnF98s", "story", "World", "WORLD", "obliquity_dg", "Axial tilt of the world in degrees", ""),
("a3u_-6RYm7A0j4SfnmKMgwGi7wgrfyxlEnfGsJT-Yh0", "story", "World", "WORLD", "distance_from_star_au", "Distance from the star in astronomical units", ""),
("qhOaq9-8NJuwLu3o5ZJFMiJ5xOsr-Y42cB_u5rT9G5k", "story", "World", "WORLD", "distance_from_star_km", "Distance from the star in kilometers", ""),
("crpO0dkp-SnLuw4X_grukBmCQPYkcN2xzNcPuoQ9hA4", "story", "World", "WORLD", "radius_km", "Radius of the world in kilometers", ""),
("FBJMoJiZKoMC91OEEJxc_TOr2HeHvTvNIivZHFxE_9A", "story", "World", "WORLD", "mass_kg", "Mass of the world in kilograms", ""),
("2VJWkQM7R6UGTEkCw4ld8sQuDhZ8nsnfFkgJynF7eos", "story", "World", "WORLD", "gravity_m_per_s_per_s", "Gravity of the world in meters per second squared", ""),
("aYQ9RwIFZWGYczJZS3A6QZL7Mb9Or8WvDxTuDc459Pg", "story", "World", "WORLD", "orbit_gdy", "Orbital period of the world in galactic days", ""),
("RnrmMzdmBRM2kmjests-1SZses1TFPR5Ef9pid5PeLc", "story", "World", "WORLD", "orbit_gyr", "Orbital period of the world in galactic years", ""),
("3lHQAJxbZDSM1vldmnI5nxk-AJwZxR1Qgkhmy2o1xdA", "story", "World", "WORLD", "is_tidally_locked", "Indicates if the world is tidally locked", ""),
("iOTIpZ6ixd2gCdzAcgI_qDtchZ0Sjwp1ulhE7wafnXM", "story", "World", "WORLD", "rotation_gdy", "Rotation period of the world in galactic days", ""),
("06HMWQUfqaHHfkYSVbfFPpWfqZsLisFHVHmY_43pUk8", "story", "World", "WORLD", "rotation_direction", "Direction of rotation, default is prograde", ""),
("J_p7rSmcQDlWykJ8xbSqBwXAc4Dhx7XVIbbppE_Bx3Y", "story", "World", "WORLD", "orbit_direction", "Direction of orbit, default is prograde", ""),
("FBBgVviAtBVRzBZRSGjDmxwwb5mFeW52H2xKP8fsWBk", "story", "World", "WORLD", "moons_cnt", "Number of moons orbiting the world", ""),
("CGAXEDolSN8Xg0G1acOjMTp4w_s83X9PzmhFcwdF03I", "story", "World", "WORLD", "world_desc", "Description of the world", ""),
("G1qQc9tzXEShK30kS6Oqhj1iQlPdTo5r90I9xyeLdck", "story", "World", "WORLD", "atmosphere", "Composition of the atmosphere", ""),
("_JcVRKgtOpfD9h-C0jT-ZamL-XYT2lYuC0kcyBCK1g4", "story", "World", "WORLD", "sky_color", "Color of the sky", ""),
("Vb8L1HbirjZCPkHP0Dm-P71mzGmXv2y1EN-IOs27WKo", "story", "World", "WORLD", "biosphere", "Presence of life forms", ""),
("T7m7h84SKbsNHEdGJbCt2tRz_zvFCroMgBQmt5M4ztw", "story", "World", "WORLD", "sentients", "Presence of intelligent life", ""),
("Qn4aP6loUgprDmDhIR0P2DJwqlPiQYL426Ye6Or-Mp0", "story", "World", "WORLD", "climate", "Climate of the world", ""),
("gvmV7r4LyhthwoBgrN9n0Mlin2LUX2oz9-NmgmZBvC8", "story", "World", "WORLD", "tech_level", "Technological level of the world", ""),
("-M26139dwseQy6FxmenBLt8d0wgI9ukgUykJc0mhRps", "story", "World", "WORLD", "terrain", "Terrain of the world", ""),
("jm0jSgDuhc7v7b6-dDWSljpM2hNy2Ts7Hc1y-FcjtsA", "story", "World", "WORLD", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("WKriM43WeNIqorhQVmDAOkX9OOrEP7Dc5aIUPl6ATs4", "story", "Moon", "MOON", "moon_uid_pk", "Primary key, unique identifier for each moon", ""),
("gN_HlBYpr9hKnHb2z2uBZDtdWVFKOvrEDnPkm-mwLXU", "story", "Moon", "MOON", "world_uid_fk", "Foreign key referencing the World table", ""),
("_qPgTfxi_RznQi4QbVE7FWjh_dG8gyOFJWO61zBo3T4", "story", "Moon", "MOON", "moon_name", "Name of the moon in Common language glossary", ""),
("1hXeDCqJ7f4zSqeIgRVsK4R1GkKgAWkVA6hHLHqfsto", "story", "Moon", "MOON", "moon_desc", "Description of the moon", ""),
("ix0KTgCdPIbzUMxjJm-y9MjdnEt0G747RN6eI0OFw1c", "story", "Moon", "MOON", "moon_lore", "Lore of the moon", ""),
("fgeyBzb5IXGHPG9vmo1nPCtcU4bu-M5s5UA4WK6xVyA", "story", "Moon", "MOON", "center_from_world_center_km", "Distance from the center of the world in kilometers", ""),
("1Yea7OZEsbiJEqxbdJsn2RCN7_8zXFk_q1k__93qus8", "story", "Moon", "MOON", "mass_kg", "Mass of the moon in kilograms", ""),
("1xWoeRoM44TZFxilsXbzO4bpfrg3qNsIRc29k3_X168", "story", "Moon", "MOON", "radius_km", "Radius of the moon in kilometers", ""),
("hBoyA3JoEJj7_uKBh-hEIFYpNmscc0G0vhAGDx4rgns", "story", "Moon", "MOON", "obliquity_dg", "Axial tilt of the moon in degrees", ""),
("v7dthTJ84QYDzwVYX3gh5rljydaqBYZOBkj3PTRhrb8", "story", "Moon", "MOON", "is_tidally_locked", "Indicates if the moon is tidally locked", ""),
("nfPhJr6XkDjkzg-UTtdF6nsngYY_9xLV3zWTHbyXwSU", "story", "Moon", "MOON", "rotation_direction", "Direction of rotation, default is prograde", ""),
("snL_eTFXv3wqf32ttQH9PnvwShJe_61i_z9YsFLoetU", "story", "Moon", "MOON", "orbit_direction", "Direction of orbit, default is prograde", ""),
("LKpf_qqX8plcIsr3Uj2BcAIHnrF4c-nFgw93ARs6NxE", "story", "Moon", "MOON", "orbit_world_days", "Orbital period of the moon in world days", ""),
("nFoEyHYOso7M32Lg3PpobqAA-vbUUS6dFrOr5XBL7cg", "story", "Moon", "MOON", "rotation_world_days", "Rotation period of the moon in world days", ""),
("QbxnWCRO8q3HePxizr-3UDE1HHsTAkXEKMdqAQRCm2U", "story", "Moon", "MOON", "initial_velocity", "Initial velocity of the moon in meters per second", ""),
("h8wa_6W9cojspGNXAiTGrmOqmovRNwPnVDJS0TIvdaA", "story", "Moon", "MOON", "angular_velocity", "Angular velocity of the moon in radians per second", ""),
("V30hlain0pNZwgjvjL41Eg0rcEdzFMzzroDWzzc5b2g", "story", "Moon", "MOON", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("10vE9J8sGQzjk4cjuKDfRhZBM9jrR6UUfjE8IwBEjDo", "story", "Lake", "LAKE", "lake_uid_pk", "Primary key, unique identifier for each lake", ""),
("tvK21tPf187seb-LCGlQyA_qgm1ar435qsYpwNfNarw", "story", "Lake", "LAKE", "gloss_common_uid_vfk", "Foreign key linking to the Common Glossary table", ""),
("t4UzxoknVBprFTQHW0gdU-cdF4RnBmPc_HbSfCmpeMg", "story", "Lake", "LAKE", "lake_name", "Name of the lake", ""),
("XxO2wXjpUY_1kuCoWiLIPSSpkABFlP7_M-wRxt2BBgc", "story", "Lake", "LAKE", "lake_shoreline_points_json", "JSON of the lake shoreline points", ""),
("QIkXvdgGgV9KFLTLZ55SZJjbPt1dIZ7totSH3xqpB58", "story", "Lake", "LAKE", "lake_size", "Size of the lake", ""),
("gqYAPwHGd32EQ4t2rT586CFdoBXGpjMpYDQu8-DLaU0", "story", "Lake", "LAKE", "water_type", "Type of water", ""),
("lc9Cva1c6fzxjYAsKq2_9_PA89mhGTPnayfiW12M63o", "story", "Lake", "LAKE", "lake_type", "Type of lake", ""),
("7np8ix90N3KwxgnB8NDAGv75-SBmtPzcZjsmZyPaDGI", "story", "Lake", "LAKE", "is_tidal_influence", "Indicates if the lake has tidal influence", ""),
("sQEC_7qZEigylrcYvhoG8Y_xMBvDGsACqFnO0d4oIGI", "story", "Lake", "LAKE", "lake_surface_m2", "Surface area of the lake", ""),
("GY8AJ9XKN12fga_c6ghyBDagfeGPriXXDRsMN78Lwtw", "story", "Lake", "LAKE", "max_depth_m", "Maximum depth of the lake", ""),
("XSa7NiXiAvbLS_qIygsxl2Pmyg3f54zM71TKqo5EMcI", "story", "Lake", "LAKE", "avg_depth_m", "Average depth of the lake", ""),
("7IuWEGVERQbBgzOrxhqIOrKhj3YkoV9Iyl1uqOXQTI8", "story", "Lake", "LAKE", "lake_altitude_m", "Altitude of the lake", ""),
("Nvz9wyf2G2ZhBOV_g4kzYG05m8gLweo-VW31sRxUHgE", "story", "Lake", "LAKE", "catchment_area_radius_m", "Catchment area radius of the lake", ""),
("0O8maMhp4Ix7jXWL_mkPP87nLjiq4khwCEv6oHvMosA", "story", "Lake", "LAKE", "lake_origin", "Origin of the lake", ""),
("xjb2he8VYuOV44_Kx5GkIYXJGXI2WD33a7HlG3vTHAw", "story", "Lake", "LAKE", "flora_and_fauna", "Flora and fauna of the lake", ""),
("J8kjbU4XNWruC_USa1Pqn3OW92Tcsbg8qzpvQq1nu5k", "story", "Lake", "LAKE", "water_color", "Color of the water", ""),
("Lsf061WzKhs6H1jDEBHvwZjYwNOdRvw0F-vrTGugnV0", "story", "Lake", "LAKE", "accessibility", "Accessibility of the lake", ""),
("_tigWoh3y1sapUJ2ppSE_tAjAZbgxQY15IRerTQlomc", "story", "Lake", "LAKE", "special_features", "Special features of the lake", ""),
("Ynv7cSXzPPRtP33LOyd14dTB6ysWVD_SV-Zt5x094y8", "story", "Lake", "LAKE", "lake_usage", "Usage of the lake", ""),
("ma8uze0J6xfB0o80Ew3rkNUYy9-c6rQ3zOAyNBLdtl4", "story", "Lake", "LAKE", "lake_lore", "Legends or myths of the lake", ""),
("4vdHCO4SlICcFiZqwNPOaqTVBI69tlDX31E6S2xcKQ8", "story", "Lake", "LAKE", "lake_history", "History of the lake", ""),
("VXf47lh1gk9Sklp-MM58VrIXnTO7TyePUxBmrOvVCjM", "story", "Lake", "LAKE", "conservation_status", "Conservation status of the lake", ""),
("tBvoaS6T2AfrrKIDWK7cogy1CMecXf7R9qV4k9aG82Q", "story", "Lake", "LAKE", "current_conditions", "Current conditions of the lake", ""),
("1meaMP5Cj6X2743j2ZbwleFp8uNsjt8_D1Vz1i8ZtZw", "story", "Lake", "LAKE", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("3Q37PCxuNQxpxk_gioPie2xIRl7R1sxPxUj9t6ovrVo", "story", "LakeXMap", "LAKE_X_MAP", "lake_x_map_pk", "Primary key, unique identifier for each association", ""),
("1ULJvmBsNHLYeNdxUvV_uaA6KfiilmhRxupR2ipWBWM", "story", "LakeXMap", "LAKE_X_MAP", "lake_uid_fk", "Foreign key linking to the Lake table", ""),
("W_UeAm-7I7lFkJHydUnMBUPb6Wa8XqkU9R-svXWHZzE", "story", "LakeXMap", "LAKE_X_MAP", "map_uid_fk", "Foreign key linking to the Map table", ""),
("kg8mMtwjZ9Vjde-hnZBq-69OrGCfRf1PpBhbMQg612g", "story", "LakeXMap", "LAKE_X_MAP", "touch_type", "Type of association", ""),
("eX6l7YqmtsGdxFvU3SAyPL2I4ZcHZacO-t-5lMsNS84", "story", "LakeXMap", "LAKE_X_MAP", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("nJAhDjVVWSqpENKwmgheM7FUADg6iuJOVi0S7Wm4FDQ", "story", "River", "RIVER", "river_uid_pk", "Primary key, unique identifier for each river", ""),
("kVpclmD6Hyv871bl5TcMGo8mMpkM27jS4tLltOVRzrY", "story", "River", "RIVER", "gloss_common_uid_vfk", "Foreign key linking to the Common Glossary table", ""),
("2n5De3LJ0ON3-ZEViloOobqStv7whfIDFSd9FzUDbCk", "story", "River", "RIVER", "river_name", "Name of the river", ""),
("e9RRZX7vubYEsoiM-55PGGarIOouvRNjRR9e1xSbW2M", "story", "River", "RIVER", "river_course_points_json", "JSON of the river course points", ""),
("YIVWfpDCcRVgTAo4hqx6E10986NX6_DU2h_gRCjlz5E", "story", "River", "RIVER", "river_bank_points_json", "JSON of the river bank points", ""),
("fnsj0i-O7R1hPEAeluwqtHDSd49Fd09CbqTeUwOsxbE", "story", "River", "RIVER", "river_type", "Type of river", ""),
("DrlsIrO_G64pxSjMKqdZGR3HHAEOveZFm9pL6G0VbM0", "story", "River", "RIVER", "avg_width_m", "Average width of the river", ""),
("8LznLg3a1rdKg5SldbaamOfp-L0Q9M7tG9J07_kqW0k", "story", "River", "RIVER", "avg_depth_m", "Average depth of the river", ""),
("Cl5ZXz4tZFaPzZRbNmX0a5ELibkvHJbBwiMFXfDnPWg", "story", "River", "RIVER", "total_length_km", "Total length of the river", ""),
("e-UDJgF4VnX3wzA7lSzuwPBV-RbF3BKO1bNBEmaaNSo", "story", "River", "RIVER", "drainage_basin_km", "Drainage basin of the river", ""),
("sZfliQYSveAkkL3-59hCx2jTvJf9bfZE6TsJWFX8aW4", "story", "River", "RIVER", "avg_velocity_m_per_h", "Average velocity of the river", ""),
("x2r6n_QTImyid4gWRKXA-39NwLXN2grf9MSY93sJ3K0", "story", "River", "RIVER", "gradient_m_per_km", "Gradient of the river", ""),
("rF47kXEqJd-NLhlZ9K2Tr2RXTza-cZKv6d_ZHDuJRbs", "story", "River", "RIVER", "river_hazards_json", "JSON of the river hazards", ""),
("kDpGvu8t-CeYaTbD1HYiteCdJPcLQshV4uKlyi5-7qc", "story", "River", "RIVER", "river_features_json", "JSON of the river features", ""),
("ffLN-M-Lpa80G9A3r3uw6DX8Avvp2y22aBdHQsOeUi4", "story", "River", "RIVER", "river_nav_type", "Type of river navigation", ""),
("7KiOKhSpnCJ8Iw3brwU8h8HN--inwRKTo_hzcYHGR0M", "story", "River", "RIVER", "flora_and_fauna", "Flora and fauna of the river", ""),
("7GLzPX27cxrSCM9XhS2Hkp5Js9NLO0DjFYVAP1J-ZHo", "story", "River", "RIVER", "water_quality", "Quality of the water", ""),
("GTVQ-oYrQm9y23XU6uE7VX-rk65nMmtYpCj74R59tXU", "story", "River", "RIVER", "historical_events", "Historical events of the river", ""),
("1ijoyaXsrQMfJoRir7LwkiXrfy20SLOGasqCyaFKhxs", "story", "River", "RIVER", "current_conditions", "Current conditions of the river", ""),
("3hl5pTQC7-gmYjUBULvzGgsfe2xgHtwp1soWmwJ7oG8", "story", "River", "RIVER", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("RzWr1w_AQ3yTUSYV-tX6_vbT-La_hEhro_NrHgCBfig", "story", "RiverXMap", "RIVER_X_MAP", "river_x_map_uid_pk", "Primary key, unique identifier for each association", ""),
("ZCcleTur8OTcIA9l0p-ZolDxcjGW92CX8d1UwND65I8", "story", "RiverXMap", "RIVER_X_MAP", "river_uid_fk", "Foreign key linking to the River table", ""),
("b-XmXagTBe3-z9qI7jfWFV8R-k0Ip6GnSz1gsEJaunk", "story", "RiverXMap", "RIVER_X_MAP", "map_uid_fk", "Foreign key linking to the Map table", ""),
("4oI9T9-dDIemmITN-0M174utEDmAj1l9xlNlXaPhSYc", "story", "RiverXMap", "RIVER_X_MAP", "touch_type", "Type of association", ""),
("UQIzyxzCKhOOE2DYdcH-cw3yuOcZKgPPeJG-jZgERLY", "story", "RiverXMap", "RIVER_X_MAP", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("FENXIIiNP395rCfwNcv-Y--FsYTq4ty1cOuAWab2bB4", "story", "OceanBody", "OCEAN_BODY", "ocean_body_uid_pk", "Primary key, unique identifier for each ocean body", ""),
("VKj7RWhVAJ64JRq3aZeEZMvUOUioEyX1DQuoiAXVS6U", "story", "OceanBody", "OCEAN_BODY", "gloss_common_uid_vfk", "Foreign key linking to the Common Glossary table", ""),
("gCvzRXrCat0oly2UlkIp1s6anAGYUtvgqlINlvod_NM", "story", "OceanBody", "OCEAN_BODY", "ocean_body_name", "Name of the ocean body", ""),
("7muliVks2AvaBzP-Ty9jn6RltQhbvKJoE2bIf-cOlRo", "story", "OceanBody", "OCEAN_BODY", "body_shoreline_points_json", "JSON of the body shoreline points", ""),
("9M1iD8CTFiyM072ybyr5bIGd7q9wVhqNYsxuRAZ0mzs", "story", "OceanBody", "OCEAN_BODY", "is_coastal", "Indicates if the body is coastal", ""),
("F7tXjS9JQXK6NFKVXCUOx2n_ff7ML-fMcZs-gRiU5C4", "story", "OceanBody", "OCEAN_BODY", "is_frozen", "Indicates if the body is frozen", ""),
("Gc91_Ms_uo05DFh4UWzKjcPwUVHMMPE3NnK839CtLMQ", "story", "OceanBody", "OCEAN_BODY", "ocean_body_type", "Type of ocean body", ""),
("JWlvoQO14KKc8PlGZQ9nPEZvLnWVneav7qGs--lBCtU", "story", "OceanBody", "OCEAN_BODY", "water_type", "Type of water", ""),
("iu-kbj2k77GQDh3o7728jtvJTgG3VMlUfwXqDt-Qp8k", "story", "OceanBody", "OCEAN_BODY", "is_tidal_influence", "Indicates if the body has tidal influence", ""),
("CGRtLfpEzpvyLdQeZf-TOjeZecUgKdFpGcxM8dPEYP0", "story", "OceanBody", "OCEAN_BODY", "tidal_flows_per_day", "Number of tidal flows per day", ""),
("WwDiU2S4VkUnPrQRm5BFihlHtRrSGieOw3hWK5pMUWQ", "story", "OceanBody", "OCEAN_BODY", "avg_high_tide_m", "Average high tide", ""),
("fXKk42Flc_5LEz1gC4xTARdnw9jWY8L-DCY4E8SM244", "story", "OceanBody", "OCEAN_BODY", "avg_low_tide_m", "Average low tide", ""),
("-kn13NVChqCEsIxeevwSQpwRD2ydUQlCDrHZYU7RKIE", "story", "OceanBody", "OCEAN_BODY", "max_high_tide_m", "Maximum high tide", ""),
("Bd-2rlxFRFOH5zUzBwAtegld4jtGAdlf39JSV6kKR6M", "story", "OceanBody", "OCEAN_BODY", "ocean_wave_type", "Type of ocean wave", ""),
("R8s49Jz-4B07WXABL93_EVzdqeLM8rYqBn4E_aQFfl8", "story", "OceanBody", "OCEAN_BODY", "body_surface_area_m2", "Surface area of the body", ""),
("dnzMwazZyrjZl5qBDXrU9ryGrWwviDuQ3zBoUx4i9Tc", "story", "OceanBody", "OCEAN_BODY", "body_surface_altitude_m", "Altitude of the body", ""),
("rnZwEkT6aWumrGFe4X9pnGmTXr2Dc1I9CZ84s6Q2gWo", "story", "OceanBody", "OCEAN_BODY", "max_depth_m", "Maximum depth of the body", ""),
("eyswBp643-4X17JM-GEQ-lJhvht67cyARVRC3dvdrmE", "story", "OceanBody", "OCEAN_BODY", "avg_depth_m", "Average depth of the body", ""),
("j1MOQZnljPq_54wTMXELtXFYVSFZDr1NcodKjmCgtsI", "story", "OceanBody", "OCEAN_BODY", "ocean_hazards_json", "JSON of the ocean hazards", ""),
("vj9fnBhmP3fWqlTVuZb97-Vwx4Mnj7DQB3asseEbzk8", "story", "OceanBody", "OCEAN_BODY", "ocean_features_json", "JSON of the ocean features", ""),
("oMVgLwFY_UrAGV9ICn1SBUjbL99B6kB05XE02fOhkYk", "story", "OceanBody", "OCEAN_BODY", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("F_8JXnYY2Ws6cT496trpDn_jRukvbof-NYFsrx9_9C0", "story", "OceanBodyXMap", "OCEAN_BODY_X_MAP", "ocean_body_x_map_uid_pk", "Primary key, unique identifier for each association", ""),
("iqG1oR37ih4fVRZKkR_L1n985q2NckR9jmGxGcuu6Xk", "story", "OceanBodyXMap", "OCEAN_BODY_X_MAP", "ocean_body_uid_fk", "Foreign key linking to the Ocean Body table", ""),
("LjT6j9vqHOFCiYODIiZpqTkLGYIoJTBTzU8zeznslCc", "story", "OceanBodyXMap", "OCEAN_BODY_X_MAP", "map_uid_fk", "Foreign key linking to the Map table", ""),
("6RVEAgJ5mx5GVc18ZOjq8M1Q8kLObDq_-_jvhOnorEk", "story", "OceanBodyXMap", "OCEAN_BODY_X_MAP", "touch_type", "Type of association", ""),
("hd6i9SCbvrWdyOxyVausaywLeXxCYpdi2VbwW2LQSzM", "story", "OceanBodyXMap", "OCEAN_BODY_X_MAP", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("oGoMMgx0I95lBON9vUXfYBycxm_ziDBMBgpW-X6XO4U", "story", "OceanBodyXRiver", "OCEAN_BODY_X_RIVER", "ocean_body_x_river_uid_pk", "Primary key, unique identifier for each association", ""),
("nSIWDbHkEZ-yXRi1Pgw8Iq9ir8tLqVSSCjI55FHH99g", "story", "OceanBodyXRiver", "OCEAN_BODY_X_RIVER", "ocean_body_uid_fk", "Foreign key linking to the Ocean Body table", ""),
("J6Mk1oeiGcpRgn3PEg-LDgBNwlbhXiqqXJps0vCIEgQ", "story", "OceanBodyXRiver", "OCEAN_BODY_X_RIVER", "river_uid_fk", "Foreign key linking to the River table", ""),
("l0l9-GTaVOC0zctwpGjjomfuDSDpEJ1ht5G-L6mRj2Y", "story", "OceanBodyXRiver", "OCEAN_BODY_X_RIVER", "touch_type", "Type of association", ""),
("pONpX9bHA3ae7i2cI-7yPp_0Mn3O6LOyCLlZys3-PTM", "story", "OceanBodyXRiver", "OCEAN_BODY_X_RIVER", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("3us65EdVoGw0tH7C3dlrRSiMi6sVWgP9S7a9-EP3GgI", "story", "LandBody", "LAND_BODY", "land_body_uid_pk", "Primary key, unique identifier for each land body", ""),
("ExOhDZr-LFtoId1I1lSNGE5SXF5xNNTwdLa7a3-fhls", "story", "LandBody", "LAND_BODY", "gloss_common_uid_vfk", "Foreign key linking to the Common Glossary table", ""),
("M736NRbpyNHH36uIgofUKO6WsXf9F16Wsk_S2wd2lr4", "story", "LandBody", "LAND_BODY", "land_body_name", "Name of the land body", ""),
("IsxL4p7UEvdO8-woiJgWZrp2GHN53354FO7NhavxN2Y", "story", "LandBody", "LAND_BODY", "body_landline_points_json", "JSON of the land body line points", ""),
("YtLmqrAhHPauLKkvuiS0xQt8yCw_ZcIeaZjpNmS_o5U", "story", "LandBody", "LAND_BODY", "land_body_type", "Type of land body", ""),
("1tSHy-0bf1tSUum5lgYaWDRd9S1SZ6lRc_CnS_sbmAQ", "story", "LandBody", "LAND_BODY", "land_body_surface_area_m2", "Surface area of the land body", ""),
("nXM6WrcSrM8JQX4wUhY-jeGiPgO6brISLE6dwGXgmbQ", "story", "LandBody", "LAND_BODY", "land_body_surface_avg_altitude_m", "Average altitude of the land body", ""),
("5GeFdnb1JblTp_HhP0cvpuz8zCgZD0oyFPgvUYz35M4", "story", "LandBody", "LAND_BODY", "max_altitude_m", "Maximum altitude of the land body", ""),
("05v2lvhl7TAmtRoQ_Gf8NOidRgii8cvKnznJZpjfeCU", "story", "LandBody", "LAND_BODY", "min_altitude_m", "Minimum altitude of the land body", ""),
("LJ49-B3Pp6ocvVd6gtEqCwCeQYYs7RId7sFEAK-sjsQ", "story", "LandBody", "LAND_BODY", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("i8mswAnd-RlqK4SVZq97ruJr7_mGCx3Ml-VHa9ZnGNM", "story", "LandBodyXMap", "LAND_BODY_X_MAP", "land_body_x_map_uid_pk", "Primary key, unique identifier for each association", ""),
("UIbie6YpQGr35BDd7D2wY4XR5kCfDkawCuaa1U2EDoA", "story", "LandBodyXMap", "LAND_BODY_X_MAP", "land_body_uid_fk", "Foreign key linking to the Land Body table", ""),
("b1zGL95ovIdRX-X7XlVj04wsXrxVuKQIIaJntK6ChAA", "story", "LandBodyXMap", "LAND_BODY_X_MAP", "map_uid_fk", "Foreign key linking to the Map table", ""),
("OuVWeD41VwfD3XWnZZQAE5Rt73_isoU8ijqVJAV5v7s", "story", "LandBodyXMap", "LAND_BODY_X_MAP", "touch_type", "Type of association", ""),
("0QAl3MH4iCctWgoD5TA1Ry6RpGO9AYydH2eTThoPSd4", "story", "LandBodyXMap", "LAND_BODY_X_MAP", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("SWi5sbZyutvVnr_uYpu7x2A-u-z26n2KDUOXUyKNHtE", "story", "LandBodyXLandBody", "LAND_BODY_X_LAND_BODY", "land_body_x_land_body_uid_pk", "Primary key, unique identifier for each association", ""),
("eXlDGkvogCm_hEfz88NrFkgl-h51R3u_eRG2wo3yTY4", "story", "LandBodyXLandBody", "LAND_BODY_X_LAND_BODY", "land_body_1_uid_fk", "Foreign key linking to the Land Body table", ""),
("XpisRWro1XuteyKQWSJC7Opbmg3Q_ROWCsUxZhdxMXQ", "story", "LandBodyXLandBody", "LAND_BODY_X_LAND_BODY", "land_body_2_uid_fk", "Foreign key linking to the Land Body table", ""),
("fOZqGlxFX0KsZTi2XQtyzC6ZM1zCgBxuKaijNJ2BPYc", "story", "LandBodyXLandBody", "LAND_BODY_X_LAND_BODY", "land_land_relation_type", "Type of land-land relation", ""),
("dfv4juaL-cQQWdp6oWPEKtHyr9Iy2MQ1v9Gn7NNynng", "story", "LandBodyXLandBody", "LAND_BODY_X_LAND_BODY", "touch_type", "Type of association", ""),
("LBNEYDZpOjo0NTj_cuTW-dBr51diuEFfjngaadZswUs", "story", "LandBodyXLandBody", "LAND_BODY_X_LAND_BODY", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("CmcHR2gJKvQEk8XLzWf1wv1fFljl9lvcBbo0-8vpE5Q", "story", "LandBodyXOceanBody", "LAND_BODY_X_OCEAN_BODY", "land_body_x_ocean_body_uid_pk", "Primary key, unique identifier for each association", ""),
("rMzMj8hxPUwy2Icef7eijpzA-sxn616slkoxXwuKLRs", "story", "LandBodyXOceanBody", "LAND_BODY_X_OCEAN_BODY", "land_body_uid_fk", "Foreign key linking to the Land Body table", ""),
("K_Ee31UBfb5fnlo2hvL7kPWbbGnvjbHsL1pKtnt65kg", "story", "LandBodyXOceanBody", "LAND_BODY_X_OCEAN_BODY", "ocean_body_uid_fk", "Foreign key linking to the Ocean Body table", ""),
("aUrN_by7fqjGdf6juLnx5Rggpv5mUITe9Bm3tB-i_Wo", "story", "LandBodyXOceanBody", "LAND_BODY_X_OCEAN_BODY", "land_ocean_relation_type", "Type of land-ocean relation", ""),
("sWjcgLtcAANjgUsaVICPQoi6r3MElUxTY9CPG8I6pvg", "story", "LandBodyXOceanBody", "LAND_BODY_X_OCEAN_BODY", "touch_type", "Type of association", ""),
("uLKFmbSnWbkvZCtiXSerzmYYL5j0ovgJoASYDvtnZ98", "story", "LandBodyXOceanBody", "LAND_BODY_X_OCEAN_BODY", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("sLqbdWO9_asvTpAhQ-UFSJdYVql2v4bhjH2Z0R0ZzUQ", "story", "SolarYear", "SOLAR_YEAR", "solar_year_uid_pk", "Primary key, unique identifier for each solar year", ""),
("zO57iOE6ccHOTR67kU-ncc3NhZYdJ6IyrNq4dhF8Bt4", "story", "SolarYear", "SOLAR_YEAR", "world_uid_fk", "Foreign key linking to the World table", ""),
("iLiY0prCq8dcgSuXWfKS4Jpci0h8MTptm1Vf5MBg2xc", "story", "SolarYear", "SOLAR_YEAR", "lang_uid_fk", "Foreign key linking to the Language table", ""),
("WKCwRophaemQF3qsCm5chEcGPNLgvF5PgX-hj_FtFDM", "story", "SolarYear", "SOLAR_YEAR", "solar_year_key", "Key for the solar year", ""),
("F_OTO-D23Ej1o4XVJDN7ACiEgbvRsr_5lMj4vT7rojk", "story", "SolarYear", "SOLAR_YEAR", "version_id", "Version of the solar year", ""),
("rrOTgaCD2K17x6h9lDlUYwGqOesYXIeWX4HONbakgoQ", "story", "SolarYear", "SOLAR_YEAR", "solar_year_name", "Name of the solar year", ""),
("cM1MaZheaiK0SzYY6u4cpphcwEsHEN4y1Gl8B_6E6C8", "story", "SolarYear", "SOLAR_YEAR", "solar_year_desc", "Description of the solar year", ""),
("2cH4QqaCwxFbf6JpZ5STGp6CxwMAkMOzVFJGEVxDMek", "story", "SolarYear", "SOLAR_YEAR", "solar_year_span", "Number of solar revolutions in the year", ""),
("Gm75ohlh8r-cwun0Zm1Zxnv4X3LGJYN3mTr5rBfRLag", "story", "SolarYear", "SOLAR_YEAR", "days_in_solar_year", "Number of days in the solar year", ""),
("o_SFEiOkoGS2rUkr306y5i6Pbo7KopqEyyo5MpAXaO4", "story", "SolarYear", "SOLAR_YEAR", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("5oEPx7wEV9Xe2-ytUqPncApcylEoFIYjkQrgs4vJlFc", "story", "Season", "SEASON", "season_uid_pk", "Primary key, unique identifier for each season", ""),
("mvFLABkIMo4tmKftKaix-lEHKrg1emqGzM-z2xgaeVA", "story", "Season", "SEASON", "solar_year_uid_fk", "Foreign key linking to the Solar Year table", ""),
("vF3MXYJOjpvZjADwvZkUkbnXM07ecdxcaeIPeFzmMk8", "story", "Season", "SEASON", "gloss_common_uid_vfk", "Virtual foreign key linking to the Common Glossary table", ""),
("c6HEogr_1PgfFZd17M9Ael5uNwvYeQ_BpCSpDF_iI94", "story", "Season", "SEASON", "season_type", "Type of the season", ""),
("cdxVMJBPWYf_LFE_Lq774rXGNWnhTgtlrjUZGIhX4RQ", "story", "Season", "SEASON", "hemisphere_type", "Hemisphere of the season", ""),
("v5idMD9DMqqK7gXSedCGa-xbbfDPQjgSQy8nv9n-gcE", "story", "Season", "SEASON", "years_in_season", "Number of years in the season", ""),
("X4BesXaO9CGv-IXHS9x7wHadvSHjT-yTPnilfS6A0J0", "story", "Season", "SEASON", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("Al0R8JVQDQ7m4Um1RxSRKQ8qP2GyAZXiPueZAVIEVs0", "story", "LunarYear", "LUNAR_YEAR", "lunar_year_uid_pk", "Primary key, unique identifier for each lunar year", ""),
("_GJ_NX8Lm2gLoA3DExTQuwsbfVbfeR_ZqoYfYeM5uwc", "story", "LunarYear", "LUNAR_YEAR", "world_uid_fk", "Foreign key linking to the World table", ""),
("9zaskKtpVn9tJFI67IEN_xBkLpblX5ZE0aFtIKZWEQc", "story", "LunarYear", "LUNAR_YEAR", "lang_uid_vfk", "Virtual foreign key linking to the Language table", ""),
("gwNGLNnA1gQPlA2unsQ2v-UwlDIIUlJPecskXkEb0pM", "story", "LunarYear", "LUNAR_YEAR", "lunar_year_name", "Name of the lunar year", ""),
("me4FN_MyTRdE60ggVBgyfmcmVKDsHukJTAU39FQRuOI", "story", "LunarYear", "LUNAR_YEAR", "lunar_year_desc", "Description of the lunar year", ""),
("Q2ZWg5-1kAlgmlLYF7sbpuzbvPztqo35rLW7uqC2jS0", "story", "LunarYear", "LUNAR_YEAR", "days_in_lunar_year", "Number of days in the lunar year", ""),
("A0hOLG9WOhrTMT7jWeAZbmp_bn3qWfXDeLgyzuIZVbU", "story", "LunarYear", "LUNAR_YEAR", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("vsEYKuZpqS8p5_cfLNqEJ5dIItKLfoc4C2uN4frZ3EQ", "story", "LunarYearXMoon", "LUNAR_YEAR_X_MOON", "lunar_year_x_moon_uid_pk", "Primary key, unique identifier for each association", ""),
("3PkiX9rF9N6MSuda1BRWveALxFLxMcFc1NerHrR3r6g", "story", "LunarYearXMoon", "LUNAR_YEAR_X_MOON", "lunar_year_uid_fk", "Foreign key linking to the Lunar Year table", ""),
("zQd-CJlW2w7BOLxC047bruiViB9ngFkTstr06yzOQO8", "story", "LunarYearXMoon", "LUNAR_YEAR_X_MOON", "moon_uid_fk", "Foreign key linking to the Moon table", ""),
("aYZw_ywr1rgwgoDojwOFKnGYP9HdeCDUViteqqaXo0o", "story", "LunarYearXMoon", "LUNAR_YEAR_X_MOON", "touch_type", "Type of association", ""),
("SJx6iZnUx9eZTlB3ZiQIbFxoX5z6wuKH8S8OM4lPbT4", "story", "LunarYearXMoon", "LUNAR_YEAR_X_MOON", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("CuTXtqghOURqKuQaoQ5-sZsoi98T3Di0xU6nLXdRExM", "story", "SolarCalendar", "SOLAR_CALENDAR", "solar_calendar_uid_pk", "Primary key, unique identifier for each solar calendar", ""),
("RAVFmn2z3NrRUfRGjoKXISTHEJhOx9Uk25Qa-7L_5eE", "story", "SolarCalendar", "SOLAR_CALENDAR", "solar_year_uid_fk", "Foreign key linking to the Solar Year table", ""),
("hd9Kl9rerXyplqXocYL2iUkukQaIalm7f5gMEopJMEo", "story", "SolarCalendar", "SOLAR_CALENDAR", "year_name_gloss_common_uid_vfk", "Virtual foreign key linking to the Common Glossary table", ""),
("1acvG69l4nuz3J0hnGsF2Cu8QswHWD85wpNq3vtCxDo", "story", "SolarCalendar", "SOLAR_CALENDAR", "season_start_uid_fk", "Foreign key linking to the Season table", ""),
("Xhi6ZzlPNx0Ttj4OStNy_eOeX4F0JsayREVzSsvMFvM", "story", "SolarCalendar", "SOLAR_CALENDAR", "solar_calendar_name", "Name of the solar calendar", ""),
("e4kkuV_L3zAFirtn-0-0oVsViidBjT9Uac2i8x9wCdk", "story", "SolarCalendar", "SOLAR_CALENDAR", "solar_calendar_desc", "Description of the solar calendar", ""),
("21oIkTo2X6TNq3PMJofYYTXFWDy4zkKjTLgzFNWTiPs", "story", "SolarCalendar", "SOLAR_CALENDAR", "epoch_start_offset", "Offset from the epoch start year", ""),
("iInO1XdeMF1U67IPwv7MWnvX-3FdeEdcC1EPi8D2LcM", "story", "SolarCalendar", "SOLAR_CALENDAR", "months_in_year", "Number of months in the year", ""),
("4vhd0MQhJxwX6izzvqxKtn8cKCOtQjN6Z4RsaepHKWw", "story", "SolarCalendar", "SOLAR_CALENDAR", "watches_in_day", "Number of watches in the day", ""),
("OAZ1ci1gw9duTncG-Lb5ajZGBVCUj7s8Q2ZROmhCEY0", "story", "SolarCalendar", "SOLAR_CALENDAR", "hours_in_watch", "Number of hours in the watch", ""),
("e56sL3PapzQJXN0dLabsMyVIrMnBqEi8_HWm0U2-7K8", "story", "SolarCalendar", "SOLAR_CALENDAR", "minutes_in_hour", "Number of minutes in the hour", ""),
("2tsyLkvbjKC0ZD36fJfljkZMiSANpF7Bazm9bwyjbiM", "story", "SolarCalendar", "SOLAR_CALENDAR", "seconds_in_minute", "Number of seconds in the minute", ""),
("u-ilLMw6rw56EH1feNfKQblPVm3EbxP9cwgqUKmP9Cc", "story", "SolarCalendar", "SOLAR_CALENDAR", "leap_year", "Number of leap years", ""),
("JwSeGo979w0ud0QQ10jxUYRsIVybyA3VXd66y1tLQ8U", "story", "SolarCalendar", "SOLAR_CALENDAR", "leap_month", "Number of leap months", ""),
("nrAxe4FXxIbvaTrEtJ54PuhrlGcMrCXSLifJe8HeUDw", "story", "SolarCalendar", "SOLAR_CALENDAR", "leap_days", "Number of leap days", ""),
("_NgNlzljTZOtMaiGRJO6_g392LtkgYGDWLnNdR0yD5w", "story", "SolarCalendar", "SOLAR_CALENDAR", "leap_rule", "Rule for handling leap years", ""),
("I9xijcmfg01DXfb9p1TA_Bii0s0pckUCZgyfk-i6Yws", "story", "SolarCalendar", "SOLAR_CALENDAR", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("NvLKUKOF1YMPLonpW2OEPtVj7kgN19_iV1E1tNS636c", "story", "LunarCalendar", "LUNAR_CALENDAR", "lunar_calendar_uid_pk", "Primary key, unique identifier for each lunar calendar", ""),
("7uAf-rXYf-FzJdzhPp_G-1EnarCdojuDIgggJ65dSpU", "story", "LunarCalendar", "LUNAR_CALENDAR", "lunar_year_uid_fk", "Foreign key linking to the Lunar Year table", ""),
("CbrZdvMXFwyK6yOPP7EFfskFMc1bPd8euo0RgxPX8pU", "story", "LunarCalendar", "LUNAR_CALENDAR", "lunar_year_name_gloss_common_uid_vfk", "Virtual foreign key linking to the Common Glossary table", ""),
("oYTPl9GlZsjtJUsfpQ6r7jjy996bChWYXMlveyEM8g0", "story", "LunarCalendar", "LUNAR_CALENDAR", "lunar_calendar_name", "Name of the lunar calendar", ""),
("XemjgIJfN1sNjCpQ4Tl6uIoGzaQJO7qA3uBywTcMqXo", "story", "LunarCalendar", "LUNAR_CALENDAR", "lunar_calendar_desc", "Description of the lunar calendar", ""),
("__kvMElWV1qNvmlCOO7a9o5_5vi-P_Z-5NSq9NbkFi8", "story", "LunarCalendar", "LUNAR_CALENDAR", "epoch_start_offset", "Offset from the epoch start year", ""),
("EGbOd9IGbHmC-UH8s9Exu06WxLLCMaEyDPpYJfE9_lc", "story", "LunarCalendar", "LUNAR_CALENDAR", "days_in_month", "Number of days in the month", ""),
("asIqM-RGvmLkj1WGzmHJJosbLQu8rn_W48TId0u07XI", "story", "LunarCalendar", "LUNAR_CALENDAR", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("OxLRDrk5L6XrRyjQn6HoMjf1qI6dCS2d5e9sNK9kRcs", "story", "Month", "MONTH", "month_uid_pk", "Primary key, unique identifier for each month", ""),
("-9Gnm_E38sL2CqpPCapzkxAgUtQ-UJcWSpOmYAnHYmA", "story", "Month", "MONTH", "month_name_gloss_common_uid_vfk", "Virtual foreign key linking to the Common Glossary table", ""),
("gdPkK04vyQQT_wvNgl_qspSbgZf5i10OA40vKTLCz2w", "story", "Month", "MONTH", "month_name", "Name of the month", ""),
("FxO89GTs6IVPUGIcjhk9LB3-en4MrqwrGQFpdQlEuss", "story", "Month", "MONTH", "days_in_month", "Number of World days in the month", ""),
("BJ4zhGlNv5R4Fk1XKhVxej_DQLokKGCxJTK-AJMbq10", "story", "Month", "MONTH", "month_order", "Ordinal number of the month", ""),
("7g71pFWkkUMgA_5TgYO-5OcajW1aeNb6YAA00HawWcI", "story", "Month", "MONTH", "is_leap_day_month", "Indicates if the month contains leap day/s", ""),
("0UJDPwmDA8pQnTHHW52M8Z8TBmwNhoHxaHLDuoiScsU", "story", "Month", "MONTH", "is_leap_month", "Indicates if the entire month is leap days", ""),
("DaXPjyT3d4Wu73dSW6sF4rMtu23KBVMw5uslFn-r4og", "story", "Month", "MONTH", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("ytSZY-eyNHrrNfdi_3QUCNXCQ3ZlqWw_pDQmYEA25Ww", "story", "LunarCalendarXMonth", "LUNAR_CALENDAR_X_MONTH", "lunar_calendar_x_moon_uid_pk", "Primary key, unique identifier for each association", ""),
("U74RS6aGv1ttli35OtHbNIzwroJx8hg53iLbTQMPM1I", "story", "LunarCalendarXMonth", "LUNAR_CALENDAR_X_MONTH", "lunar_calendar_uid_fk", "Foreign key linking to the Lunar Calendar table", ""),
("7c1M5Vw0D_cUlrdYd6_bEmOwV4fQqxdNf-HIhKg69B8", "story", "LunarCalendarXMonth", "LUNAR_CALENDAR_X_MONTH", "month_uid_fk", "Foreign key linking to the Month table", ""),
("L0EBBS5JDmNoQ01_cx8KxWK3Ao5jTrDQboBqp2CrlpE", "story", "LunarCalendarXMonth", "LUNAR_CALENDAR_X_MONTH", "touch_type", "Type of association", ""),
("xHiu_JrZqc6XDH37eMVVcbOYK2lRlheazszCThmQlnw", "story", "LunarCalendarXMonth", "LUNAR_CALENDAR_X_MONTH", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("rbuFIA1j_khc-dZip98sD-8T1VYHI8QPeECcMRYWFbU", "story", "SolarCalendarXMonth", "SOLAR_CALENDAR_X_MONTH", "solar_calendar_x_moon_uid_pk", "Primary key, unique identifier for each association", ""),
("4tVL1U-lyerNW4nGYn7_bzCVQgESyXTsmufxzN8zuD4", "story", "SolarCalendarXMonth", "SOLAR_CALENDAR_X_MONTH", "solar_calendar_uid_fk", "Foreign key linking to the Solar Calendar table", ""),
("7BFIzxXVvIrF2kOm0h3k3I4Lnu_jX6IhFVV9NEPEhdM", "story", "SolarCalendarXMonth", "SOLAR_CALENDAR_X_MONTH", "month_uid_fk", "Foreign key linking to the Month table", ""),
("nOhTJhJ_NEDzgBOp0HtJQXH_bNhebS_O88cuR7GAW6Y", "story", "SolarCalendarXMonth", "SOLAR_CALENDAR_X_MONTH", "touch_type", "Type of association", ""),
("a120vpRtVxFmLbd_AaOIETQN4cLim2buZLa9A9l21Fc", "story", "SolarCalendarXMonth", "SOLAR_CALENDAR_X_MONTH", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("Uto673hiQvHAudb1lUYdBGVTkVYzcNHC1FtRI5uz34s", "story", "WeekTime", "WEEK_TIME", "week_time_uid_pk", "Primary key, unique identifier for each week time", ""),
("utohtmJIxVYYTmlh7lC7XywpCinZlJyqCvlCaegb7Eg", "story", "WeekTime", "WEEK_TIME", "week_time_name_gloss_common_uid_vfk", "Virtual foreign key linking to the Common Glossary table", ""),
("HB6dSv5c5KShaXcKDF85oWjZHlAbqfEb_Np8Lkw1djc", "story", "WeekTime", "WEEK_TIME", "week_time_name", "Name of the week time", ""),
("nd2jdZdrvwo-2To6H1SMonbSoVG8PrMzB382xITasVs", "story", "WeekTime", "WEEK_TIME", "week_time_desc", "Description of the week time", ""),
("e8Kfwd9T7ryzFE5cKvZiWlZRJXB0HQIqY3YFg9wvQHM", "story", "WeekTime", "WEEK_TIME", "days_in_week_time", "Number of days in the week time", ""),
("4Z7WHoQbHD2vU2dNDciHjveihsWFjtwJSNWArqfrcS0", "story", "WeekTime", "WEEK_TIME", "week_time_order", "Order of the week time", ""),
("F61HokbpRs5WoqR_GN2nm_QEROuWNbom8Ktf9G2b4aU", "story", "WeekTime", "WEEK_TIME", "is_leap_week_time", "Indicates if the week time contains leap day/s", ""),
("bP8zMecl1ykdUfKQbbtptWU3eoer6uiHAHu85s1sRKw", "story", "WeekTime", "WEEK_TIME", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("UDBIFvnvnicv4M7z7KRFJf8pNkDR52vNtd6WlWGy55s", "story", "LunarCalendarXWeekTime", "LUNAR_CALENDAR_X_WEEK_TIME", "lunar_calendar_x_week_time_uid_pk", "Primary key, unique identifier for each association", ""),
("8n4E3uCgYUWFhN--bGyzEqf5HESfmQOAX84M9uz0W0k", "story", "LunarCalendarXWeekTime", "LUNAR_CALENDAR_X_WEEK_TIME", "lunar_calendar_uid_fk", "Foreign key linking to the Lunar Calendar table", ""),
("BhEv0LMu2JOk28suxYOi_wllVux9Fq4TrbjrM0PS_kk", "story", "LunarCalendarXWeekTime", "LUNAR_CALENDAR_X_WEEK_TIME", "week_time_uid_fk", "Foreign key linking to the Week Time table", ""),
("MtuyBCYNIeWIlnOUI5IL2xq_mtNQEfDWZCJhzNowXes", "story", "LunarCalendarXWeekTime", "LUNAR_CALENDAR_X_WEEK_TIME", "touch_type", "Type of association", ""),
("EMeGW9NFs9dnI4w2sLEVGMj9VqQLct46VLczSqXokNI", "story", "LunarCalendarXWeekTime", "LUNAR_CALENDAR_X_WEEK_TIME", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("VUX3RMYCwAqdZZJ1kI-Eum_O9CZl_QDEqxC00t6utWM", "story", "SolarCalendarXWeekTime", "SOLAR_CALENDAR_X_WEEK_TIME", "solar_calendar_x_week_time_uid_pk", "Primary key, unique identifier for each association", ""),
("TLZspcG3EumRr1sbGVWi2zzpA-IbR2zNiOKQqL-dWKc", "story", "SolarCalendarXWeekTime", "SOLAR_CALENDAR_X_WEEK_TIME", "solar_calendar_uid_fk", "Foreign key linking to the Solar Calendar table", ""),
("SH2Nozgw5i5eUBb2hMCHRkEVDhLcmS22dOpSsLxuWPI", "story", "SolarCalendarXWeekTime", "SOLAR_CALENDAR_X_WEEK_TIME", "week_time_uid_fk", "Foreign key linking to the Week Time table", ""),
("eHO0PblasW-gPm6QNWENSn75L1wdcJKjHJLtDd4FOXw", "story", "SolarCalendarXWeekTime", "SOLAR_CALENDAR_X_WEEK_TIME", "touch_type", "Type of association", ""),
("xtgBFqDk-iaUJvJco2BZ1GOR0wrVn5rIQtiRxVr69tU", "story", "SolarCalendarXWeekTime", "SOLAR_CALENDAR_X_WEEK_TIME", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("DbcQ26st2an_5mwF5_q1yKT0tMWnxD9uG4aRieV98EU", "story", "DayTime", "DAY_TIME", "day_time_uid_pk", "Primary key, unique identifier for each day time", ""),
("DHdG5bY9aPJe4bBEcG9QKNgG9vWS4eWJtMYGnmWgojM", "story", "DayTime", "DAY_TIME", "day_time_name_gloss_common_uid_vfk", "Virtual foreign key linking to the Common Glossary table", ""),
("2jHOxIHTmwLa2a9qbe0Dd6jjFdjLq46Or2A9Lt2WrR4", "story", "DayTime", "DAY_TIME", "day_time_name", "Name of the day time", ""),
("5hEji8iZ9F7wixK4-ZjyhKOu-_wHsqAx5yznPe_uBMY", "story", "DayTime", "DAY_TIME", "day_time_desc", "Description of the day time", ""),
("umQYkzbAgjsLViRIbMesjIJKEk1dBGs7lfKQJDn-SGc", "story", "DayTime", "DAY_TIME", "hours_in_day_time", "Number of hours in the day time", ""),
("ZsWC6gdg_uDa2b2DvxBVqyJstK4dbA4bGlPGSgEsV-k", "story", "DayTime", "DAY_TIME", "day_time_number", "Order of the day in a week", ""),
("-HVWTRfKC-EcsIx2xaSugY5tYSJbLUJcVxoy8x4A6iw", "story", "DayTime", "DAY_TIME", "is_leap_day_time", "Indicates if the day time is only a leap day", ""),
("T6fNCc17DA-Bc7-vOw5WDEmLAlZeQ1fvbz6fdQVTrF8", "story", "DayTime", "DAY_TIME", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("pmDTnZYd9HDJcr3-hZDhEuEYdCkJNRrRshguljI6hck", "story", "WeekTimeXDayTime", "WEEK_TIME_X_DAY_TIME", "week_time_x_day_time_uid_pk", "Primary key, unique identifier for each association", ""),
("N9YA3fqqLBeSamybIdp0Q-f592tY_xblXzi2D01TncM", "story", "WeekTimeXDayTime", "WEEK_TIME_X_DAY_TIME", "week_time_uid_fk", "Foreign key linking to the Week Time table", ""),
("XFq-pPmUJ3oU50pK_v1YgSzkNssHuMokl4R0tap_ycM", "story", "WeekTimeXDayTime", "WEEK_TIME_X_DAY_TIME", "day_time_uid_fk", "Foreign key linking to the Day Time table", ""),
("YulZqUld5Oo7RRTnJXrRmBPEoYGonaGlRPQb-Asolzc", "story", "WeekTimeXDayTime", "WEEK_TIME_X_DAY_TIME", "touch_type", "Type of association", ""),
("Fj20b6hfo3eUhxJrJSyP-hiP0YNUB7Ih5GqNw_jH1_E", "story", "WeekTimeXDayTime", "WEEK_TIME_X_DAY_TIME", "delete_dt", "Deletion date, indicating when the record was marked for deletion", "");