INSERT INTO `METADATA` (
`meta_uid_pk`,
`name_space`,
`model_name`,
`tbl_name`,
`col_name`,
`col_def`,
`delete_ts`) VALUES 
("o3vI9QwRojTf0H-3hKIKiFbcugTCWH5nxRwnYVezlsI", "app", "Metadata", "METADATA", "meta_uid_pk", "Primary key", ""),
("_JdRnZ3y9jrvEBHwUN7KA5PSYG-mD_H6QXa04yoUK9Q", "app", "Metadata", "METADATA", "name_space", "[app|story]", ""),
("5P1qP5woMQQBRTg_hW148N_Pcng2B0bxdP5tbaK1FEE", "app", "Metadata", "METADATA", "model_name", "class name of the data model", ""),
("E60a5e_PHERf7C33V2EKp9uTxxBYWBuvCD_QaoowQyw", "app", "Metadata", "METADATA", "tbl_name", "name of the SQL table", ""),
("Qu10o0ukqQJpvMFG-OUkGgFFLMO98k8l9qZzouBNpng", "app", "Metadata", "METADATA", "col_name", "name of the SQL column", ""),
("zeK4Oxlr__VLNXhmkXxUXHfUjf-40RKqBNLqG5yYd3Q", "app", "Metadata", "METADATA", "col_def", "definition of the SQL column", ""),
("GLYXlJqC_VePK_e2uuxviV2YBOrOVa4ndt8Na9U2CHc", "app", "Metadata", "METADATA", "delete_ts", "date/time of virtual deletion", ""),
("jmM7lIyPKyqwJjOaFkr7GFHVk47qqNEXNNlJoeTiDFI", "app", "Backup", "BACKUP", "bkup_uid_pk", "Primary key", ""),
("YOa7ufJGZdtZrUz22xcby7oq07f2cFOIsOV-zvcqtP0", "app", "Backup", "BACKUP", "bkup_id", "ID (natural key), of the backup, typically type + timestamp", ""),
("bqJ_yWLxK3AiR1dURdZJ9LyryI8vlGFbHO61mCuqH1k", "app", "Backup", "BACKUP", "bkup_dttm", "Date and time of the backup", ""),
("asZ_AFTJid2XpryMD0v7O6FzSsxC090sKeWysWUXB2c", "app", "Backup", "BACKUP", "bkup_type", "Type of backup, e.g., full, incremental", ""),
("_k85YM0PS1pTqmY5ZwGrRn_mlZSzilDBZDaYSP0vLRw", "app", "Backup", "BACKUP", "file_from", "Source file or directory", ""),
("dWB8rv9--ku-hHo4faasUv2ihCLV2YJAzJiCeTIM6hQ", "app", "Backup", "BACKUP", "file_to", "Destination file or directory", ""),
("GpdD43SZ_JKTJJRz63Lqa7k9In52XfR_REhajvYX7t4", "app", "Backup", "BACKUP", "delete_dt", "Date and time the record was deleted", ""),
("0uhYmk9ayRC_TTs-47JCgbtFnxBiw8fIjhxmVYCUQuE", "app", "Texts", "TEXTS", "text_uid_pk", "Primary key, unique identifier for each text entry", ""),
("Q_tV8kKC3WASmrNyu1vZd3vCPBFWOabRFfZSk4FavO4", "app", "Texts", "TEXTS", "lang_code", "Language code of the text, e.g., en, de, fr", ""),
("zLGPH1Wh6S2Lr15ElNfjchcJFF8oi2ytGf5BYB2KfqM", "app", "Texts", "TEXTS", "text_id", "ID of a text string shared across languages", ""),
("6Hpzvhq7pSHBI_yiXzwEGN8ldeEMja80HJHzPgdRQ4w", "app", "Texts", "TEXTS", "text_value", "Text string value", ""),
("dH0h6kcBAYRHAxxZ9zKFfY8w87E9JPn8wcCZ4arDiLQ", "app", "Texts", "TEXTS", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("E_ALh-P8DYzqIA_0itH__B3u-blP1i0kBraUCOVM6ww", "app", "Frames", "FRAMES", "frame_uid_pk", "Primary key, unique identifier for each frame entry", ""),
("wGYHqyhMO9JSQpYkGlLNNvftMPtzf5D7wdF_dfTPoys", "app", "Frames", "FRAMES", "lang_code", "Language code of the frame, e.g., en, de, fr", ""),
("p1pGE_PjUT-zgErxBMj4c8QcqgvlYI3aXQ1UmEkYKwQ", "app", "Frames", "FRAMES", "frame_id", "Natural key, in combo with lang-code and blank delete_dt", ""),
("B75-kualeF5T_QLq6WN86KSVfKbe9VU6NCiOOLMy9C8", "app", "Frames", "FRAMES", "frame_name", "Displayed title of the frame in a given language", ""),
("JLVnoiqTr5HIazI9j2Yqoa6J1MzCKB5q9F-YufSNdOk", "app", "Frames", "FRAMES", "frame_desc", "Description of the frame", ""),
("09L0LasuIMwT_vPijW0H_zWUSUiFIUrfmKqO3DU_PKI", "app", "Frames", "FRAMES", "frame_w", "Width of the frame", ""),
("J1gYP60HVPA5nHDzHBKGYABUt_heTeY6OPeDXZMB2N4", "app", "Frames", "FRAMES", "frame_h", "Height of the frame", ""),
("_3kfqwITl4m1lsegw5BO5HIXf1eaaoPpiPzcmOz-ph8", "app", "Frames", "FRAMES", "pg_hdr_x", "X-coordinate of the page header", ""),
("ZxezU9y91VWmBP1Qn9dU6iP1e4mdu_IYar96fzQsW94", "app", "Frames", "FRAMES", "pg_hdr_y", "Y-coordinate of the page header", ""),
("CCwA8TLgXdUrE9CzzLEaoV6Vx0n5zTs0bA3GYkJ7yug", "app", "Frames", "FRAMES", "pg_hdr_w", "Width of the page header", ""),
("ZOKuPxm1ghGsZhkW1_mAZQHmw54_m7H7kiAOFIkCQOE", "app", "Frames", "FRAMES", "pg_hdr_h", "Height of the page header", ""),
("HNZmzN6qQtMyLAVS_Iu3sqPCw3gYoTrhv-_jyuJlhwQ", "app", "Frames", "FRAMES", "pg_hdr_txt", "Text displayed in the page header", ""),
("zgKadxMEv4o7jymrh0G52WCvMnGeMrUV65uN6vdf8PE", "app", "Frames", "FRAMES", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("5Dd51G6QoHKJG0YSftPjx8wCTzXFmjjJeg3Cs0QK0NU", "app", "MenuBars", "MENU_BARS", "menu_bar_uid_pk", "Primary key, unique identifier for each menu bar entry", ""),
("QRRBghR8Ukq4inAiVXG7ZhG7lbrW0QeQucBVTVIoZWw", "app", "MenuBars", "MENU_BARS", "frame_uid_fk", "Foreign key referencing a frame UID (PK),", ""),
("JhbOUUlgLWaMWgoQXhIsCrgKXxNnlWo6SJui7dRkJTw", "app", "MenuBars", "MENU_BARS", "frame_id", "Natural key to match with corresponding frame records", ""),
("bEGHoqBi7Jta29MJ8o7B_Htenb0EP262E17j95sM5p8", "app", "MenuBars", "MENU_BARS", "mbar_margin", "Margin around the menu bar", ""),
("SfJ3fCnWcleM2EoQsLQgVDeYeycw8TFK47tuOVbHiY8", "app", "MenuBars", "MENU_BARS", "mbar_h", "Height of the menu bar", ""),
("KcN5w4qrM4zHl2ifA7oqk8Ey_z_2Qcf0C1xy2wW2shY", "app", "MenuBars", "MENU_BARS", "mbar_x", "X-coordinate of the top-left corner relative to the frame", ""),
("G5vk1DJq4UXPXQ6eyTSDq4NfNOINv76sUTtuTLqstzQ", "app", "MenuBars", "MENU_BARS", "mbar_y", "Y-coordinate of the top-left corner relative to the frame", ""),
("K1Fc57g7cOPR2A_5rDtpt1Iqhry1NSoI7aE3yaKMHMM", "app", "MenuBars", "MENU_BARS", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("VhktxY2VEAufSUNo08AkFxnV_CeLAtuzH8HLPn6VtjU", "app", "Menus", "MENUS", "menu_uid_pk", "Primary key, unique identifier for each menu entry", ""),
("mlAhdAZL2dvZic8yic76k9g5X68pHct35ypnRbP4rL4", "app", "Menus", "MENUS", "menu_bar_uid_fk", "Foreign key referencing the associated menu bar", ""),
("Qf_LwyugH_965SFbsyuUDIj36Y6LkQCGz7mpxZLtb20", "app", "Menus", "MENUS", "frame_id", "Identifier to match with corresponding frame records", ""),
("wmdZOvMVpoCA__CgIQqKN2WceRLS5TruPEFYW6Pwgg0", "app", "Menus", "MENUS", "lang_code", "Language code for the menu text", ""),
("YvMnVt-wUDTYAPe9gY8P9S8ebTougGbDUeSbzAC2NKI", "app", "Menus", "MENUS", "menu_id", "Generic string label ID or key for menu", ""),
("BA0wP2NB6zAGqXISGe1EUEr99HquSFZs6jrgdIkczZQ", "app", "Menus", "MENUS", "menu_name", "Text string label for menu in designated language", ""),
("Xr6YM972vEY7yEbE9UGUE5Dk9NttB74r_Z3uvTuJG6Q", "app", "Menus", "MENUS", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("MVKVv0pjj8WCsy33HItUNMpwn6cPkJfVC31QFc4a_9A", "app", "MenuItems", "MENU_ITEMS", "item_uid_pk", "Primary key, unique identifier for each menu item entry", ""),
("amSCfw1CWGYUalDu6JCq8yA8JbMSnw27jvYDSsIVDPA", "app", "MenuItems", "MENU_ITEMS", "menu_uid_fk", "Foreign key referencing the associated menu", ""),
("EXQXz5_MF_ISMDFCbiWGGdemVaST7i5QChEGsiush_M", "app", "MenuItems", "MENU_ITEMS", "lang_code", "Language code for the menu item text", ""),
("rz8SyrDyaHweqKdRwYQkbCkHBALnV3o6wzlz7Rpub3w", "app", "MenuItems", "MENU_ITEMS", "frame_id", "Identifier to match with corresponding frame records", ""),
("J2154o5ym8R_ZhQjwx8ud2F0XKJ8dtucmRNOGuM56Kk", "app", "MenuItems", "MENU_ITEMS", "item_id", "Generic string label ID or key for menu item", ""),
("1G5JYVdR447UrYjpvHnOo_P-eeIZYpE1uyz9_6aU0Ls", "app", "MenuItems", "MENU_ITEMS", "item_order", "Order of the item within the menu", ""),
("SVGu9t_F0swIeUPYj-_MajAVMFQaT7lDOXj7x0tTLvU", "app", "MenuItems", "MENU_ITEMS", "item_name", "Text string label for menu item in designated language", ""),
("633gtdJaCpvfsoHAGKnbsZCGQsFEwgr8DZyHeZD4bRc", "app", "MenuItems", "MENU_ITEMS", "key_binding", "Shortcut key binding for the menu item", ""),
("BGZIX3rk1efOnPhhV6-9xblOtVforD8UETDSCybLRf0", "app", "MenuItems", "MENU_ITEMS", "help_text", "Help text or description for the menu item", ""),
("GP38TG0KzwFiFQIIFGyELxGwB0GFyD74cHtg-LryHYM", "app", "MenuItems", "MENU_ITEMS", "enabled_by_default", "Boolean indicating if the item is enabled by default", ""),
("NCV-nEjL7D7fKdWwTm5JnVpfGAPNk5Rqr4YDnsNFNKI", "app", "MenuItems", "MENU_ITEMS", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("zWSyXu_sD5acfnHRCCuqibgkJpjCP2BR9ta7dzzuSTA", "app", "Windows", "WINDOWS", "win_uid_pk", "Primary key, unique identifier for each window entry", ""),
("ACJDLmvc3mhPdrt4f9kmqBfQKBL5mxcrC15_RScYvEI", "app", "Windows", "WINDOWS", "frame_uid_fk", "Foreign key referencing the associated frame", ""),
("jfOo-nnn4Pc-CuiPgkhP3ju1cnVekU7Vm2TD7oGkjI0", "app", "Windows", "WINDOWS", "frame_id", "Identifier to match with corresponding frame records", ""),
("-yle1PVF5RiqDoVjw4xwctTiXQr4nYDfMsQiMEvjriI", "app", "Windows", "WINDOWS", "lang_code", "Language code for the window text", ""),
("JQOHoGTMqGZaaA8thsAWJSKnG8k412pr42MjNRGu1VA", "app", "Windows", "WINDOWS", "win_id", "Generic string label ID or key for the window", ""),
("1mZ0N3xd834L4fPfSpTizASOYkrzJfTAjGjnEoUJcsc", "app", "Windows", "WINDOWS", "win_name", "Displayed title (name), of window in designated language", ""),
("-86zrEORHPv7xy9w7RaXcczZ--qOoMSXe_gekEjq2ME", "app", "Windows", "WINDOWS", "win_margin", "Margin size around the window", ""),
("7GUPbh-zYhQRqDX_FBDkMCt6-Q0BuMMR6V2Qsf_oV_o", "app", "Windows", "WINDOWS", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("EDog90U4vBNCyOoFp5nTOkLWw6b8kVHBrXGMOapaczk", "app", "Links", "LINKS", "link_uid_pk", "Primary key, unique identifier for each link entry", ""),
("XPGY9LxXBAkqh4PNkkExBR3J7SlgxaJCViG057e65Xg", "app", "Links", "LINKS", "lang_code", "Language code associated with the link", ""),
("dSHz-kINCf3eCzVU5nJUawEXboykGTvHFtwYV_iy7NY", "app", "Links", "LINKS", "link_id", "Identifier for the specific link", ""),
("3fbTndmFk8VqeqYG9hls4uffyJUIh2L38mLDnNrrjm8", "app", "Links", "LINKS", "frame_id", "Identifier for the frame associated with the link", ""),
("8uJkyuFi8uQOxE15K0IvaoYQ722sPGCnc2AGPxhBWQI", "app", "Links", "LINKS", "link_protocol", "Protocol type (e.g., HTTP, HTTPS), used by the link", ""),
("5e2tRahtfc88G3iNS-b3lhXHKXqQdRT5AIN4z4RHNjQ", "app", "Links", "LINKS", "mime_type", "MIME type specifying the nature of the link content", ""),
("GE5Z1oxzXzoZ7126Li8zssOnW8OH4nL8QCipm_OaLXY", "app", "Links", "LINKS", "link_name", "Descriptive name of the link", ""),
("6Xj3cNJsGGcMm32ROiQGqE3GI7ppMGc8XplKk7-yqkw", "app", "Links", "LINKS", "link_uri", "The actual URI or address represented by the link", ""),
("Fk-sxY5ehOw8W4J5CkpR9EdVkqi1JXSdiuvu0UbGr9I", "app", "Links", "LINKS", "link_icon", "Icon representing the link visually (stored as BLOB),", ""),
("8aegoMRsqoMVrnRyr5wFbFKZZWOMUFKIw2Azew22Ihc", "app", "Links", "LINKS", "link_icon_path", "Path to the icon file", ""),
("bxnmufPgItLhhGCJ15DHALJU3KsVLyzSjKTGnQ8bImg", "app", "Links", "LINKS", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("wgbebuNqyxJIYKOHqGPvJtyEixnvB1f965J39l4A5GI", "app", "ButtonSingle", "BUTTON_SINGLE", "button_single_uid_pk", "Primary key, unique identifier for each button entry", ""),
("mL8NH21Cunu6htXxQuRFos0cNpVqRiluSo742NIC3Is", "app", "ButtonSingle", "BUTTON_SINGLE", "frame_uid_fk", "Foreign key linking to the associated frame", ""),
("HL0Y2aufYAfIOwP8Gjh2ceZn0gjvLD8CvGVfB0KN3No", "app", "ButtonSingle", "BUTTON_SINGLE", "window_uid_fk", "Foreign key linking to the associated window", ""),
("I3HM4rlClEK5S9Vk1y_PvYhEnSoTTwyH9ANWgLLZ8gc", "app", "ButtonSingle", "BUTTON_SINGLE", "button_type", "Type of button (e.g., submit, reset),", ""),
("Fq-CWkZX36oMOifz-heKxJc_9PNT0hBcke6J5EvdZHI", "app", "ButtonSingle", "BUTTON_SINGLE", "button_id", "Identifier for the button", ""),
("nINoMc1SjSIDA-qEIvstSbKh_rAaARaHk3sgRH_NxRo", "app", "ButtonSingle", "BUTTON_SINGLE", "lang_code", "Language code associated with the button", ""),
("X9Z0ItPPM93xNyI0PzNeDi0GbMhX1qASMXNr7B7GyxI", "app", "ButtonSingle", "BUTTON_SINGLE", "button_name", "Displayed name for the button", ""),
("QBSbnq466NpLiAjuiN2DjmnMjYvhyquFv66iAyH15p8", "app", "ButtonSingle", "BUTTON_SINGLE", "button_icon", "Binary data representing the buttons icon image", ""),
("bRMjzJSStqdUYNdrNlAvYrBEKb7-eDe7hCecOipy5Jk", "app", "ButtonSingle", "BUTTON_SINGLE", "button_icon_path", "Path to the icon file in the app images directory", ""),
("F_10lBZuCV7vMdtSaNCLkt47qKupNcbazvrUlfV4iXg", "app", "ButtonSingle", "BUTTON_SINGLE", "button_key", "Key to press to activate the button", ""),
("AKETa5PAlmYyYwJoHxHuRHDxYUvO_yTjxzmLXYUsme8", "app", "ButtonSingle", "BUTTON_SINGLE", "left_x", "X-coordinate position of top-left corner relative to the window", ""),
("dk5veC3BP8_s1-aQXSbC02XGbWqqC53BuFWb5zl0B3o", "app", "ButtonSingle", "BUTTON_SINGLE", "top_y", "Y-coordinate position of top-left corner relative to the window", ""),
("41d8ir8fwK7hzKA_ENMP3KovZNfsHXX1wfQK4PkPfew", "app", "ButtonSingle", "BUTTON_SINGLE", "enabled_by_default", "True to enable, False to disable the button", ""),
("A_ovEuh-Np8km0okwFnazcTf9AIb3xRiY8mQrNlArBA", "app", "ButtonSingle", "BUTTON_SINGLE", "help_text", "Text to display when the mouse hovers over the button", ""),
("SiBoJ1CH-WfHCdAJqWpb4ehH7E7yhTrDf8FXzoBSFfg", "app", "ButtonSingle", "BUTTON_SINGLE", "action", "Name of the function to call when the button is clicked", ""),
("mGatf1dLVh7WhvGK6oQgbPfyvot19tqcE0g7Z2FmoeI", "app", "ButtonSingle", "BUTTON_SINGLE", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("Qc8AESydfuGj2G1w8YfEELguwFqJoVfCWujlcnJnaqA", "app", "ButtonMulti", "BUTTON_MULTI", "button_multi_uid_pk", "Primary key, unique identifier for each button group entry", ""),
("oqt-EyrGAfyy-F7ZDUynmCW1dIr1XDea5_sJK1jEmGc", "app", "ButtonMulti", "BUTTON_MULTI", "frame_uid_fk", "Foreign key linking to the associated frame", ""),
("_3hHUb6eKMVsIaGC66LxqSJijEW1PbCtLuztMfzOck0", "app", "ButtonMulti", "BUTTON_MULTI", "window_uid_fk", "Foreign key linking to the associated window", ""),
("JFLrwnS1TVXz4NKnjjxuLDvBENFBgdvoiYeEF8RwRI4", "app", "ButtonMulti", "BUTTON_MULTI", "button_type", "Type of button group (e.g., radio, checkbox),", ""),
("rrObmNPvH9X4HzogPLy3E2L3VukMXVAwkekerk67Hjw", "app", "ButtonMulti", "BUTTON_MULTI", "button_id", "Identifier for the button", ""),
("JvEnaH0LKjxSbNz9sWEA9gt3Oj6F4YN5o61rPxljhx8", "app", "ButtonMulti", "BUTTON_MULTI", "lang_code", "Language code associated with the button", ""),
("ZB05rfnI4BZ90HVSrIgUkEJllO0Bgv24S0CmWtwepq4", "app", "ButtonMulti", "BUTTON_MULTI", "button_name", "Displayed name for the button group", ""),
("IsdCI2Ru5GuplCyGEqYduATVhEHI_PRV0Zl5475z8iE", "app", "ButtonMulti", "BUTTON_MULTI", "button_icon", "Binary data representing the button groups icon image", ""),
("k11Hmn7_jwRNqWRznICjd2scAviT4k07Yq8VPKrPlo8", "app", "ButtonMulti", "BUTTON_MULTI", "button_icon_path", "Path to the icon file in the app images directory", ""),
("WxWyGEIDl8g-nnJ93IWaBwSopvQihZc_kIUREeCDq4M", "app", "ButtonMulti", "BUTTON_MULTI", "x", "X-coordinate position of top-left corner relative to the window", ""),
("x8wQ9aSQ06yZ53eQpxNpqYnnzlB0Xl0WBi1fdQJorfE", "app", "ButtonMulti", "BUTTON_MULTI", "y", "Y-coordinate position of top-left corner relative to the window", ""),
("kKzMuG9baIbwnL8kBl2tvLYjDLNRR8pGJEGE73GiC1g", "app", "ButtonMulti", "BUTTON_MULTI", "enabled_by_default", "True to enable, False to disable the button group", ""),
("scM6gK3xdoN0cO_fSL5QvIwrpRb8wkghm2pnWumYH1M", "app", "ButtonMulti", "BUTTON_MULTI", "help_text", "Text to display when the mouse hovers over the button group", ""),
("wUhcGxfrKjYd_75u6aIemoE4f1qDvC-UK6xYVVt_9mw", "app", "ButtonMulti", "BUTTON_MULTI", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("NjIZZXM1mzXTFuvLSKeOXOS3GZ2Gm8kzknAMG38c-i0", "app", "ButtonItem", "BUTTON_ITEM", "button_item_uid_pk", "Primary key, unique identifier for each button item", ""),
("UMPyzGJtKtt2LLbnGse3zXHa5c4OVeQqSs9TOHhAKRs", "app", "ButtonItem", "BUTTON_ITEM", "button_multi_uid_fk", "Foreign key linking to the associated multi-choice button group", ""),
("P-nr_ElplTyN3WQtEqjjAVUfA1AIRxNdZgEYPG2yQ5g", "app", "ButtonItem", "BUTTON_ITEM", "button_id", "Identifier for the button item", ""),
("1bJPZwB87LlW3oZpLlKbSahzVBljrsYwKKWvW1X5mj0", "app", "ButtonItem", "BUTTON_ITEM", "lang_code", "Language code associated with the button item", ""),
("ycRTd14OgJdMSU7roAZYDvhS-OdUw00TmYkIujDVOFE", "app", "ButtonItem", "BUTTON_ITEM", "button_name", "Displayed name for the button item", ""),
("Z87bn6OqoBTfp6p1m1wDkq5koVkwgoSSNoMQqpaNygs", "app", "ButtonItem", "BUTTON_ITEM", "button_icon", "Binary data representing the button items icon image", ""),
("OTgUg06JIvY5Hi62REeiTdpfzrBy4bBESvDkuEb602A", "app", "ButtonItem", "BUTTON_ITEM", "button_icon_path", "Path to the icon file in the app images directory", ""),
("_cFiDzsE_oD-ztCb1yVWrN1Bo_r9gj2vep3Ydo4j17A", "app", "ButtonItem", "BUTTON_ITEM", "button_order", "Integer defining the display order of the button item within the group", ""),
("inW15yH-cVFxr1S2nlXc-Qvcr1B-m1gbAtZwYKarPnY", "app", "ButtonItem", "BUTTON_ITEM", "button_action", "Action or command executed when the button is pressed", ""),
("j9IN8GiuAYcSgfxc-t5gBwUXwNqJRzm2xZNz9M3TJGk", "app", "ButtonItem", "BUTTON_ITEM", "enabled_by_default", "True to enable, False to disable the button item by default", ""),
("NqplT5hbfbcWOsJtmnQyWqgvuRYyXGwE6q1a4Z9mnRo", "app", "ButtonItem", "BUTTON_ITEM", "is_enabled", "Indicates if the button item is currently enabled", ""),
("_tGSplB5oAOjPQZybews5GbRy5zo88je_FNylsPjbEM", "app", "ButtonItem", "BUTTON_ITEM", "help_text", "Text to display when the mouse hovers over the button item", ""),
("qYckOrYwgPor_MId-DB8OxWAS2YtmmQJdZ-ZRdeAupg", "app", "ButtonItem", "BUTTON_ITEM", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("GN248nri0zScU6amFtfLrXN0SN5ffL7SZ-Jq2lMtaQM", "story", "MapRect", "MAP_RECT", "map_rect_uid_pk", "Primary key, unique identifier for each map rectangle", ""),
("4Wq2eUNo5Q3aO5UdnBG_n_RIz1NgoDLXXcoXUPmwgSc", "story", "MapRect", "MAP_RECT", "map_shape", "Shape of the map area (e.g., rectangle, box, sphere),", ""),
("sRLkU-8SlB2pfHHwApxnKNnxQOyBVQZCp7N3gFSMyuo", "story", "MapRect", "MAP_RECT", "map_type", "Type of map area (e.g., geo, astro, underwater),", ""),
("JpuOoHih1lAImlalECRIaw72hHO83XjQ6vxSjkJIh2s", "story", "MapRect", "MAP_RECT", "map_id", "ID of the map rectangle", ""),
("bMiaqmQj6OhdnV7mcel_A73YT5B5CKke661loTdHoiw", "story", "MapRect", "MAP_RECT", "lang_code", "Language code for the map rectangle", ""),
("8gBL6bsmSMX11wLwm3yO9-VBOWCk4pXcW2ddWrxThyw", "story", "MapRect", "MAP_RECT", "map_name", "Displayable name of the map rectangle", ""),
("ukoakQ1XgqRZacEGKPdUIpVx7LtIk7DnaQNfOYz51N4", "story", "MapRect", "MAP_RECT", "map_desc", "Description of the map rectangle", ""),
("4h3O1VA_B996uFXCZAiM4tfPCdYr4De_pRpivRKM4lI", "story", "MapRect", "MAP_RECT", "north_lat", "Northern latitude boundary of the map rectangle", ""),
("64D44f00FrTNxQEmAxM-9iH-oXoPgFSK1SrlVRqavo8", "story", "MapRect", "MAP_RECT", "south_lat", "Southern latitude boundary of the map rectangle", ""),
("QOGm3yk-VLsnQmgfr8HVXw4ZEnPMHNNMWjB8o_-IQ-4", "story", "MapRect", "MAP_RECT", "east_lon", "Eastern longitude boundary of the map rectangle", ""),
("xJ-PVMzr9fOwIxmz0t4b6QPoza5yJ_Ke91XnZFay1uU", "story", "MapRect", "MAP_RECT", "west_lon", "Western longitude boundary of the map rectangle", ""),
("gnpmElZnBtcFrUO2ndJzHAlZZc8QRf3qRe0LJFAjdfg", "story", "MapRect", "MAP_RECT", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("m0Hk-j8-yrEOtW6L1Byejt8yEFS1wKo6t7d-HdSU-Cg", "story", "MapBox", "MAP_BOX", "map_box_uid_pk", "Primary key, unique identifier for each map box", ""),
("msRemlnC6vbJZ7nXqOIGw_5YTiv1Y8ydq5V7vK50wUs", "story", "MapBox", "MAP_BOX", "map_shape", "Shape of the map area (e.g., box),", ""),
("oo5quM6XK65vd47J_QHHGm6K_axoQFcJHp7Zxm3ae_o", "story", "MapBox", "MAP_BOX", "map_type", "Type of map area (e.g., geo, astro, underwater),", ""),
("NuDDeXYVMFjQJmw9nZBgJQfrSZop2modnSXpt5ifLHI", "story", "MapBox", "MAP_BOX", "map_id", "ID of the map box", ""),
("nq7ZxVfR1Z8GTjjQabwjGY1WWO0-AvAno9dAucN2VpY", "story", "MapBox", "MAP_BOX", "lang_code", "Language code for the map box", ""),
("lg5dv8pUmNtINqL7u1BsPIoEWikafuk3w3powA8EAh0", "story", "MapBox", "MAP_BOX", "map_name", "Name of the map box", ""),
("TtnTFukKunC_5_OrbTSbcx1KS3kZRZBmFvza_qfUXL4", "story", "MapBox", "MAP_BOX", "map_desc", "Description of the map box", ""),
("qcaRZ5XQUSv5OG9VfP3CAkyBaEUhx4YDy1iDgm3BDlw", "story", "MapBox", "MAP_BOX", "north_lat", "Northern latitude boundary of the map box", ""),
("gr8zjel07Bg2SE4hpfkrZncbk79JVd0keE60BmWWtS0", "story", "MapBox", "MAP_BOX", "south_lat", "Southern latitude boundary of the map box", ""),
("4lFhbe_gNzgRA-kdFvd5JQade07rrHzSoaJK5vJldzY", "story", "MapBox", "MAP_BOX", "east_lon", "Eastern longitude boundary of the map box", ""),
("ff4HYbZgl4uCYCHm8cQhdNwjKtuv9WGlH-xBPmGPblE", "story", "MapBox", "MAP_BOX", "west_lon", "Western longitude boundary of the map box", ""),
("1KnQs3js2OaAejGneYT2tD2I1z0EAe7u1LXo-qAELyc", "story", "MapBox", "MAP_BOX", "up_m", "Maximum meters upwards from the base level", ""),
("ixstRKt-QSrQc687MDIchcdlf43tcyA5DNbktBW-ISY", "story", "MapBox", "MAP_BOX", "down_m", "Maximum meters downwards from the base level", ""),
("st5QHZ71SYv846yZsk02DVX4caFSBmLpiWpxnn2_CTA", "story", "MapBox", "MAP_BOX", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("3ojIU29gNfX9IrXVVCn0027Xp2_FqI-dZYCQOn1sTMs", "story", "MapSphere", "MAP_SPHERE", "map_sphere_uid_pk", "Primary key, unique identifier for each map sphere", ""),
("t_3TUSuj_NHb0H4jeVJZMGK0PrTRh-qQwq5Sh6LbwXE", "story", "MapSphere", "MAP_SPHERE", "map_shape", "Shape of the map area (e.g., sphere),", ""),
("kjcsInhtmfCzyasf62U-ePTc112ZH86c8FBzESrVZtQ", "story", "MapSphere", "MAP_SPHERE", "map_type", "Type of map area (e.g., geo, astro, underwater),", ""),
("Be2dYaIkh803zZPCd5mIhYBH6sUcgUosUdrOKQVJhD0", "story", "MapSphere", "MAP_SPHERE", "map_id", "ID of the map box", ""),
("jdhfwkQ5gwV1_6zcJuFvV2ECoscg0eTREDzR-G-pfZI", "story", "MapSphere", "MAP_SPHERE", "lang_code", "Language code for the map box", ""),
("s8CkW_sran8y9NmKGry_-CHHjA86Vz_0lP9nUVVDavM", "story", "MapSphere", "MAP_SPHERE", "map_name", "Name of the map sphere", ""),
("xv7R6BDnp6HzYJqWx-VWb53TwfSkuc6NlZJBEPYAkcM", "story", "MapSphere", "MAP_SPHERE", "map_desc", "Description of the map sphere", ""),
("y3EYh6Ijff4WuGZorzpxGamFFUK4UO5mqXj8wSx0g9w", "story", "MapSphere", "MAP_SPHERE", "origin_lat", "Latitudinal coordinate of the spheres origin", ""),
("0ix70PrPraxr_LjowfB0yW2q2Az1gwJK-tsbEBGQlVo", "story", "MapSphere", "MAP_SPHERE", "origin_lon", "Longitudinal coordinate of the spheres origin", ""),
("eKpOR8AvCibECT0B_NUE-r9JW-bt3DQHrinKRT15GgA", "story", "MapSphere", "MAP_SPHERE", "z_value", "Z coordinate value, indicating height or depth from a reference point", ""),
("l-ccZpmjWbaiGCgtI95Oa0fqK6YnI_4BbW6PlJH_6P8", "story", "MapSphere", "MAP_SPHERE", "unit_of_measure", "Unit of measure used for dimensions (e.g., meters, parsecs),", ""),
("FPW7yi0UovoQ7TjyZ0jvKux-UzL7l5RZDV3SXFuWSQs", "story", "MapSphere", "MAP_SPHERE", "sphere_radius", "Radius of the sphere", ""),
("hzvO6kEGy8YyoQdWoPsy1d5mS8ViepMh_IEY21eEiV4", "story", "MapSphere", "MAP_SPHERE", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("vihX8XBmOsCsg8TF4YTBHZSlNEJ-qRb7VDssmtw5vVU", "story", "Grid", "GRID", "grid_uid_pk", "Primary key, unique identifier for each grid", ""),
("5cFS7BdOXKecLeqTi3V60ngId3N7ywh8feZxMGHwZro", "story", "Grid", "GRID", "grid_id", "ID of the grid", ""),
("7sXtnwQ20YljRF2T6ruqoaZQccEiIic36HM9oI5g3vg", "story", "Grid", "GRID", "x_col_cnt", "Number of columns (east-west direction),", ""),
("b5y-EiiFVr106Nsf9O1AkqsS9g1Uhinn_L58XnnXgEI", "story", "Grid", "GRID", "y_row_cnt", "Number of rows (north-south direction),", ""),
("X_4mcmALmBJ8QkKC7hdzRDZtrsOZfcIlUx-W_BN0MN8", "story", "Grid", "GRID", "z_up_cnt", "Number of layers above the zeroth row", ""),
("0SK1U2ep_Chi3Scl6HhrCwTquxWqYgrT8DwgQi6FL_Y", "story", "Grid", "GRID", "z_down_cnt", "Number of layers below the zeroth row", ""),
("xsz7vyKpygU5mZUupP0QGD6IsckuNWLE897QYt3becg", "story", "Grid", "GRID", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("6cC_hhNZlk4ZODGz1mA0DQECopUjQimILfeTYZ2aS7U", "story", "GridCell", "GRID_CELL", "grid_cell_uid_pk", "Primary key, unique identifier for each grid cell", ""),
("t2MM_RT_1ENZqSsVG88BpXIz_5GfGJVjf9OctfukrA4", "story", "GridCell", "GRID_CELL", "grid_uid_fk", "Foreign key linking to the Grid table", ""),
("nk4Z6pGinY1LHUPVDlSUss33uZ3SZSzE_wrJPPRB1yc", "story", "GridCell", "GRID_CELL", "grid_id", "Name of the grid this cell belongs to", ""),
("Y7aq_htOcFmysRuLdRCW2XSZecUE2re4vW1ckJ00_7w", "story", "GridCell", "GRID_CELL", "lang_code", "Language code for the grid cell", ""),
("o6h2dT9l7svWgQWNcKqgvmR8AuVA7aqt-SaOvQcBqxI", "story", "GridCell", "GRID_CELL", "grid_cell_name", "Optional descriptive name for the grid cell", ""),
("GH1z28GwWduB__sWWmtiv8Wk4UKTh7hV_uZjOGVZbSQ", "story", "GridCell", "GRID_CELL", "x_col_ix", "Zero-based column index (east-west direction),", ""),
("KhgUlN9zS3VswugllISsLs-oOsOWTFEk9hHhyjfqZyc", "story", "GridCell", "GRID_CELL", "y_row_ix", "Zero-based row index (north-south direction),", ""),
("pbq0m-iYSHteamBHnZZEJIjw3Xk80bLE1YcIBUxYSyw", "story", "GridCell", "GRID_CELL", "z_up_down_ix", "Index indicating vertical position (positive for up, negative for down),", ""),
("9XEHwuuTGMvXVKI-y7_fp4AfaJV2DrEjuZBKNqNBCF0", "story", "GridCell", "GRID_CELL", "grid_cell_id", "Tuple representing the x, y, z location in the Grid matrix", ""),
("hPbRabDIPUfOFWvApNQuAx1YQngJxTAyZ4WbQpacQnI", "story", "GridCell", "GRID_CELL", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("xu4t-A_tbh-fgwLk-Vnl_11hXy95YpY4i7Pz_sXOkZY", "story", "GridInfo", "GRID_INFO", "grid_info_uid_pk", "Primary key, unique ID for each grid info record", ""),
("ItJgn632GOdcHt_apqyFZTyHfijrhq5jewKb48Uk7wg", "story", "GridInfo", "GRID_INFO", "grid_uid_fk", "Foreign key linking to the Grid table", ""),
("rhpv3NUSV4Fcbd7AhfjCjjqj3CjRTSt9ngDJ5MZeKD8", "story", "GridInfo", "GRID_INFO", "grid_cell_uid_fk", "Foreign key linking to the GridCell table", ""),
("88f_um7OkkfkL9VTwubbJCrkC0MGnVGERhlcE_7tkZc", "story", "GridInfo", "GRID_INFO", "grid_id", "Name of the grid this information belongs to", ""),
("qYgaAhqvJCz_poG87XRcy0ucaS7AGSWBYUyoTUXGAfE", "story", "GridInfo", "GRID_INFO", "grid_cell_name", "Name of grid cell this info is associated with", ""),
("EXkG7y4UAP8Sa-uJ_AiyYJN1KTr177mkD6oUamig7ro", "story", "GridInfo", "GRID_INFO", "grid_info_id", "Short universal descriptive tag for the cell value", ""),
("gxdoQvd8UX1G3-R-ZrtWDXjG5578HCEwxxkgryUiIdE", "story", "GridInfo", "GRID_INFO", "lang_code", "Language code for the grid info", ""),
("sQCVUyL75BdE7U8tnIBiSD8yTFdAv1fra3KVY9WyFMY", "story", "GridInfo", "GRID_INFO", "grid_info_name", "Label for value, providing context or description", ""),
("IYih49EXEx7GEIN4nVjJqLnhQSzuGa-qDIRFdPsoVyc", "story", "GridInfo", "GRID_INFO", "grid_info_int", "(optional), Integer value for the cell", ""),
("lNA5ImqicrOz51dZLMA17O9MhNwDeVSHqti-pdBTaoo", "story", "GridInfo", "GRID_INFO", "grid_info_float", "(optional), Float value for the cell", ""),
("r3VNcDXjFvCfY1jJVm4aZVHTeK5yP21MQk24AcvohtE", "story", "GridInfo", "GRID_INFO", "grid_info_str", "(optional), String value for the cell", ""),
("94tTYBS7YIW6Z_fnvDJsQdZIzBrvGHpOajifsx0y99Y", "story", "GridInfo", "GRID_INFO", "grid_info_json", "(optional), JSON string value for the cell", ""),
("00a-0ksHQH-DDIsW5Jkk1HUUg7w8t_s_J4TDZKzLFgU", "story", "GridInfo", "GRID_INFO", "grid_info_img_path", "(optional), Path to image object for the cell", ""),
("359Ft3tninFdIZmazI_TwFPeOBbKfftyjXSai_eb05w", "story", "GridInfo", "GRID_INFO", "grid_info_img", "(optional), Image object for the cell, stored as a BLOB", ""),
("Ht7IEP0VybeRQ4lqWcEwoUXA-LZqF_u0-QmhykCHpSQ", "story", "GridInfo", "GRID_INFO", "delete_dt", "Deletion date, when the record was marked for deletion", ""),
("uz73MC-GhfiPgd148EadJRxJ-W02dYtkMvVr2-s96YY", "story", "CrossAssociation", "CROSS_X", "cross_x_uid_pk", "Primary key, unique ID for each association", ""),
("46MWh4dkUmzSl5mXCbJHxXL_u7cN5R3ru690OWpgstM", "story", "CrossAssociation", "CROSS_X", "uid_1_table", "Table name of the first table in the association", ""),
("6rRShx7LGL5YwP4XpD2k-hhcORJZ36453TyZUpw5ero", "story", "CrossAssociation", "CROSS_X", "uid_1_vfk", "VFK to first table UID in the association", ""),
("YHDQsfA6KCHucDxOq26kWbCwCp9Q563XorTzh-Nx0I8", "story", "CrossAssociation", "CROSS_X", "uid_2_table", "Table name of the second table in the association", ""),
("55b3Pw7M8IdfscQJuj18fc5k4wvAzsHXzK-vA4bIgoo", "story", "CrossAssociation", "CROSS_X", "uid_2_vfk", "VFK to second table UID in the association", ""),
("en_3oTOxEpzDRYtqc3af5-ue-p59EkkPDMozyB5sdKw", "story", "CrossAssociation", "CROSS_X", "touch_type", "Describes the relationship type between the two records,", ""),
("pFy1wpbFOkqQs_hnXtKNVsxsNRl_Ff44LDHOod87zKY", "story", "CrossAssociation", "CROSS_X", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("VIJKq7HZVAjBg1-ceA76zMwjOaPQ0KdAv5XZvIqWTL4", "story", "CharSet", "CHAR_SET", "char_set_uid_pk", "Primary key, unique ID for each character set", ""),
("x2JCMq5fshew9c8z-r2Y5KVOb2ZhVQhwYo-xf3KAEDI", "story", "CharSet", "CHAR_SET", "font_name", "Name of the font associated with the character set,", ""),
("wJDrgqR7K6tidH8e77q7kCWS5k7Z_tc7H1NX1MhTXHo", "story", "CharSet", "CHAR_SET", "char_set_type", "Type of the character set, default is alphabet,", ""),
("WDrP2pyYkNfS4G1ZlKbRSMIhFXgP7R1jNaogxYOGpis", "story", "CharSet", "CHAR_SET", "char_set_desc", "Description of the character set, providing", ""),
("UXy0UlOf11pVl5t9Ecs18ggbhnuY4YmOQhIB7eUEXU4", "story", "CharSet", "CHAR_SET", "delete_dt", "Deletion date, indicating when the record was", ""),
("Y-mgYt6VjIXlIqke-hMD7sWcheZ6dajllm8L4Tt69B8", "story", "CharMember", "CHAR_MEMBER", "char_member_uid_pk", "Primary key, unique identifier for each character member", ""),
("S3VS95SXad6ml-VU6HPNoXKOVgpWcU5YyLyyyUtmfT0", "story", "CharMember", "CHAR_MEMBER", "char_set_uid_fk", "Foreign key referencing the character set this member belongs to", ""),
("9eqbTHFLKdkjvdE74RG7GKsmONnJYS9pteYEJPaxASY", "story", "CharMember", "CHAR_MEMBER", "char_member_name", "Name of the character member", ""),
("KezzxL2fzazCJJ4A2nxYfyIK_mYa4S8SjUPbjf9Sh6o", "story", "CharMember", "CHAR_MEMBER", "char_member_image", "Binary data representing the image of", ""),
("aqlFhkTRG6fiuMHaVbOHUJxshgW9zvsb2dzpmuyCem8", "story", "CharMember", "CHAR_MEMBER", "char_member_path", "File path to the image or representation of the character", ""),
("p56Fh1437c0n2i1XrUvFIW3PFf2nWDzrqM1BUFP7fRU", "story", "CharMember", "CHAR_MEMBER", "char_member_desc", "Description providing additional details about the character member", ""),
("Ceq2fQcBZfX9Om7hKSrlcXve6uwoFrXZZQnIi88tnug", "story", "CharMember", "CHAR_MEMBER", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("zPtHY03g1JDaPwopYmLEocCtu06_Y34KVv88CT6HAYE", "story", "LangFamily", "LANG_FAMILY", "lang_family_uid_pk", "Primary key, unique identifier for each language family", ""),
("8CiHYW6gISF8qdEIilKS8kdUnnFKt6Txjzt-EhqeAUs", "story", "LangFamily", "LANG_FAMILY", "char_set_uid_fk", "Foreign key referencing the character set used by the language family", ""),
("A0KzONIR_MztF6MTZd20blf4XHCLi5lKxW9Ux4baFi4", "story", "LangFamily", "LANG_FAMILY", "lang_family_name", "Name of the language family", ""),
("5yNJMCpKdbgw4hcRAWPSn4QSeuhdH3KIeZnk_9u07u4", "story", "LangFamily", "LANG_FAMILY", "lang_family_desc", "Description of the language family", ""),
("_joyZnfHxK8fi3jxUMfx-3Pe5wClaz56ObGDWYSD98w", "story", "LangFamily", "LANG_FAMILY", "phonetics", "Description of the phonetics of the language family", ""),
("12ZDqp_soHtnsmm6HzbOqoyx5G92jZ3OUFWDAHALh5g", "story", "LangFamily", "LANG_FAMILY", "cultural_influences", "Description of the cultural influences on the language family", ""),
("8j7V98GbHneG1o0FuS9GGiR7AmraMXRf1M9YCg2vFl4", "story", "LangFamily", "LANG_FAMILY", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("SWt5VFnF_EDCHprLQO69cW5nmXgC4OsgWah4lRLLqB8", "story", "Language", "LANGUAGE", "lang_uid_pk", "Primary key, unique identifier for each language", ""),
("VRGuGDDhbf2U9sN3qlTvVm4hATRHOMzmZhOGYUOq1Ts", "story", "Language", "LANGUAGE", "lang_family_uid_fk", "Foreign key referencing the language family this language belongs to", ""),
("SD3P2n2MUMgBPEH7dhveU1ngdiYtv9XKuYjVJtISgtQ", "story", "Language", "LANGUAGE", "lang_name", "Name of the language", ""),
("hEV626MiQYIVnI68hHOVBcHJuqqWs00STIg3fi4qLgI", "story", "Language", "LANGUAGE", "lang_desc", "Description of the language", ""),
("92PIzg6SU8d-XOuIrcrvZIT69_koOgUZiSTq6oMETZI", "story", "Language", "LANGUAGE", "gramatics", "Description of the gramatics of the language", ""),
("aat2UORvoCpUHiZi1nW4w8tEyDxoN9Nuc8uCgZCUiNw", "story", "Language", "LANGUAGE", "lexicals", "Description of the lexicals of the language", ""),
("NtAmAE0h4Cag4k92nP2ZPgWA93En_CWF2JqnfgR33EI", "story", "Language", "LANGUAGE", "social_influences", "Description of the social influences on the language", ""),
("bJY8JKPHHvod-o3J8HWxPTAcJes3ze8kiQcssfgl9H0", "story", "Language", "LANGUAGE", "word_formations", "Description of the word formations of the language", ""),
("NMYbN-CsOrZNATqA41WQ9A7TLbwcehIYYLvDg4jNJDI", "story", "Language", "LANGUAGE", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("AfoFoqAV8zgDr65IccVN4nyPKEcY_zUy9h6R6xu-YR4", "story", "LangDialect", "LANG_DIALECT", "dialect_uid_pk", "Primary key, unique identifier for each dialect", ""),
("rFFSBi3xlzw5y1oeKZfcpiD2Ce_yWArWANsYAPs73oQ", "story", "LangDialect", "LANG_DIALECT", "lang_uid_fk", "Foreign key referencing the language this dialect belongs to", ""),
("2XMU0uXakehEzDDcA6An09R5eDuhWCj94FUrnPDJubQ", "story", "LangDialect", "LANG_DIALECT", "dialect_name", "Name of the dialect", ""),
("SRdcWuyE8j983Mi3UKiyi_KzDRLtnghJtv0EiyRM_8I", "story", "LangDialect", "LANG_DIALECT", "dialect_desc", "Description of the dialect", ""),
("jHcBkZNNTwHXD9oHt4Srej7Tz8FXo-GXf-S8icqStZg", "story", "LangDialect", "LANG_DIALECT", "divergence_factors", "Description of the divergence factors of the dialect", ""),
("DEWdPnygnM5rx3MBM1f2xvCDVYlSvIsNG2Ej05DhM7A", "story", "LangDialect", "LANG_DIALECT", "syncretic_factors", "Description of the syncretic factors of the dialect", ""),
("4fdM6q_iDCt97jVYt_W_JVY5sAW2i_wqjj51SJ5Lr4c", "story", "LangDialect", "LANG_DIALECT", "preservation_factors", "Description of the preservation factors of the dialect", ""),
("iIM2dHNRn4gv6DXD_s0Mdg_ODTkIsg03lhvOw1BniS0", "story", "LangDialect", "LANG_DIALECT", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("k3_6dQ2rJrxPTD7EQjaG_KSxiThq05mumcNPwl-ftAo", "story", "GlossCommon", "GLOSS_COMMON", "gloss_common_uid_pk", "Primary key, unique identifier for each common glossary item", ""),
("xfEkeLDP52TTfJtHwmeMDWuZir3n1ZTwLZgBNHZvEBI", "story", "GlossCommon", "GLOSS_COMMON", "dialect_uid_fk", "Foreign key referencing the dialect this glossary item belongs to", ""),
("SeESaZKFSTw98GfWy44nRGQ1jCgMklQOUBv4f70jrPI", "story", "GlossCommon", "GLOSS_COMMON", "gloss_type", "Type of the glossary item", ""),
("EXYamemgvhQTM6hbRnWbq13fNLVq33dNrDYfJFOFwEk", "story", "GlossCommon", "GLOSS_COMMON", "gloss_name", "Name of the glossary item", ""),
("i1QH2r9VQjwNXBV3EJkFtqACw_dyBxoFyN8ntE2Ev1Y", "story", "GlossCommon", "GLOSS_COMMON", "gloss_value", "Value of the glossary item", ""),
("W5sa_1eH5zrRC7TlXXEC9lCaWe8isS1I5b-4Mj90W5c", "story", "GlossCommon", "GLOSS_COMMON", "gloss_uri", "URI of the glossary item", ""),
("pq4NcIRd_DBogSxjLZwEpNeL1DRr4fsFz_5bkNYkj7c", "story", "GlossCommon", "GLOSS_COMMON", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("gtBO2_6YWdLQo5B5ks8FOSEK66lijpBZ5mxF4Mre0DY", "story", "Glossary", "GLOSSARY", "glossary_uid_pk", "Primary key, unique identifier for each glossary item", ""),
("MYbMQjIGEIyRwwth-dhmuOFi29jjlaIyQb-WSVM513E", "story", "Glossary", "GLOSSARY", "gloss_common_uid_fk", "Foreign key referencing the common glossary item", ""),
("4bigHmbGTnuBsZ7gpxtuT5nMqRmgXKfRstRs5Xq1FIY", "story", "Glossary", "GLOSSARY", "dialect_uid_fk", "Foreign key referencing the dialect this glossary item belongs to", ""),
("rzM8YfWZ9jJR10nN2Hbb9ac5kddTWIlYdawLQ8pJWhU", "story", "Glossary", "GLOSSARY", "gloss_type", "Type of the glossary item", ""),
("N5HEzBE3hsTK2evN_eNmAWLHwAJyLjvjfO4YzrGDu1E", "story", "Glossary", "GLOSSARY", "gloss_name", "Name of the glossary item", ""),
("n9MnqLLPNXGhOVn53iDsvjKAxh7iXzfqNVwhmn49bs0", "story", "Glossary", "GLOSSARY", "gloss_value", "Value of the glossary item", ""),
("0giTE6ZgTGuJrIVBjQgZYiBwEivTntrKy9kZnp1-cTY", "story", "Glossary", "GLOSSARY", "gloss_uri", "URI of the glossary item", ""),
("i8HYNth9dEPVGMUertSZt9tpUBmIlVY2mvDaT_aZVfw", "story", "Glossary", "GLOSSARY", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("43qwe-Wfq3SUmRS6W3XyanDAKf4fziFw8zkd4GbhmeI", "story", "Universe", "UNIVERSE", "univ_uid_pk", "Primary key, unique identifier for each universe", ""),
("jiBQXtqAbI86eTZwLM8-16iwvJiLmMeKKp0M58I6Oso", "story", "Universe", "UNIVERSE", "univ_name", "Name of the universe", ""),
("s4qv2dy9Uol8gJgH7_El3fkoOI-ZvtBmmiM1JsNUfzs", "story", "Universe", "UNIVERSE", "radius_gly", "Radius of the universe in gigalightyears", ""),
("IdZFwPVlTKNV7KAIfAWFgJDSN4G4vceTkzWNe2YR4JY", "story", "Universe", "UNIVERSE", "volume_gly3", "Volume of the universe in gigalightyears cubed", ""),
("HLBZV7vcvRTJbuAd77zpkuwmIS6KuZLKuV9AE4E5grs", "story", "Universe", "UNIVERSE", "volume_pc3", "Volume of the universe in parsecs cubed", ""),
("R_VIhHeeq2ZcAcTwPBZh7aalv0Hsa1at7rtCZKbla3I", "story", "Universe", "UNIVERSE", "age_gyr", "Age of the universe in gigayears", ""),
("K-vfsI6BcY6OW8ADnc-Q6fYaCLBSBc8pjbfAYqSogec", "story", "Universe", "UNIVERSE", "expansion_rate_kmpsec_per_mpc", "Expansion rate of the universe in km/sec per megaparsec", ""),
("e4nRtJkrJy69VoajfFB2zE_ytsjSrNPFbKJT7AioIDs", "story", "Universe", "UNIVERSE", "total_mass_kg", "Total mass of the universe in kilograms", ""),
("cjUciUtSE6otXzSH7CsKbC10q0jZcf9nlfswNu5TYBA", "story", "Universe", "UNIVERSE", "dark_energy_kg", "Amount of dark energy in the universe in kilograms", ""),
("XNEQQ58mlJyXojPpoy-ds56zhuOm58ENbpYVWe363Ec", "story", "Universe", "UNIVERSE", "dark_matter_kg", "Amount of dark matter in the universe in kilograms", ""),
("AVb-rNQ_vPp-gsQYbizec8rvojq6qRreqOvTB3JprMc", "story", "Universe", "UNIVERSE", "baryonic_matter_kg", "Amount of baryonic matter in the universe in kilograms", ""),
("_DXG9hwQRhYM5MVkB6gfinueJyVRBzPbYyP_WSAwTW8", "story", "Universe", "UNIVERSE", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("_-9v6MaYKWHbL6uHCRoZHXoZf0to-28UsG5a1-UJnGw", "story", "ExternalUniv", "EXTERNAL_UNIVERSE", "external_univ_uid_pk", "Primary key, unique identifier for each external universe", ""),
("va3mIUSMbb3RE5F_guUo3cqdy_YLYE1fQO_5q6F5kgc", "story", "ExternalUniv", "EXTERNAL_UNIVERSE", "univ_uid_fk", "Foreign key linking to the Universe table", ""),
("T8Er0rVqfub4TZLegFcgEn2iphJ71tvuCYdEB3zDqVs", "story", "ExternalUniv", "EXTERNAL_UNIVERSE", "external_univ_name", "Name of the external universe", ""),
("2YkolBzdJG2Ior6Cn95NB3VOAXpHBvokJ5-CwuWOFlY", "story", "ExternalUniv", "EXTERNAL_UNIVERSE", "mass_kg", "Mass of the external universe in kilograms", ""),
("Ech4OqVicpjQM35ONpu-NpUSDDg9E7Ytt4nOD6dXsC4", "story", "ExternalUniv", "EXTERNAL_UNIVERSE", "dark_energy_kg", "Amount of dark energy in the external universe in kilograms", ""),
("TRLCrtoMwoH1jPUvxVSGt2dMdOhKsmjt7q71i_LpfOg", "story", "ExternalUniv", "EXTERNAL_UNIVERSE", "dark_matter_kg", "Amount of dark matter in the external universe in kilograms", ""),
("B9Bx8C5uzwnWOWXWUh-PM94ynvd3DUj3b8DSM-EbeAc", "story", "ExternalUniv", "EXTERNAL_UNIVERSE", "baryonic_matter_kg", "Amount of baryonic matter in the external universe in kilograms", ""),
("NtOlXUJ1pUKi8FMaqQlksuruhQTQel8qABmADz8VdWc", "story", "ExternalUniv", "EXTERNAL_UNIVERSE", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("hQhXVtl6lZKJCj1OCRSNesc6dVFtga2GNWqRonZnJU8", "story", "GalacticCluster", "GALACTIC_CLUSTER", "galactic_cluster_uid_pk", "Primary key, unique identifier for each galactic cluster", ""),
("CAoim1I5PAvRL4ZqLm8bnLKPxX_B9FfVMYFGP9IM4Cc", "story", "GalacticCluster", "GALACTIC_CLUSTER", "univ_uid_fk", "Foreign key linking to the Universe table", ""),
("xDRCJoenKgWrobA-22kAFYFB9rO5DsDbYNsLALh8rc4", "story", "GalacticCluster", "GALACTIC_CLUSTER", "galactic_cluster_name", "Name of the galactic cluster", ""),
("ZECxNX5JBykpHkOnYjBrRgHRUKranr7TAoGo0zfgqBc", "story", "GalacticCluster", "GALACTIC_CLUSTER", "center_from_univ_center_gly_x", "X coordinate of the center of the cluster in gigalightyears", ""),
("2loXqjjjclTZ5utwmI_oEU__JtQDqQmvGzAJuWheCvQ", "story", "GalacticCluster", "GALACTIC_CLUSTER", "center_from_univ_center_gly_y", "Y coordinate of the center of the cluster in gigalightyears", ""),
("AckFgnfymJ-cKSpPPxkE_130a9uK_uGj-hAVRL7wSgI", "story", "GalacticCluster", "GALACTIC_CLUSTER", "center_from_univ_center_gly_z", "Z coordinate of the center of the cluster in gigalightyears", ""),
("7pCYXQms_1i-V-kvZO0TRVMxBRGQcxadcCrVQfRBL2c", "story", "GalacticCluster", "GALACTIC_CLUSTER", "boundary_gly_x", "X coordinate of the boundary of the cluster in gigalightyears", ""),
("iPSySJCiK5BlFstoq539WHKBGLzZp2hJW_xeExkBLqo", "story", "GalacticCluster", "GALACTIC_CLUSTER", "boundary_gly_y", "Y coordinate of the boundary of the cluster in gigalightyears", ""),
("hRArFWTlje1R9NR2XgPoIofmmGRZygqQDDzbfRYaOIk", "story", "GalacticCluster", "GALACTIC_CLUSTER", "boundary_gly_z", "Z coordinate of the boundary of the cluster in gigalightyears", ""),
("Fl05M58awfRcx8Xrw75C_hRkE8xFejTYUWDunfZgHKM", "story", "GalacticCluster", "GALACTIC_CLUSTER", "cluster_shape", "Shape of the cluster, default is ellipsoid", ""),
("VMA2WEup5_ilnVN4iQyz-wA0oRy0pSCs_oNhlLBxtco", "story", "GalacticCluster", "GALACTIC_CLUSTER", "shape_pc_x", "X coordinate of the shape of the cluster in parsecs", ""),
("quUX8MgMsX_qgHeiQfFQQY5XLqQF5yy-HRer8Mxvokc", "story", "GalacticCluster", "GALACTIC_CLUSTER", "shape_pc_y", "Y coordinate of the shape of the cluster in parsecs", ""),
("i3955pbgcwTOMsulX0CDAWO90XFTfEyJmFm-iGVv8hI", "story", "GalacticCluster", "GALACTIC_CLUSTER", "shape_pc_z", "Z coordinate of the shape of the cluster in parsecs", ""),
("xfxO086iHMqIht4nc0UDynBHD-xqcXoxTQYZDZutytw", "story", "GalacticCluster", "GALACTIC_CLUSTER", "shape_axes_a", "Length of the major axis of the cluster in parsecs", ""),
("xoN2S8CqD9ufTIGBA9A4wsVBNmHwiRUlH2_0oFh-kG4", "story", "GalacticCluster", "GALACTIC_CLUSTER", "shape_axes_b", "Length of the minor axis of the cluster in parsecs", ""),
("7m0ZoPmtastHpbtWuGdPZTaIgSe9W32LnyeGGjmb8wI", "story", "GalacticCluster", "GALACTIC_CLUSTER", "shape_axes_c", "Length of the tertiary axis of the cluster in parsecs", ""),
("g_chgcxxyKzyn-aTW6eI79ybL8Cgi8EBW-efVPWLb1E", "story", "GalacticCluster", "GALACTIC_CLUSTER", "shape_rot_pitch", "Pitch rotation of the cluster in degrees", ""),
("XNGqmSMv4DziQNm40mXzTQvSmd0uevXvNTvDPPqDGBw", "story", "GalacticCluster", "GALACTIC_CLUSTER", "shape_rot_yaw", "Yaw rotation of the cluster in degrees", ""),
("jSLfXDQj7jxgVTHSIxwGQSrPAzr7RAhYz3IUY4biwZA", "story", "GalacticCluster", "GALACTIC_CLUSTER", "shape_rot_roll", "Roll rotation of the cluster in degrees", ""),
("vWmU9k8VNaZhVD6FPLTYfNP3qbW7KchkYFtkmGKtsNM", "story", "GalacticCluster", "GALACTIC_CLUSTER", "volume_pc3", "Volume of the cluster in parsecs cubed", ""),
("gzopnabl-hVi0mKjjTKBHXseT9bQEK2Mi4GxIqt9ZOQ", "story", "GalacticCluster", "GALACTIC_CLUSTER", "mass_kg", "Mass of the cluster in kilograms", ""),
("lizlNy7A89VfCVdjQ3AC-fqtX8SfMdG4k0qp-ZX35iE", "story", "GalacticCluster", "GALACTIC_CLUSTER", "dark_energy_kg", "Amount of dark energy in the cluster in kilograms", ""),
("Cykx5O3WUpPQ6-qrG1K6FqEnPRb6AlA3D_YrauFm-Mw", "story", "GalacticCluster", "GALACTIC_CLUSTER", "dark_matter_kg", "Amount of dark matter in the cluster in kilograms", ""),
("lqGKY-5GxYEcrwPlXLe7Jj0G9N4RJV_M1cvDZj6fl5w", "story", "GalacticCluster", "GALACTIC_CLUSTER", "baryonic_matter_kg", "Amount of baryonic matter in the cluster in kilograms", ""),
("JY2mXENxoHrmFqCCyvBfPckit987cB5Khlf3fWLBUyE", "story", "GalacticCluster", "GALACTIC_CLUSTER", "timing_pulsar_pulse_per_ms", "Timing of the pulsar pulse in milliseconds", ""),
("_ebnk3kZSoDB2bWi-BUmOFH-iFI3wyX76HeK6RW3uZ8", "story", "GalacticCluster", "GALACTIC_CLUSTER", "timing_pulsar_loc_gly_x", "X coordinate of the pulsar location in gigalightyears", ""),
("3JMSwQcKNsMTv856EWmD6JTa_qjKEHBtyXWmLVHOThU", "story", "GalacticCluster", "GALACTIC_CLUSTER", "timing_pulsar_loc_gly_y", "Y coordinate of the pulsar location in gigalightyears", ""),
("P9uPIG-cBMHR74sOiwDJsOWnu5tX-YTSPV6_m5qkWAM", "story", "GalacticCluster", "GALACTIC_CLUSTER", "timing_pulsar_loc_gly_z", "Z coordinate of the pulsar location in gigalightyears", ""),
("NUj2E3RTBbR9FQVhqqY5jJWUjuHdR-018IDYGxUGSBw", "story", "GalacticCluster", "GALACTIC_CLUSTER", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("Nv7omFov0XbSKePWtUZefDDjgDe_uq_V1V69kLWriR8", "story", "Galaxy", "GALAXY", "galaxy_uid_pk", "Primary key, unique identifier for each galaxy", ""),
("WGrLoo04aNLzt4kH49S1ei09bwDnBPLg6uN07qDGczA", "story", "Galaxy", "GALAXY", "galactic_cluster_uid_fk", "Foreign key linking to the Galactic Cluster table", ""),
("5gcnAKkcD7tv_Hf-9ZdIcrPA1mNoof6DhT-gIr0rQNY", "story", "Galaxy", "GALAXY", "galaxy_name", "Name of the galaxy", ""),
("EebVW0bTkJW2fYeqNyoX7QTI_u8mwuQxiX_RLmK2rjA", "story", "Galaxy", "GALAXY", "relative_size", "Relative size of the galaxy, default is medium", ""),
("TyW2rygNY-fMulvqVslhsJaskmRTIM3-vmd1RcBM8e0", "story", "Galaxy", "GALAXY", "center_from_univ_center_kpc_x", "X coordinate of the center of the galaxy in kiloparsecs", ""),
("O589BlYdbV8OH36eh8xCJuWoFtk63lW1AUkvUvDrFFM", "story", "Galaxy", "GALAXY", "center_from_univ_center_kpc_y", "Y coordinate of the center of the galaxy in kiloparsecs", ""),
("p-Y0kBaCCD997igKLMqfmijAZ4OrvJcIwps_vPry7_k", "story", "Galaxy", "GALAXY", "center_from_univ_center_kpc_z", "Z coordinate of the center of the galaxy in kiloparsecs", ""),
("LROVVWvaieGM0d6-QTpxW5DxBQPDr-l0tLtePWll4sU", "story", "Galaxy", "GALAXY", "halo_radius_pc", "Radius of the halo of the galaxy in parsecs", ""),
("8of1-mEiizusCo58pvEwHGpqYTVz1fy_x3GFKttA1S8", "story", "Galaxy", "GALAXY", "boundary_pc_x", "X coordinate of the boundary of the galaxy in parsecs", ""),
("lmXZF4aPhu0aKc63Z5JB7j6BiMPFlKscvHvT3XexHPU", "story", "Galaxy", "GALAXY", "boundary_pc_y", "Y coordinate of the boundary of the galaxy in parsecs", ""),
("jyMRlEZZuhFxo2Yv2I6BsTI-W7H9vMr7YaH2-bejGc8", "story", "Galaxy", "GALAXY", "boundary_pc_z", "Z coordinate of the boundary of the galaxy in parsecs", ""),
("O8kpRwFLLi4j9vtCWRpb8qLat92EgplO7PqwbFnXnN8", "story", "Galaxy", "GALAXY", "volume_gpc3", "Volume of the galaxy in gigaparsecs cubed", ""),
("fCkcV9EDzklkoL99-P2zFBOdH5fYimPquTo0DKX7yew", "story", "Galaxy", "GALAXY", "mass_kg", "Mass of the galaxy in kilograms", ""),
("fefH8iyrjqnPpNhoqtRGxL1_9uRiv95toZd5JM8uZio", "story", "Galaxy", "GALAXY", "bulge_shape", "Shape of the bulge of the galaxy, default is ellipsoid", ""),
("oIFUclr1v0i4U8Ul46jDP-nNEPrVH1rDo6DGkLahHsw", "story", "Galaxy", "GALAXY", "bulge_center_from_center_ly_x", "X coordinate of the center of the bulge", ""),
("W3tIjULqAw5tK61EzS26U4rTp3hMapVSyr9mzvhPJk8", "story", "Galaxy", "GALAXY", "bulge_center_from_center_ly_y", "Y coordinate of the center of the bulge", ""),
("Ao4ZktL9kaCX0hgKUgZFUUMkMvFYnOEGHUm3PC8zEhM", "story", "Galaxy", "GALAXY", "bulge_center_from_center_ly_z", "Z coordinate of the center of the bulge", ""),
("U56Ep9eUWLRJRX222fu6FsJs0pDzCfswgO-lChFHQMU", "story", "Galaxy", "GALAXY", "bulge_dim_axes_a", "Length of the major axis of the bulge in lightyears", ""),
("22yGrZiXONR6IgqP1Pal7-NCuD7PfoLNwUkQnGD_lk4", "story", "Galaxy", "GALAXY", "bulge_dim_axes_b", "Length of the minor axis of the bulge in lightyears", ""),
("Nt_Si219egG9ak1ApxEWaApm7TImr2kfqhcf1tJOjdI", "story", "Galaxy", "GALAXY", "bulge_dim_axes_c", "Length of the tertiary axis of the bulge in lightyears", ""),
("aXtx7kkCiLemEovYlCqzvJTssEnZiIaY4uUP0UH9TOM", "story", "Galaxy", "GALAXY", "bulge_dim_rot_pitch", "Pitch rotation of the bulge in degrees", ""),
("M2q0qDIGgsyUNtAduLXzbCGasKDOGem8umE2XASJKmQ", "story", "Galaxy", "GALAXY", "bulge_dim_rot_yaw", "Yaw rotation of the bulge in degrees", ""),
("Pt5YZAET69o58CKq2q68ErqJxDxLOxcfGyYMDlGrf0c", "story", "Galaxy", "GALAXY", "bulge_dim_rot_roll", "Roll rotation of the bulge in degrees", ""),
("uI-RJ-__HGr_wzHplyMpaGxACp_itqUhfuWhASUGTdU", "story", "Galaxy", "GALAXY", "bulge_black_hole_mass_kg", "Mass of the black hole in the bulge in kilograms", ""),
("xS7Zic-GzLFWPFjrxOPrNDgr_OrylcKgWNZ9jb35QSY", "story", "Galaxy", "GALAXY", "bulge_volume_ly3", "Volume of the bulge in lightyears cubed", ""),
("qUPAwF3GFNLtzc5kqKoQ6PMdXtPG4pg5y0JGWPjaryI", "story", "Galaxy", "GALAXY", "bulge_total_mass_kg", "Total mass of the bulge in kilograms", ""),
("cni7tHT8igoNWqX4vOd-RENDKNke3pRbQ1V8X4kTt5A", "story", "Galaxy", "GALAXY", "star_field_shape", "Shape of the star field of the galaxy, default is ellipsoid", ""),
("IDPyRvqcLvCxNyXI5FWlQFns5jsOZ6esrVw61-j2OzY", "story", "Galaxy", "GALAXY", "star_field_dim_from_center_ly_x", "X coordinate of the center of the star field", ""),
("CKU-65337OkQxFzJQEZ-oJ4Y4YXHBWi9ByCrSG-l_C8", "story", "Galaxy", "GALAXY", "star_field_dim_from_center_ly_y", "Y coordinate of the center of the star field", ""),
("VRz0xASoT0BrUz1BW0B-sbhYyktOZrX1CMTo2-SVBOM", "story", "Galaxy", "GALAXY", "star_field_dim_from_center_ly_z", "Z coordinate of the center of the star field", ""),
("x5nc6YUn9hp_wYDoDRQCFMexAz5tBAgvaIv1OM_OoS4", "story", "Galaxy", "GALAXY", "star_field_dim_axes_a", "Length of the major axis of the star field in lightyears", ""),
("aNdYp9YWvJcaW_HZul_ie3OjXR4DDQN9WP8kVHnB-_U", "story", "Galaxy", "GALAXY", "star_field_dim_axes_b", "Length of the minor axis of the star field in lightyears", ""),
("qZrAhwiDiKXlA6EJfzCEdIOVxjKCCke022IxOBh42TI", "story", "Galaxy", "GALAXY", "star_field_dim_axes_c", "Length of the tertiary axis of the star field in lightyears", ""),
("GpiKHDlwPtGnD6jkP1hiQSwbxhfiLA46SG7pahufjao", "story", "Galaxy", "GALAXY", "star_field_dim_rot_pitch", "Pitch rotation of the star field in degrees", ""),
("It6qkotkxGmuFlF2Xpwt694fIryUMZasp_gBKver9U8", "story", "Galaxy", "GALAXY", "star_field_dim_rot_yaw", "Yaw rotation of the star field in degrees", ""),
("3T7PO88OI-_hq1S6CSNWyGRzzai2Bk44ofSQf4PT5ts", "story", "Galaxy", "GALAXY", "star_field_dim_rot_roll", "Roll rotation of the star field in degrees", ""),
("2GS82b2WrKTAUwTxylNcFbKVkelKinCTtJ1dFB_fIlI", "story", "Galaxy", "GALAXY", "star_field_vol_ly3", "Volume of the star field in lightyears cubed", ""),
("NcqhYOAav7bgpaS9oX95SsnBMtzaeanPn8VywPQJ2_g", "story", "Galaxy", "GALAXY", "star_field_mass_kg", "Mass of the star field in kilograms", ""),
("pl-RHKCB5tszKjPj7xKGunLKIeN2eyZRKVnudqRahyc", "story", "Galaxy", "GALAXY", "interstellar_mass_kg", "Mass of", ""),
("h4jodgkBe2SlPd_cQLZb5Y0AmWnnXJ9PbyTV5LT88Cg", "story", "Galaxy", "GALAXY", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("QkD0lKFsmS65eBeV6Nj4u0iDPc_E_qURWu9SG5QD0sE", "story", "StarSystem", "STAR_SYSTEM", "star_system_uid_pk", "Primary key, unique identifier for each star system", ""),
("VyIlunpOO_PBsT34Hws6zJCUlBRHlnmWK8kJ-9mdpGE", "story", "StarSystem", "STAR_SYSTEM", "galaxy_uid_fk", "Foreign key linking to the Galaxy table", ""),
("8YUACOcPUcWuDaeKT2yKs52h-lJx9W8yShNA3acVjQA", "story", "StarSystem", "STAR_SYSTEM", "star_system_name", "Name of the star system", ""),
("vwGZ67B39fDDo89o-zah28z9xE1KNMltcfZTFYANzJo", "story", "StarSystem", "STAR_SYSTEM", "is_black_hole", "Indicates if the star system contains a black hole", ""),
("yEgLOnbQBjmsN7HHr65iNWtIwmx-kJemx7PAWa_7JIs", "story", "StarSystem", "STAR_SYSTEM", "is_pulsar", "Indicates if the star system contains a pulsar", ""),
("JG75sz7bjzZ7Kf6m9cp29-EQV_7H5YcQh6jXjPIiPcQ", "story", "StarSystem", "STAR_SYSTEM", "boundary_pc_x", "X coordinate of the boundary of the star system in parsecs", ""),
("_5pjnxL_UQBpISV4VNfPVIg9jUpC5M36ImyMkvKvRIs", "story", "StarSystem", "STAR_SYSTEM", "boundary_pc_y", "Y coordinate of the boundary of the star system in parsecs", ""),
("ib-KWv8MpT_-IDsCvFM1mWO5z6X1qem907NL2BbNqUo", "story", "StarSystem", "STAR_SYSTEM", "boundary_pc_z", "Z coordinate of the boundary of the star system in parsecs", ""),
("uIi9G4QPR189dcV5JCrhsi1ViTUFORcPm1zUtGjNdW8", "story", "StarSystem", "STAR_SYSTEM", "volume_pc3", "Volume of the star system in parsecs cubed", ""),
("a4K1YPDcFFPpYwSruc1WbnsxvxfKLWiukeL6gdZ6wMQ", "story", "StarSystem", "STAR_SYSTEM", "mass_kg", "Mass of the star system in kilograms", ""),
("MFKKeUsLKI-futWNMhWCT3yL7-vHK16Hb4fJelXx7ck", "story", "StarSystem", "STAR_SYSTEM", "system_shape", "Shape of the star system, default is ellipsoid", ""),
("ccUVqS9mLLSbW5N-krrktPc-ZcPK9lpD72xoyBuwirk", "story", "StarSystem", "STAR_SYSTEM", "center_from_galaxy_center_pc_x", "X coordinate of the center of the star system", ""),
("Igb9fghLRWmdWAA-As_-QYirkQuiz4KHVn3270IWb2U", "story", "StarSystem", "STAR_SYSTEM", "center_from_galaxy_center_pc_y", "Y coordinate of the center of the star system", ""),
("W_Gus2laPGJ59JZe5DeQWqX2Ef2sZE81Ufhjt2BP5HI", "story", "StarSystem", "STAR_SYSTEM", "center_from_galaxy_center_pc_z", "Z coordinate of the center of the star system", ""),
("Ud0RpoVmmLgfuGUKlQcehakY7hnvLNJg40_ays5kKpM", "story", "StarSystem", "STAR_SYSTEM", "system_dim_axes_a", "Length of the major axis of the star system in parsecs", ""),
("N7obm0E4i7_LBNnNssy3z3SKuz6ITX-uirnaRm1FkQc", "story", "StarSystem", "STAR_SYSTEM", "system_dim_axes_b", "Length of the minor axis of the star system in parsecs", ""),
("0nOP3IWCz9C1aP8aQobmBrqvm0d4zCGVV77XzLv5omI", "story", "StarSystem", "STAR_SYSTEM", "system_dim_axes_c", "Length of the tertiary axis of the star system in parsecs", ""),
("Riyaszjk9SQKAl_zL5ep1dmpvbaQuKoWP6uBqKu1f8I", "story", "StarSystem", "STAR_SYSTEM", "system_dim_rot_pitch", "Pitch rotation of the star system in degrees", ""),
("tfJ2nyWVmCkS4r6qyTvSyOFGHsVliL1xNUPjeHfXyQE", "story", "StarSystem", "STAR_SYSTEM", "system_dim_rot_yaw", "Yaw rotation of the star system in degrees", ""),
("1ApVCe5kGFKSblxGE4qg0T8loLgS53w8I9O80Di3oAc", "story", "StarSystem", "STAR_SYSTEM", "system_dim_rot_roll", "Roll rotation of the star system in degrees", ""),
("T_cw-dXNcj2g1GJWajge-CNAJTIhnbwoMZJRYLynAX8", "story", "StarSystem", "STAR_SYSTEM", "relative_size", "Relative size of the star system, default is medium", ""),
("_iDnMy9oPj65bSWkF2x1WZ9kFKKFIu7OHFLDCHNNPDk", "story", "StarSystem", "STAR_SYSTEM", "spectral_class", "Spectral class of the star, default is G", ""),
("VHdpaJmJ5OBRMkyj3fDBcNsAab8Q5oxAC_pIMlyhv00", "story", "StarSystem", "STAR_SYSTEM", "aprox_age_gyr", "Approximate age of the star system in gigayears", ""),
("BeX_OS4NNHGEWGRcewUudrVyLLAhLGpBg6pruF_ysy4", "story", "StarSystem", "STAR_SYSTEM", "luminosity_class", "Luminosity class of the star, default is V", ""),
("HIHAJmS2RMyak58NLXajuQBr0nubpfsXFC-Tr5gqmM8", "story", "StarSystem", "STAR_SYSTEM", "frequency_of_flares", "Frequency of solar flares, default is rare", ""),
("kvynXJLECdjyfmteMadrf9S8Y34Vwz06GD1PTm4iJ9o", "story", "StarSystem", "STAR_SYSTEM", "intensity_of_flares", "Intensity of solar flares, default is low", ""),
("qPbKG4a3aSZ7XBScCXq6BRFvolV_MqG3agEkOVSjctU", "story", "StarSystem", "STAR_SYSTEM", "frequency_of_comets", "Frequency of comets, default is rare", ""),
("MRpZxif3m9OG7OVQwEsR4URtG2THKA0lkEUZ0uK1wU4", "story", "StarSystem", "STAR_SYSTEM", "unbound_planets_cnt", "Number of unbound planets in the star system", ""),
("ZruC4GlaaCWA1o42IkUfBq31InQ6ISJJ-5LHRMlz0rs", "story", "StarSystem", "STAR_SYSTEM", "orbiting_planets_cnt", "Number of planets orbiting the star", ""),
("1fqHJ4EU1osfBk4Jz4m_G0RmE1klMeEKfpklVhExnsk", "story", "StarSystem", "STAR_SYSTEM", "inner_habitable_boundary_au", "Inner boundary of the habitable zone in astronomical units", ""),
("sKJ1ac2ZMSlGPvxkNYXh3fg1-1q6BIX8zfKGU9j1pt8", "story", "StarSystem", "STAR_SYSTEM", "outer_habitable_boundary_au", "Outer boundary of the habitable zone in astronomical units", ""),
("zf0iNL9qkYDDkBQosBdmMTrTCRf9EWGwyd3flL3AsIQ", "story", "StarSystem", "STAR_SYSTEM", "planetary_orbits_shape", "Shape of the planetary orbits, default is circular", ""),
("OCOjD4JRzCk6i2PcaT9KQdwJcRPn-MpPkrJ3-zvEfMM", "story", "StarSystem", "STAR_SYSTEM", "orbital_stability", "Stability of the planetary orbits, default is stable", ""),
("9qSyROzh5pbwEKqd6rFh8wopWMhmXZKnAy-h-rTaKSs", "story", "StarSystem", "STAR_SYSTEM", "asteroid_belt_density", "Density of the asteroid belt, default is sparse", ""),
("JriXHjnv-GZP-wlTYKfYmCiCtNDbJBrmBUjFRCXKMac", "story", "StarSystem", "STAR_SYSTEM", "asteroid_belt_loc", "Location of the asteroid belt, default is inner", ""),
("Qm83YGUP8MB1mg2U6PvKoA1W1eDduP2pouOGbrPTB_k", "story", "StarSystem", "STAR_SYSTEM", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("IrldnuUnyDd90lA7HOcBkvdEReNByxBUloJUZaxPpk0", "story", "World", "WORLD", "world_uid_pk", "Primary key, unique identifier for each world", ""),
("ZzcK8qrNElsvXiL6-MT77wHBbG9dgWNzS9Texsx-hq4", "story", "World", "WORLD", "star_system_uid_fk", "Foreign key referencing the Star System table", ""),
("0TBzGdA1Lon6xiwL33iixs8ECf0A6INJA0qlty609co", "story", "World", "WORLD", "world_name", "Name of the world", ""),
("45ClXsjeABAibAnun_ytG09D-D9lHE93RUVEk3txvzg", "story", "World", "WORLD", "world_type", "Type of the world, default is habitable", ""),
("MDgJPF93GeISWnQ43PyC6IVpvPphvMHERYxEqiPG0n0", "story", "World", "WORLD", "obliquity_dg", "Axial tilt of the world in degrees", ""),
("g-GZGdQ4Vd98Lc3A5Q-hs_HLs1uIQCpv_DE69tGKGeU", "story", "World", "WORLD", "distance_from_star_au", "Distance from the star in astronomical units", ""),
("-NIn9erOP1FFukElsGPbQ-vf1FooySuRoRHwGMSbFOU", "story", "World", "WORLD", "distance_from_star_km", "Distance from the star in kilometers", ""),
("UiKU-4XWGeArDFTj1MDq0BUQAScDiTT3OCUbBmgWcr4", "story", "World", "WORLD", "radius_km", "Radius of the world in kilometers", ""),
("PCfHlb-HOKvRe3tgrrP6qIrf7TUME1oWI-FdzIafvPU", "story", "World", "WORLD", "mass_kg", "Mass of the world in kilograms", ""),
("ZnOCl10-7bFC5l8XsgUepXpXFRs_vMhI7VitdlvmQyw", "story", "World", "WORLD", "gravity_m_per_s_per_s", "Gravity of the world in meters per second squared", ""),
("8HC5YVBfk-9-WZNyWRGEFVhWgJOFRivl_joZj1HoEi0", "story", "World", "WORLD", "orbit_gdy", "Orbital period of the world in galactic days", ""),
("tA-be-yMxAaKN6WbxYNylnBceEkhgBDIe2WjZsbxHNw", "story", "World", "WORLD", "orbit_gyr", "Orbital period of the world in galactic years", ""),
("ThLXv-kQGbApER7q6AKfI4zkxr52tI9YsI0XroMsGs4", "story", "World", "WORLD", "is_tidally_locked", "Indicates if the world is tidally locked", ""),
("9kd6Sbf_9-BIHXcdmVhqku2tMqGmEW4gpkZvkmUvGyM", "story", "World", "WORLD", "rotation_gdy", "Rotation period of the world in galactic days", ""),
("G6n8788lhKvOMh_czpXkXAj2ag6tPhczrNdY4yk8Tus", "story", "World", "WORLD", "rotation_direction", "Direction of rotation, default is prograde", ""),
("yn8zZw4KOqFHHgAXWJLb_ypiprIgXHwHo4yjEav29Ts", "story", "World", "WORLD", "orbit_direction", "Direction of orbit, default is prograde", ""),
("RusmdI82GbOw7DeoPj63Sj8Cv3jZW0uUGrUVRwH6dLw", "story", "World", "WORLD", "moons_cnt", "Number of moons orbiting the world", ""),
("yJZEoJSV9QIh0cvjQSkdQqVOFG7miL1NpHzNEBCW9AE", "story", "World", "WORLD", "world_desc", "Description of the world", ""),
("6P8eulvEI9Tpl2yvN8IyMGHhR5YzKms5AHVLcaEtlXE", "story", "World", "WORLD", "atmosphere", "Composition of the atmosphere", ""),
("EczXRqdDzXXiAs7q2MYzYy1ErUbFMOdEfk0eh8Jgo2o", "story", "World", "WORLD", "sky_color", "Color of the sky", ""),
("0ZdHPHmQFHOxbdTWzUngkjdsENa_ArtBY9_WJ0IdBQk", "story", "World", "WORLD", "biosphere", "Presence of life forms", ""),
("D_Y2BFkLFJZknXiDgPbHHccPudd3XOWWGhvj29PawxA", "story", "World", "WORLD", "sentients", "Presence of intelligent life", ""),
("fq0k8TV_tTc6n-rrz7oeMsH0wCpsB6EcRUk1sTkT6us", "story", "World", "WORLD", "climate", "Climate of the world", ""),
("auTgJxRClwNqaPBKGurN97XvLyzjv4hAPCiZI1MV8KI", "story", "World", "WORLD", "tech_level", "Technological level of the world", ""),
("jcI3cBunxAlcvMa1_u7IGAr_UNEy0ai2BD5PCETwnzY", "story", "World", "WORLD", "terrain", "Terrain of the world", ""),
("qu_uYylGvNb02c9ql-484N-W_x2qquawR8FIf5vi4MY", "story", "World", "WORLD", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("-Qv9M-1-o8zN0DB24Xv-H2GanHfFSG5WCMhaoUEoTi8", "story", "Moon", "MOON", "moon_uid_pk", "Primary key, unique identifier for each moon", ""),
("gQTsRCjaNa56KSWj6-qTDe1lCIVrP8ocwLI04OET0P4", "story", "Moon", "MOON", "world_uid_fk", "Foreign key referencing the World table", ""),
("vMJyXECXOqbpF0n7ybjxv9pRFBgHwkddOKGdMpnjiM0", "story", "Moon", "MOON", "moon_name", "Name of the moon in Common language glossary", ""),
("wEliLYxhazboxSJQcdbe-nVeyNkcA_h-hCWjZItpqwM", "story", "Moon", "MOON", "moon_desc", "Description of the moon", ""),
("KrzWYaZdOrw1tLtbcicSMDC9c-Rf7BhxfjLLhYmLP28", "story", "Moon", "MOON", "moon_lore", "Lore of the moon", ""),
("tFfrqEfQ9eQQdhFHgwzr8gSRaQCY9eoTyH94eX3nBgY", "story", "Moon", "MOON", "center_from_world_center_km", "Distance from the center of the world in kilometers", ""),
("yK8_LGcc3XSwxI8KljH_eEOygITXsZF98Ix0rvgekWY", "story", "Moon", "MOON", "mass_kg", "Mass of the moon in kilograms", ""),
("aANNWQ0R6G82oNQmmjjUVJnYBgIFzX3ddJZh1X6hS04", "story", "Moon", "MOON", "radius_km", "Radius of the moon in kilometers", ""),
("AiGAT7Mv5pWb6P1Ve-SImlTjY_UzUgaHgAevoMBJtZo", "story", "Moon", "MOON", "obliquity_dg", "Axial tilt of the moon in degrees", ""),
("MiIRGbbtEy76t0AGiP7rJTYQZW2rQqocxJTySGQg1L8", "story", "Moon", "MOON", "is_tidally_locked", "Indicates if the moon is tidally locked", ""),
("jhX_sPVSo6OrtOj8JMvULGtT6P4NwG2jXNbFNxJE3oc", "story", "Moon", "MOON", "rotation_direction", "Direction of rotation, default is prograde", ""),
("VIE6VFAedXjGgomOV3-W9l_wBBORYfiVWIhrtLPwz24", "story", "Moon", "MOON", "orbit_direction", "Direction of orbit, default is prograde", ""),
("nbdnHeopl1ZnUB2mN__aYLqyFTB1vnypRjrX1kDo7G4", "story", "Moon", "MOON", "orbit_world_days", "Orbital period of the moon in world days", ""),
("O3zxRHFU_j1lXOpTYGBYekYe87HGDtp_ZsvsF3A8oiI", "story", "Moon", "MOON", "rotation_world_days", "Rotation period of the moon in world days", ""),
("R1JAxbw4iBmSw0n-BNAMlbJ_pWglGYAzOUfk7hZLELc", "story", "Moon", "MOON", "initial_velocity", "Initial velocity of the moon in meters per second", ""),
("WMRrUN3yHFz8q8DNczepOmURNA8YhDiDab17xq9j8L4", "story", "Moon", "MOON", "angular_velocity", "Angular velocity of the moon in radians per second", ""),
("hYE7k_I1nPzIvxQdaPP7APYWRdwsn4c6eHlZxOpaj9M", "story", "Moon", "MOON", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("wJhM6SY-nyufajIQq5g-AbOtoHEoE4RZZcx5yM6MHf8", "story", "Lake", "LAKE", "lake_uid_pk", "Primary key, unique identifier for each lake", ""),
("jF4Yg0Z1u1bR0BjjyjzipcHuVr7jXZJ85OPso75IxbY", "story", "Lake", "LAKE", "gloss_common_uid_vfk", "Foreign key linking to the Common Glossary table", ""),
("VFmnV1wDg9YSb9hUEHBDAuldiuJP8m2oVHTjCorTFkg", "story", "Lake", "LAKE", "lake_name", "Name of the lake", ""),
("5h1T2RgFmdPkP9RWSTc6nOTxriElV45WAlPdyCJbi8o", "story", "Lake", "LAKE", "lake_shoreline_points_json", "JSON of the lake shoreline points", ""),
("RwDRTJvchPLH9sFhs22NvmvyiA3r1Wi50hGPFS_PSHw", "story", "Lake", "LAKE", "lake_size", "Size of the lake", ""),
("XMQ4UpMdkjIZoQ2n7bib5BEs5okaDjc7337FEiXZe98", "story", "Lake", "LAKE", "water_type", "Type of water", ""),
("dK8px1VyWMXDirI5KHxJm3lesdS-YHS7BbDg1oJgmfw", "story", "Lake", "LAKE", "lake_type", "Type of lake", ""),
("7RIFtSfyhCAO7RbsBa5-nJMW8oIP8mZVXJn4LOQQZBk", "story", "Lake", "LAKE", "is_tidal_influence", "Indicates if the lake has tidal influence", ""),
("-92HW-4XIZ0rxfiIrh3nNSGFh35IkXk_xjKwQa1_d78", "story", "Lake", "LAKE", "lake_surface_m2", "Surface area of the lake", ""),
("992YzIkYsYnNkUOe-VsWZSFKEByJIrNm7TdK64bkJ-M", "story", "Lake", "LAKE", "max_depth_m", "Maximum depth of the lake", ""),
("-48iXa8lTMk2yh8flXBSMc7LHURXHHzU4-9qeErlBOQ", "story", "Lake", "LAKE", "avg_depth_m", "Average depth of the lake", ""),
("vrhFai4dBQdeeszF5PyPhXumrvFhTOiCPf0zpbdn6Lo", "story", "Lake", "LAKE", "lake_altitude_m", "Altitude of the lake", ""),
("ZnHUuNlGP9E0soVtwf1D9q1u45nWuqNBWlBJoPLZyw4", "story", "Lake", "LAKE", "catchment_area_radius_m", "Catchment area radius of the lake", ""),
("m9LUPsY5RuC-gUtNrRAL_3Qp0uruc3bBpnSpPG5j1q0", "story", "Lake", "LAKE", "lake_origin", "Origin of the lake", ""),
("CTQKTC9PjAIYbNF_9ZUpH37kxhxV9OHaiDRLVSlDxiI", "story", "Lake", "LAKE", "flora_and_fauna", "Flora and fauna of the lake", ""),
("8Oga_x_tCnpyTEYH3_TmOMx74HFXGGZRWlGoOTavwyc", "story", "Lake", "LAKE", "water_color", "Color of the water", ""),
("WpQnS5MtidYhp4389enGq33RA63Rh25Ao82D2qzqLDg", "story", "Lake", "LAKE", "accessibility", "Accessibility of the lake", ""),
("8e4L2LRpYmz9DCYqYiIHpbTT1Xt6CTCgnPLYv_tAtZ8", "story", "Lake", "LAKE", "special_features", "Special features of the lake", ""),
("yOG-IXW14smbSk2pqJKZY3ztYdLigdioIFqcMvtPpO8", "story", "Lake", "LAKE", "lake_usage", "Usage of the lake", ""),
("ycM2voLyim85RSn41T3hdjb-wDcdkLZBlJAGNUDahKA", "story", "Lake", "LAKE", "lake_lore", "Legends or myths of the lake", ""),
("YoULDFYl38Unm0ruVsb8-D_apQo2LmDTD-hVB-qq3qA", "story", "Lake", "LAKE", "lake_history", "History of the lake", ""),
("yjIAx3pMy_u8tIhtzdP4mIL7R1aoRBKA9id7EpQ3f58", "story", "Lake", "LAKE", "conservation_status", "Conservation status of the lake", ""),
("zRVcif-u7450ogQBbOi-x5yXzcVVFuldbgN4gHtoX3I", "story", "Lake", "LAKE", "current_conditions", "Current conditions of the lake", ""),
("2586YLy4HdvgIgpenQiDNsaYVC_Bm3c35ZVLYaPuS2w", "story", "Lake", "LAKE", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("QDF2dOvZHgLbMlUMXQg5JK5SMFfIjOBP3wKA6oEmxK0", "story", "River", "RIVER", "river_uid_pk", "Primary key, unique identifier for each river", ""),
("-9F44dx83nkW50YtX_Vjfgar3EEvMXD5Mj4YjBdB94A", "story", "River", "RIVER", "gloss_common_uid_vfk", "Foreign key linking to the Common Glossary table", ""),
("NGaRUISud3oQiJpItoJyn6Rbj1E-li8DgzTWRhpp18M", "story", "River", "RIVER", "river_name", "Name of the river", ""),
("mFsAqNQZJHPgxdK1-jt5fBX7UEEwJT6OK5SvWvaRxzE", "story", "River", "RIVER", "river_course_points_json", "JSON of the river course points", ""),
("BVz0fTfhjsNO_ClwGQUSt4LARmLUsHVYdw2DvDCuPZI", "story", "River", "RIVER", "river_bank_points_json", "JSON of the river bank points", ""),
("RbYtDZfFjYh6ufmH7FXbCN0IsKLAv_6m8eJOaNEDefA", "story", "River", "RIVER", "river_type", "Type of river", ""),
("FUwllB4VZEP3A4AIMAto81lbsrg2_N-hbT6SlXYPa7Y", "story", "River", "RIVER", "avg_width_m", "Average width of the river", ""),
("G2CR3R_c9wV_SoSk1LTTYmdXmrpMbRfjb36Z3CBTvwk", "story", "River", "RIVER", "avg_depth_m", "Average depth of the river", ""),
("6vXAfntrwrLR8owdaC8lV1ATrZbYMHn-0kM7H_dVPrc", "story", "River", "RIVER", "total_length_km", "Total length of the river", ""),
("lUPuPZg0sAiVpv5_JS58gCYgz9dDCNbxHJx1vHJ8vdE", "story", "River", "RIVER", "drainage_basin_km", "Drainage basin of the river", ""),
("Mv_2wxhFoFVG0mKcFpVMzldjNnjaiFI-xN6WOZf08kY", "story", "River", "RIVER", "avg_velocity_m_per_h", "Average velocity of the river", ""),
("UF7i4qCF1B54NSsEJl_GQXJ2vOmyrfoXwS3zw6HzGB0", "story", "River", "RIVER", "gradient_m_per_km", "Gradient of the river", ""),
("F3JFUJBt8I18SAUHfpaSUOpZfGVosMOgKww9S6VDirU", "story", "River", "RIVER", "river_hazards_json", "JSON of the river hazards", ""),
("XqzLg3u0eugf53WJ4kQU8SSKxPFVGTSAvvCCln-nA8g", "story", "River", "RIVER", "river_features_json", "JSON of the river features", ""),
("xmRGH_RAXmz4xghVdS76LskIIFqR8npQ36Yv-_e_5Ys", "story", "River", "RIVER", "river_nav_type", "Type of river navigation", ""),
("ZVRoNGuzHFYt8DeXqFQ2pMMbsw5whRfSu4SjxCbFDYE", "story", "River", "RIVER", "flora_and_fauna", "Flora and fauna of the river", ""),
("o9qYz9VwoXLszqAPmfgZY5ER9fXgaPPQ1263dRdqeao", "story", "River", "RIVER", "water_quality", "Quality of the water", ""),
("gmjPXbTwDNHbDdpy7cndFX3RS50sqLPue0xp2Fqa29c", "story", "River", "RIVER", "historical_events", "Historical events of the river", ""),
("eaum9EvEka618_jBGPkWcBYyIeReohS6z_rELYwiKdQ", "story", "River", "RIVER", "current_conditions", "Current conditions of the river", ""),
("a873-HsIBt5x4KXGkjWhsb2s0vHnZn5FoN1CMKrOB-A", "story", "River", "RIVER", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("jXYs1VfLg5-DibKl1mE4SAWHoIoxfZu6_9tUcOJ69w4", "story", "OceanBody", "OCEAN_BODY", "ocean_body_uid_pk", "Primary key, unique identifier for each ocean body", ""),
("_K6eeLwDeFHqXGUUVo2quMIUJ3edh7Fm8RB3B6QOkbA", "story", "OceanBody", "OCEAN_BODY", "gloss_common_uid_vfk", "Foreign key linking to the Common Glossary table", ""),
("OU7EpMe1mkLFFzN8Nrk-0bSx6F_Yn1bbW6rIyI0uepo", "story", "OceanBody", "OCEAN_BODY", "ocean_body_name", "Name of the ocean body", ""),
("TlrQonrenOGCDDiPWo3J3LoNLLnOc5jAjdw2EwKRCvc", "story", "OceanBody", "OCEAN_BODY", "body_shoreline_points_json", "JSON of the body shoreline points", ""),
("xSMswZnY7XkhRJxvS0l6LssElCfxOSXMJ-5hrAHGp6U", "story", "OceanBody", "OCEAN_BODY", "is_coastal", "Indicates if the body is coastal", ""),
("aPipT6ytHz_gaQz3sLEOFbDvYIDwdvrP5AVynUv9-9k", "story", "OceanBody", "OCEAN_BODY", "is_frozen", "Indicates if the body is frozen", ""),
("goEG6nMmgSiZb9oLXyqRwqqvSTs1elH0ocfNWJnrmVk", "story", "OceanBody", "OCEAN_BODY", "ocean_body_type", "Type of ocean body", ""),
("-WSBIwHCjciZ8sXO8N_qBz2nWH9ufHwo8svQyUIwxok", "story", "OceanBody", "OCEAN_BODY", "water_type", "Type of water", ""),
("KhLapJHKPwJI0xzc18YgupAvqhOUYe-cWmJ_Akggu10", "story", "OceanBody", "OCEAN_BODY", "is_tidal_influence", "Indicates if the body has tidal influence", ""),
("DFUr6RBquI1FR6cuc4G1gGYPFovg4-29NyX5-G8EDiY", "story", "OceanBody", "OCEAN_BODY", "tidal_flows_per_day", "Number of tidal flows per day", ""),
("UlaCVblUG69KKpRoBBYDqPsaiCcCwTP-QkPig4hCfLw", "story", "OceanBody", "OCEAN_BODY", "avg_high_tide_m", "Average high tide", ""),
("F-5cuYe-7uEgsbmLBm_nC1gN4B3rlLUxy8JKfWjr2KA", "story", "OceanBody", "OCEAN_BODY", "avg_low_tide_m", "Average low tide", ""),
("CjC-v0FG3ncPum6RBgUBtUroqYoq55m_FtsqATl4aqc", "story", "OceanBody", "OCEAN_BODY", "max_high_tide_m", "Maximum high tide", ""),
("3cvj8fefJzuuRCoF5FqARMarPYTwltnGSv2TncM3Z2Y", "story", "OceanBody", "OCEAN_BODY", "ocean_wave_type", "Type of ocean wave", ""),
("w6FJ5JZ8jQ4CfFHX1EK10W_kTX01cnQ_1yEZ1LuFT1Q", "story", "OceanBody", "OCEAN_BODY", "body_surface_area_m2", "Surface area of the body", ""),
("-sCgpwuqC5QvGQd8B4vxReT9JO0AbGNWObpWpl_Kyyw", "story", "OceanBody", "OCEAN_BODY", "body_surface_altitude_m", "Altitude of the body", ""),
("BFoWWzGsqYyQVwTBHx6pvVgsPyRuu67aTDyxiNWoc5I", "story", "OceanBody", "OCEAN_BODY", "max_depth_m", "Maximum depth of the body", ""),
("jhnuAnFJFPRfCXzU6gwgxgzdzxxW9-9sR_u-fOKok_o", "story", "OceanBody", "OCEAN_BODY", "avg_depth_m", "Average depth of the body", ""),
("ZIDZjiAkS3-g0-oSTFTsaJVqbyoWYGZrcoWltuMM6bQ", "story", "OceanBody", "OCEAN_BODY", "ocean_hazards_json", "JSON of the ocean hazards", ""),
("_Z3xgJkxhdZ8Rjy7PEbQOvXnyZlDdKFTfGmTEX1yOvM", "story", "OceanBody", "OCEAN_BODY", "ocean_features_json", "JSON of the ocean features", ""),
("TeN7O2srQ6QDhTPRK8I9kvmkIgCiAahC07cI0qR3Fcs", "story", "OceanBody", "OCEAN_BODY", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("G0NjWResTm3sj6lZ8hzppopqPP7al2j6EVMy8SnqRkg", "story", "LandBody", "LAND_BODY", "land_body_uid_pk", "Primary key, unique identifier for each land body", ""),
("lXlhaWEghjdID1FZK2pAJFfx_H1fURFF0vG8HSFhsgw", "story", "LandBody", "LAND_BODY", "gloss_common_uid_vfk", "Foreign key linking to the Common Glossary table", ""),
("kGAh5tmDmfyfbbkKnpHaTj0Sd3_oMC623HQCLcDyhbI", "story", "LandBody", "LAND_BODY", "land_body_name", "Name of the land body", ""),
("SyVZvYTfDs1H80Kx40xfl8Mbgbr2ftupXxP2PBPfAME", "story", "LandBody", "LAND_BODY", "body_landline_points_json", "JSON of the land body line points", ""),
("5LZ7bjWGLkmgmzfHsDlbGSM48bfaKa7rnk4VQXuXqD0", "story", "LandBody", "LAND_BODY", "land_body_type", "Type of land body", ""),
("djQCUVpNlnAXI8isGI8DPzmvBeSf6htuS4oxeTps3ag", "story", "LandBody", "LAND_BODY", "land_body_surface_area_m2", "Surface area of the land body", ""),
("GRFiNnVAti4K9wN4g9DyBCVzyoR616RF5fRKTOA5Cec", "story", "LandBody", "LAND_BODY", "land_body_surface_avg_altitude_m", "Average altitude of the land body", ""),
("4YLlRZgI5w2cvmeYNaCKgZjjRsXvsQ2jtTBeiTk-yHo", "story", "LandBody", "LAND_BODY", "max_altitude_m", "Maximum altitude of the land body", ""),
("uTRbjhuFdTIuyBeQYS42TUmQiBK1e3wkeXoqm_LpmjI", "story", "LandBody", "LAND_BODY", "min_altitude_m", "Minimum altitude of the land body", ""),
("vb5efI7AQBHP93c6BsqN98ITqlVWhScZotSuCbo_GwY", "story", "LandBody", "LAND_BODY", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("tuhqNOJXEax-IvKBxDfkC5NAfUC8ZAV2WJ5DxhmmBVg", "story", "SolarYear", "SOLAR_YEAR", "solar_year_uid_pk", "Primary key, unique identifier for each solar year", ""),
("u0uLGuBwByTHJCjV9f_lcoTg-RM_fg1IkK4Oq_9_xIk", "story", "SolarYear", "SOLAR_YEAR", "world_uid_fk", "Foreign key linking to the World table", ""),
("luH5djIfrdtRjY1qHwpsQv9AlIMGfs0Yq4zxWtxXXjE", "story", "SolarYear", "SOLAR_YEAR", "lang_uid_fk", "Foreign key linking to the Language table", ""),
("EhWpfrIHEV0pqDVGPbOPiBsIAOWQN0HnUcJKmjRDgKQ", "story", "SolarYear", "SOLAR_YEAR", "solar_year_key", "Key for the solar year", ""),
("0PM6T1izb_NSqBo9eFyCN55gDv7TXed_hFkfAqwGZdM", "story", "SolarYear", "SOLAR_YEAR", "version_id", "Version of the solar year", ""),
("3yW1F2douzqsgBnFnZId1uEZ2Nzeb_UXOeag3RUDMFI", "story", "SolarYear", "SOLAR_YEAR", "solar_year_name", "Name of the solar year", ""),
("NjehdFjGYbsI3iaYbt5yafUzbs1XHzKHOffBLrnb3D8", "story", "SolarYear", "SOLAR_YEAR", "solar_year_desc", "Description of the solar year", ""),
("aeariKaU69ehUF9Wi5AumgYWXQTqbBfgAJpyJpHN_XM", "story", "SolarYear", "SOLAR_YEAR", "solar_year_span", "Number of solar revolutions in the year", ""),
("oQJZ7l_ECol_Co4jt2h_4pEanGhmY_yDnaIG_0BgCTU", "story", "SolarYear", "SOLAR_YEAR", "days_in_solar_year", "Number of days in the solar year", ""),
("WEll0piFNOFB-DAPSx0q0nfb8jf_4ZTVjnMtynKDOpU", "story", "SolarYear", "SOLAR_YEAR", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("6g_z1v7uFFJ1rFUu3XqGKVFiGLDANYa1trWu_StCoZI", "story", "Season", "SEASON", "season_uid_pk", "Primary key, unique identifier for each season", ""),
("6eToMmYX8UWgdMzF73yhQZoFsWXWzxUPkw6MufbHfeI", "story", "Season", "SEASON", "solar_year_uid_fk", "Foreign key linking to the Solar Year table", ""),
("3Rpuwu4t0YKZxHkE4v_PI6o-WKwrYCsoM99uKUfJBVU", "story", "Season", "SEASON", "gloss_common_uid_vfk", "Virtual foreign key linking to the Common Glossary table", ""),
("WJMjZpjI5m0iUHHg0VwFbh9DX9tKhltVUxNJFDu-mjM", "story", "Season", "SEASON", "season_type", "Type of the season", ""),
("sheR5nmNcHSTGztD52JRSodriuIJAE9uy2RQGKpD0CQ", "story", "Season", "SEASON", "hemisphere_type", "Hemisphere of the season", ""),
("MG_rMWB9QNYrNjdXdpeWRZTwbzJFuAUsJIEiBpirlO4", "story", "Season", "SEASON", "years_in_season", "Number of years in the season", ""),
("q5Airn2XjmrlsVv4EpN62OMIenTHgbPZbrBwmgRAxzo", "story", "Season", "SEASON", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("JMoWc9x-6oRPUpfUERDZT-3bL6UDITGZqITg1GIHr70", "story", "LunarYear", "LUNAR_YEAR", "lunar_year_uid_pk", "Primary key, unique identifier for each lunar year", ""),
("NW64MxcIjlmJtBq3nV4QxoVe6BsGbCEfMbPw49lPXlE", "story", "LunarYear", "LUNAR_YEAR", "world_uid_fk", "Foreign key linking to the World table", ""),
("2JZ-w84nHieBr3OFfLCEaJizOqXd5cQkrzonC9q-8ZI", "story", "LunarYear", "LUNAR_YEAR", "lang_uid_vfk", "Virtual foreign key linking to the Language table", ""),
("5X1vygSpZJS9gtGJuKiIRcbfgxZgbHLExlRgQ17lj0M", "story", "LunarYear", "LUNAR_YEAR", "lunar_year_name", "Name of the lunar year", ""),
("3iY_pqhCjFCljLlHSN1o0Vq-XfDLrtPwSg06SJENcek", "story", "LunarYear", "LUNAR_YEAR", "lunar_year_desc", "Description of the lunar year", ""),
("CffPg9NIMte6V7ZYZ-BlwTL6CqVrTCuLFqcs8EPjMHc", "story", "LunarYear", "LUNAR_YEAR", "days_in_lunar_year", "Number of days in the lunar year", ""),
("HohKMbLClDZMmP7o5Lk9vZOq7K8YlQxjU-bVSdhKtSY", "story", "LunarYear", "LUNAR_YEAR", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("zX4guNN76A-ffE0vxrAylyp7FPPXv-JJt9ZXldF7dr8", "story", "SolarCalendar", "SOLAR_CALENDAR", "solar_calendar_uid_pk", "Primary key, unique identifier for each solar calendar", ""),
("rokboUf5VjQriYz5DDzXVYjX1CxY2xUIGXfDscYQcL4", "story", "SolarCalendar", "SOLAR_CALENDAR", "solar_year_uid_fk", "Foreign key linking to the Solar Year table", ""),
("eodNQhp41vZGdC42edc5O2MYVV-cNeDf1pvryHhOrPk", "story", "SolarCalendar", "SOLAR_CALENDAR", "year_name_gloss_common_uid_vfk", "Virtual foreign key linking to the Common Glossary table", ""),
("y8EIEspgglotdZSpxKIN9kwDSYft369V2j6at8qyiFI", "story", "SolarCalendar", "SOLAR_CALENDAR", "season_start_uid_fk", "Foreign key linking to the Season table", ""),
("s3r2sTa9hA1HmIlKrXfvSQaHrkKHS_Wh52BM-V14198", "story", "SolarCalendar", "SOLAR_CALENDAR", "solar_calendar_name", "Name of the solar calendar", ""),
("tTEXz_KT3TRn0HPQ16cbP_mEjxW9K0uSEaekrQsKtoU", "story", "SolarCalendar", "SOLAR_CALENDAR", "solar_calendar_desc", "Description of the solar calendar", ""),
("7waB3HmXXQBeuiigr9-2xfvBlH8KaehKjEwd3pE-obA", "story", "SolarCalendar", "SOLAR_CALENDAR", "epoch_start_offset", "Offset from the epoch start year", ""),
("zTTqhk4yEF0jAqAWbb5k95z5xQXtHgab5ilcsUIhNQM", "story", "SolarCalendar", "SOLAR_CALENDAR", "months_in_year", "Number of months in the year", ""),
("qopLQ247hv1KXuD3CZomxQ8msmMl33QEbmPmlT2p740", "story", "SolarCalendar", "SOLAR_CALENDAR", "watches_in_day", "Number of watches in the day", ""),
("raQ1yOaPKKdtiDKpPKEJ1nhMxAtG5Ovwra1QeIIDwjA", "story", "SolarCalendar", "SOLAR_CALENDAR", "hours_in_watch", "Number of hours in the watch", ""),
("qvHmp308OsN4UuK5vwKk35HEWCuc1Jh3LhMiQFQGBdA", "story", "SolarCalendar", "SOLAR_CALENDAR", "minutes_in_hour", "Number of minutes in the hour", ""),
("94DjY_uCSi-_3gdTThM0tBikZMiKfmKdA7MjBO3BfSc", "story", "SolarCalendar", "SOLAR_CALENDAR", "seconds_in_minute", "Number of seconds in the minute", ""),
("fMxJJ_cYkl4gLiRIc-05P26_2WnxKeHuaBGKvtOg93o", "story", "SolarCalendar", "SOLAR_CALENDAR", "leap_year", "Number of leap years", ""),
("nGnbszd5C2GhmRaWweNd-P5yz09CWvfuJkT7cy_u9iM", "story", "SolarCalendar", "SOLAR_CALENDAR", "leap_month", "Number of leap months", ""),
("_ccc3aJm7caYvGfY7jJyzwoL5TXf91x5dh6wsmXQuCA", "story", "SolarCalendar", "SOLAR_CALENDAR", "leap_days", "Number of leap days", ""),
("D3PVt4O45aeUwQRbY_G8_BUQoUM9kB1avDTEGEOK3zI", "story", "SolarCalendar", "SOLAR_CALENDAR", "leap_rule", "Rule for handling leap years", ""),
("NQqETpemevW1hSiBtIG5IkLVO-f-si1UZtnf9a41OFk", "story", "SolarCalendar", "SOLAR_CALENDAR", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("jtMM3LDXviOc7ZJ1czgRM2z0cmEyf_CaHWJlH1xoTkc", "story", "LunarCalendar", "LUNAR_CALENDAR", "lunar_calendar_uid_pk", "Primary key, unique identifier for each lunar calendar", ""),
("q2XkWyr0MKQUg8Zu5mgeXzG7k9ikDhFMbD0R1tJXudU", "story", "LunarCalendar", "LUNAR_CALENDAR", "lunar_year_uid_fk", "Foreign key linking to the Lunar Year table", ""),
("3tGIWj9mKe84Utysa_8hDzVWRhdks5j79kYAoOdn_bE", "story", "LunarCalendar", "LUNAR_CALENDAR", "lunar_year_name_gloss_common_uid_vfk", "Virtual foreign key linking to the Common Glossary table", ""),
("vInNJ0rx-a28pYwc86Qg8QDcndh6yyxnTjISa9duLR4", "story", "LunarCalendar", "LUNAR_CALENDAR", "lunar_calendar_name", "Name of the lunar calendar", ""),
("9PtNAAft-SbhtYgmwkHwYoURLxxWl2wM7dsHMyAj044", "story", "LunarCalendar", "LUNAR_CALENDAR", "lunar_calendar_desc", "Description of the lunar calendar", ""),
("mRupVIJizbJUe6lgzts7JbZ5JwMBK_pj8ew_Jat0IJM", "story", "LunarCalendar", "LUNAR_CALENDAR", "epoch_start_offset", "Offset from the epoch start year", ""),
("ADEDT2ZcbGKkI5O7ELPS0-A701kpTkTsFQjMxH3KM4w", "story", "LunarCalendar", "LUNAR_CALENDAR", "days_in_month", "Number of days in the month", ""),
("tgjgpJqYJk7EyM9HualSek0TufWhfasWJcvtB_7bU_I", "story", "LunarCalendar", "LUNAR_CALENDAR", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("knDv7xrPaLZjLrT-qYoae7IZaVhSbDnbH1CE7dsNwOQ", "story", "Month", "MONTH", "month_uid_pk", "Primary key, unique identifier for each month", ""),
("-7n7DS8iU1LglJkkt2zLwqlpfcCFXpG2G4BI95rS04o", "story", "Month", "MONTH", "month_name_gloss_common_uid_vfk", "Virtual foreign key linking to the Common Glossary table", ""),
("ivtjn9wCkSL3_5thgFNY8QgELjjSzVTWk72YnZ0qiUo", "story", "Month", "MONTH", "month_name", "Name of the month", ""),
("41DWV-JEn4OHSw7yZVJJTRDK5KDM05cLeHwm1rD3cSo", "story", "Month", "MONTH", "days_in_month", "Number of World days in the month", ""),
("m06a7sDAAIG0GFfgE3iS8StFlMb5y53X4eXpLxQTuP4", "story", "Month", "MONTH", "month_order", "Ordinal number of the month", ""),
("4vAHQd6_rwoEzFlfKj852MFxMFTBjMdUFSwtm7jiHpU", "story", "Month", "MONTH", "is_leap_day_month", "Indicates if the month contains leap day/s", ""),
("n4JQfKZJ7YdK3pWhaZsS_5aW6SxG86tjZV1yEt6yjtU", "story", "Month", "MONTH", "is_leap_month", "Indicates if the entire month is leap days", ""),
("sM2dnwQxuk9yskLNxzcIVZAhqUKpxiD2sPVjz3kaPVI", "story", "Month", "MONTH", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("NHCGujbG_tjSF6DmfZ2EfN9mNKSBla05LWBofuASSwA", "story", "WeekTime", "WEEK_TIME", "week_time_uid_pk", "Primary key, unique identifier for each week time", ""),
("5Li2fwqamzcFSYysFHQ-8BaZVhMhyu0BET2abxSbrpc", "story", "WeekTime", "WEEK_TIME", "week_time_name_gloss_common_uid_vfk", "Virtual foreign key linking to the Common Glossary table", ""),
("9EzYUPxUGhzpzcSu5qAJ5VN2KIx5Y1WrlaV8evE3MEU", "story", "WeekTime", "WEEK_TIME", "week_time_name", "Name of the week time", ""),
("ycADNWQVXgy5dQ8SjqtsRM7LleBcFmCtbQW4iVP96L4", "story", "WeekTime", "WEEK_TIME", "week_time_desc", "Description of the week time", ""),
("P3e1kqSGW1sl3koRdI53EOrmCKVoToitiiSdEImkDAI", "story", "WeekTime", "WEEK_TIME", "days_in_week_time", "Number of days in the week time", ""),
("iSbTLGhHsSznKBTK06OFA2oZ7ojX2ksjbzkdOSwr9Vw", "story", "WeekTime", "WEEK_TIME", "week_time_order", "Order of the week time", ""),
("3J2Qaw1jGFx4t3FQxoXFRbH-xYMqTfOMEm_Nw9ZNyvQ", "story", "WeekTime", "WEEK_TIME", "is_leap_week_time", "Indicates if the week time contains leap day/s", ""),
("NDNBKaeEWa2ElEu3-THPwRrJxqm9PWSzq_Twjp5wWEU", "story", "WeekTime", "WEEK_TIME", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("lC0CJaUaSCyNaO2FabDe-e7Cxy_nkpYXotHZ-7nkkbc", "story", "DayTime", "DAY_TIME", "day_time_uid_pk", "Primary key, unique identifier for each day time", ""),
("UTIhWM4wAeiqjtUn-yEiqr0lKbmpLd5WoX-4KXkUFN8", "story", "DayTime", "DAY_TIME", "day_time_name_gloss_common_uid_vfk", "Virtual foreign key linking to the Common Glossary table", ""),
("C88BbzexeXUecj-LapepnpyZRfKphhbmb52gBBBwDJM", "story", "DayTime", "DAY_TIME", "day_time_name", "Name of the day time", ""),
("b5EtuOnrZkAOkdn1cBAXM1FcXHRWPYgjG38fQ2sftqQ", "story", "DayTime", "DAY_TIME", "day_time_desc", "Description of the day time", ""),
("6KtbrN3R90h15lY5HFXSPN7b_H64FwvNOWjSPRfwVEI", "story", "DayTime", "DAY_TIME", "hours_in_day_time", "Number of hours in the day time", ""),
("XmkXN27cn5sLM25puz2CAL_iOgeYUZIP2s5YhX7hHL4", "story", "DayTime", "DAY_TIME", "day_time_number", "Order of the day in a week", ""),
("Lz7kcSiVNugghB5pl6F_uEwQoW6ppDx_kHdL_LXEcZU", "story", "DayTime", "DAY_TIME", "is_leap_day_time", "Indicates if the day time is only a leap day", ""),
("Ycm4hG63BWzYnZ7uHyYBfX1_FC229Yx9KvMLjz1JxuQ", "story", "DayTime", "DAY_TIME", "delete_dt", "Deletion date, indicating when the record was marked for deletion", "");