INSERT INTO `METADATA` (
`meta_uid_pk`,
`name_space`,
`model_name`,
`tbl_name`,
`col_name`,
`col_def`,
`delete_ts`) VALUES 
("iEf3D9rNlVLaOlu2on_CaKObyGLc4TwUqLOD6RxFA80", "app", "Metadata", "METADATA", "meta_uid_pk", "Primary key", ""),
("wY4JcM5SJLkc6kSA9PS_D_xEBchb2UyDzP-nWOFpA4Y", "app", "Metadata", "METADATA", "name_space", "[app|story]", ""),
("Zx6ScqKWsNZgwonZkkPL-4u5r3zQdFbe6-x4Gj0rx2Q", "app", "Metadata", "METADATA", "model_name", "name of the data model class", ""),
("-u2RjlQ9L6FlzlnhRGl6IlKSJsb1mm4LQPVX94y3DR4", "app", "Metadata", "METADATA", "tbl_name", "name of the SQL table", ""),
("Z3mRA8Rzvq6gysaSPPar9BKKiUKDdiTTel04_CGW2kE", "app", "Metadata", "METADATA", "col_name", "name of the SQL column", ""),
("RYAZ_ebpMCtF0knnql1CxsgpvIS87RMLJ__-lqgvedw", "app", "Metadata", "METADATA", "col_def", "definition of the SQL column", ""),
("sqbWBEn5odAa05w0delSWmPit0WTWv_I-BgnipuO_cM", "app", "Metadata", "METADATA", "delete_ts", "date/time of virtual deletion", ""),
("Gr7dWQj5yo1MNpONZBRn9tUgf5C2UVsg2t3lO6v4pB8", "app", "Backup", "BACKUP", "bkup_uid_pk", "Primary key", ""),
("QPlzD7ZNFyjvQVogiEq09Tt9avU4vJP8BqVjC2FiDls", "app", "Backup", "BACKUP", "bkup_name", "Name of the backup", ""),
("nQEXzOPc1IRDcULtSHCUVZvLaDnbTBncINb7tYwKOfY", "app", "Backup", "BACKUP", "bkup_dttm", "Date and time of the backup", ""),
("8KVOKpUV73843B9EX2YykeFHXmGdeu9sjGGylZ48SQ0", "app", "Backup", "BACKUP", "bkup_type", "Type of backup, e.g., full, incremental", ""),
("5rBENuZRDFfGA53QAeGt2G-2-nB3mO_GIHSLRZZ296c", "app", "Backup", "BACKUP", "file_from", "Source file or directory", ""),
("_k5cHifyaaZCPKp4S1gcnSDF0mJ-lVwKo58QbLMKRzE", "app", "Backup", "BACKUP", "file_to", "Destination file or directory", ""),
("HX3SoZUdfbGEc6zMEA4QszxpvcVidy-Pd3w86aXreqo", "app", "Backup", "BACKUP", "delete_dt", "Date and time the record was deleted", ""),
("Tqxq8zrCi40FmZ0wc0qaY4u6DQh-m8VDpB9jrq42j4w", "app", "Texts", "TEXTS", "text_uid_pk", "Primary key, unique identifier for each text entry", ""),
("CQ2zxIxf7JoVBSt1QaFyXqQc3Lp0QE6--frXDFzPDms", "app", "Texts", "TEXTS", "lang_code", "Language code of the text, e.g., en, de, fr", ""),
("bEuU2zoGVgE2YGGsTxRcl-nyloBApSjd3OM-rSn2gq4", "app", "Texts", "TEXTS", "text_name", "Name/ID/label of a text string, not unique, shared across languages", ""),
("yUmzm6j1-DdV-F7DjoIPvFMqXFmOzwm3v9EG8WcIMqM", "app", "Texts", "TEXTS", "text_value", "Text string value", ""),
("WQe4kbdKDi7QDCWlri63u7kqBNDNsp8elPneFJ-G954", "app", "Texts", "TEXTS", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("W_FV8FUO1UlzlxmleLfwTruNTeoL6629L8p6V_9sXjc", "app", "Frames", "FRAMES", "frame_uid_pk", "Primary key, unique identifier for each frame entry", ""),
("qZW3ewiekC0ws9VKQNPYaD8HA0GT_OyDDlbR-9j2xqM", "app", "Frames", "FRAMES", "lang_code", "Language code of the frame, e.g., en, de, fr", ""),
("HZiPd4Za9EvrkiccbUk5GB7UdQwbv6A5CdJSsosE1I4", "app", "Frames", "FRAMES", "frame_id", "Not unique, can be shared by apps, e.g., admin or game", ""),
("Xe596qphdQ3wdl50azPd6pdJHhyI2qILfvIFEx8wBJo", "app", "Frames", "FRAMES", "frame_title", "Title of the frame", ""),
("jl_IKcdB1gxhK8SnT7mx8vtHuuvjpNLU68TPgMVVMjI", "app", "Frames", "FRAMES", "frame_desc", "Description of the frame", ""),
("wfRLOWDv0j_SDxIumRiswi6UaCZXC7EuLjzupNsez4M", "app", "Frames", "FRAMES", "frame_w", "Width of the frame", ""),
("dvCmthc99vk_HfmnLe_dEShL4vKUFshob3EEv3uG7mE", "app", "Frames", "FRAMES", "frame_h", "Height of the frame", ""),
("lIraQhUP1WYJ7VJ61eDXKru83UZNiv9B-vkxCtsNoMg", "app", "Frames", "FRAMES", "pg_hdr_x", "X-coordinate of the page header", ""),
("qxqfz71jg2Wq2B67rtKsh9LuCA3P-Y2TPlyL-A26gE4", "app", "Frames", "FRAMES", "pg_hdr_y", "Y-coordinate of the page header", ""),
("SjNoDttB4-SNuf12Av0mMwpWnivgX_p0mXEMRPNz8hA", "app", "Frames", "FRAMES", "pg_hdr_w", "Width of the page header", ""),
("60UqKVKI-PN3VP7Bqk2lCR1qxecilBQTEIeP5yYjfeM", "app", "Frames", "FRAMES", "pg_hdr_h", "Height of the page header", ""),
("psHcnX3KVEK0W1t2oK-eOAEdcn_cIP8qsoZiBmyTfkU", "app", "Frames", "FRAMES", "pg_hdr_txt", "Text displayed in the page header", ""),
("2yWdDcVDtU3UozSfq1qzyggH4Ht0b3NCzPbSMw_vddM", "app", "Frames", "FRAMES", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("xUWzENAaSFKF3kmFTwygUKohFPsCRrXliB9AiBXQkPg", "app", "MenuBars", "MENU_BARS", "menu_bar_uid_pk", "Primary key, unique identifier for each menu bar entry", ""),
("YbMwtNyVnHXpTCLr68ZLbK_nuen1_7YfJlR5S68NSUs", "app", "MenuBars", "MENU_BARS", "frame_uid_fk", "Foreign key referencing the frames unique identifier", ""),
("rb2yFE_0ysn-cRX-Jusd1ZonloUw_c6yqdIujE6-xD8", "app", "MenuBars", "MENU_BARS", "frame_id", "Identifier to match with corresponding frame records", ""),
("WTsHfHXoaZ4sk8MLevwYGZfW_0XiQbMOf2oVzd_cVvk", "app", "MenuBars", "MENU_BARS", "mbar_margin", "Margin around the menu bar", ""),
("1MNUHM_Sje3I6F2k2lPfylTRaFJmk2LK7FUwQreRTKA", "app", "MenuBars", "MENU_BARS", "mbar_h", "Height of the menu bar", ""),
("KGGHBpVW6FY8mCJkEz_D_eZWnSwXsE3mKM44-vAFK1c", "app", "MenuBars", "MENU_BARS", "mbar_x", "X-coordinate of the top-left corner relative to the frame", ""),
("f1EZj1AkxHtKgH8EStU43fXDUqaZaFpaiUaRZlz1vCs", "app", "MenuBars", "MENU_BARS", "mbar_y", "Y-coordinate of the top-left corner relative to the frame", ""),
("xAviI3gm53FMhbo-L1YTnOQjMfp0QThh2P83gcftA38", "app", "MenuBars", "MENU_BARS", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("5oUV9_Z-LcR4WwftF5R6YQ5N3iO6otO-PGGWq3Qsvl8", "app", "Menus", "MENUS", "menu_uid_pk", "Primary key, unique identifier for each menu entry", ""),
("G5FMDcvpVdoqz70VpJ4hzpZ3xaO12fpT7_3ZXGgV9_c", "app", "Menus", "MENUS", "menu_bar_uid_fk", "Foreign key referencing the associated menu bar", ""),
("uY4XSeqH9framVZcTxRhdW_k6Dlcykcz_p9sSETGQ3o", "app", "Menus", "MENUS", "frame_id", "Identifier to match with corresponding frame records", ""),
("cg6vli-m1g5sXGcSSHqG9OLKAVJ3ihzZYuLgm94M1Jc", "app", "Menus", "MENUS", "lang_code", "Language code for the menu text", ""),
("G5WDdKdzlt73n9AX0qcZoy_RAPPnSJ4eMuaPDFoSrKo", "app", "Menus", "MENUS", "menu_id", "Generic string label ID or key for menu", ""),
("8KbENCoPksu4God4QiwRWhXexYKA3RXLSyK2aKyunBM", "app", "Menus", "MENUS", "menu_name", "Text string label for menu in designated language", ""),
("4en88uOEbjZds9M0cFxBu5mk_gakuJohKMVQ1tWPvRk", "app", "Menus", "MENUS", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("75A7rJsVsvdYMsFd3X-3Yc1mnjw4se1BTGjAhG81KCE", "app", "MenuItems", "MENU_ITEMS", "item_uid_pk", "Primary key, unique identifier for each menu item entry", ""),
("vwydpVkAfIH6UTjfz4VhEHV4L70lQ5pS5m7EQhaoU68", "app", "MenuItems", "MENU_ITEMS", "menu_uid_fk", "Foreign key referencing the associated menu", ""),
("i1_qMPuidTpx02TisXZ9ENIyf36og4iQwrLeBy9CKs4", "app", "MenuItems", "MENU_ITEMS", "lang_code", "Language code for the menu item text", ""),
("1edGC562XNbVa3G4-tBmN0dX8BGymDoTC3ZA8eaBW1Q", "app", "MenuItems", "MENU_ITEMS", "frame_id", "Identifier to match with corresponding frame records", ""),
("BX4BZzOdTqdG7l9cK_FkXus5XT0FGRrySh13vILAY0Q", "app", "MenuItems", "MENU_ITEMS", "item_id", "Generic string label ID or key for menu item", ""),
("Z2IocNbv2uQXaipxGHWzs-Hs64tktF5tFRSinatWOLQ", "app", "MenuItems", "MENU_ITEMS", "item_order", "Order of the item within the menu", ""),
("Q4kxulQt2tZGoURdOCySQgGFwG9LWDtOxmXYgdSzXyI", "app", "MenuItems", "MENU_ITEMS", "item_name", "Text string label for menu item in designated language", ""),
("kQvwBq-bjlgwWl1SF49MguVEgEAw89grnd7zkzzNyXM", "app", "MenuItems", "MENU_ITEMS", "key_binding", "Shortcut key binding for the menu item", ""),
("VmoXGpV6FEJ2LgVOAE_QO760poauezgDQJA7n_8QgFo", "app", "MenuItems", "MENU_ITEMS", "help_text", "Help text or description for the menu item", ""),
("Gf6MI18GctxmqjrqXBHPMNjriwl8IV0nTRg4rpy2rDM", "app", "MenuItems", "MENU_ITEMS", "enabled_by_default", "Boolean indicating if the item is enabled by default", ""),
("Dwases1X3J5TXluD5YeyjnXroLtuLtiFWxTyaP2aKSE", "app", "MenuItems", "MENU_ITEMS", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("KOhwsMxxYYJFz_r_PRjH3LAyaZ5R5ra47Ki0Ua30pO4", "app", "Windows", "WINDOWS", "win_uid_pk", "Primary key, unique identifier for each window entry", ""),
("nDqqvqbVMSG1BLOHeWNXqeuCGdxOYGRmwHJ4awBQ5aQ", "app", "Windows", "WINDOWS", "frame_uid_fk", "Foreign key referencing the associated frame", ""),
("OzUb2r9Qq_P15MkCn0F1HaCuEmC1vEJLF13mYj-hYoI", "app", "Windows", "WINDOWS", "frame_id", "Identifier to match with corresponding frame records", ""),
("DEue03Nci4rmjqoLO2LQ2AN7yHv16A94zML2PAj6xFo", "app", "Windows", "WINDOWS", "lang_code", "Language code for the window text", ""),
("YcX-_qURvCyQt5l6zqPdmCzO2SyC6nN65uYiHuSv5eg", "app", "Windows", "WINDOWS", "win_id", "Generic string label ID or key for the window", ""),
("pzjrODoglbqg6qLxvyCK8ZQBdz8NF5KFrk24PuBOf5I", "app", "Windows", "WINDOWS", "win_title", "Title of the window in designated language", ""),
("LYvZJ_ELSuaAB8w8t5_lF5gdw0sbMNZt4xfl2HmqNMI", "app", "Windows", "WINDOWS", "win_margin", "Margin size around the window", ""),
("cV9YElIzIR4KLsYGOBs17B1-1y_sb9tchT-6hV2Xh-w", "app", "Windows", "WINDOWS", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("mx2Exot1ypOwL5ja9jSqeOnBr4vbFH2Jr-qer2cTdyw", "app", "Links", "LINKS", "link_uid_pk", "Primary key, unique identifier for each link entry", ""),
("jO6_6UzFJrqsP3G1ceVxE97NYFmelvx6fL0-R_uAXls", "app", "Links", "LINKS", "lang_code", "Language code associated with the link", ""),
("2X4JdvDT6Rl_gwmMzpP6tCxiNVHVo-ti-6BX-bsRp1g", "app", "Links", "LINKS", "link_id", "Identifier for the specific link", ""),
("EXtnC79G_3mRWKWljZXlFiJkh-DUjKRzf7fCT3gBpR0", "app", "Links", "LINKS", "frame_id", "Identifier for the frame associated with the link", ""),
("gycD2YTX2N4lHKm2dIINQMvA_GNzs7qnQOgpXiS3Dgc", "app", "Links", "LINKS", "link_protocol", "Protocol type (e.g., HTTP, HTTPS), used by the link", ""),
("kXekcuOh91m-MplDuFc7i3jHelxgjeWiBFoRIlIJkhg", "app", "Links", "LINKS", "mime_type", "MIME type specifying the nature of the link content", ""),
("AMe2hPMJhvSy7OgLBF-EDbM9_12QvPjWnYaaMc8htnw", "app", "Links", "LINKS", "link_name", "Descriptive name of the link", ""),
("-cem43kKJ1BRLi8XeH5169V7ThC69smAb4BDT4O9QbE", "app", "Links", "LINKS", "link_uri", "The actual URI or address represented by the link", ""),
("07jnx3ap522iJWOM9zej--NRYAiditInosKQ1BZdqP8", "app", "Links", "LINKS", "link_icon", "Icon representing the link visually (stored as BLOB),", ""),
("_jPCFS9SYIJ2nLX7Hy8HJuvVwU7JVf8FlMui_drYp34", "app", "Links", "LINKS", "link_icon_path", "Path to the icon file", ""),
("zfsemWEj-goamPHU1FaKfTPKX1PA_D_CwQS3EhxAqpo", "app", "Links", "LINKS", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("zVUzpiD_qhvYJdOi9oKfQRNGeA1V6c3l44isMI-5mDM", "app", "ButtonSingle", "BUTTON_SINGLE", "button_single_uid_pk", "Primary key, unique identifier for each button entry", ""),
("SO5iA3Z8hWhdwGUJgcnHfiwP4sCYhk1aC7W2Ani6aF0", "app", "ButtonSingle", "BUTTON_SINGLE", "button_type", "Type of button (e.g., submit, reset),", ""),
("ZwUDNQ35zEabkdnBpzhyPCjAAkL98J10yoVGDhwNmmk", "app", "ButtonSingle", "BUTTON_SINGLE", "button_name", "Displayed name for the button", ""),
("0wT0DJi2VHBYmeQFtvgjveC9Xv7ociGvTz2aJol_WOs", "app", "ButtonSingle", "BUTTON_SINGLE", "button_icon", "Binary data representing the buttons icon image", ""),
("QF-d9bIyCWcszJxaNBrcTXcuKJNWFH03f1T7LQlCVsk", "app", "ButtonSingle", "BUTTON_SINGLE", "button_icon_path", "Path to the icon file in the app images directory", ""),
("pJCRh4dZlCclp2L4EDTCJ32hDKYsbJ7WvRYttlAOXvY", "app", "ButtonSingle", "BUTTON_SINGLE", "button_key", "Key to press to activate the button", ""),
("XZrwTM9mbafOahYLvScBbYKV6E1srsJ3KafH1Qf_hN4", "app", "ButtonSingle", "BUTTON_SINGLE", "frame_uid_fk", "Foreign key linking to the associated frame", ""),
("AWtReNRC7KtS5dBTBLQXmzy5ymic_NkRxv6bw0pK0S8", "app", "ButtonSingle", "BUTTON_SINGLE", "window_uid_fk", "Foreign key linking to the associated window", ""),
("3dmsEdurgLa14D_AGaEXyZyYfxjD1IPOfFFGP8pvBFg", "app", "ButtonSingle", "BUTTON_SINGLE", "left_x", "X-coordinate position of top-left corner relative to the window", ""),
("e4WeIsgMabiCRuUYjMz39tED0UiOsrxK9UxFXorcu70", "app", "ButtonSingle", "BUTTON_SINGLE", "top_y", "Y-coordinate position of top-left corner relative to the window", ""),
("qXYLcEtIfLgmDnH2yur_-XjXqQrwdW5POMLfLnAeO1A", "app", "ButtonSingle", "BUTTON_SINGLE", "enabled_by_default", "True to enable, False to disable the button", ""),
("bv4js5opdH4r6tWfI7_368z08dxGzaNtdC5IPrhRQxM", "app", "ButtonSingle", "BUTTON_SINGLE", "help_text", "Text to display when the mouse hovers over the button", ""),
("cp-LlY2dHNvP_Has4m-W98e9iyxaI6GXUVa8aOAl5TQ", "app", "ButtonSingle", "BUTTON_SINGLE", "action", "Name of the function to call when the button is clicked", ""),
("BDisg8KQL-vSFLjY5bLxpK0ksTHVXKmFZHf_prNaARE", "app", "ButtonSingle", "BUTTON_SINGLE", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("H-ARsvPO7P33LX2foI7lw4uBVru2qkWv9NuMoCkAhbM", "app", "ButtonMulti", "BUTTON_MULTI", "button_multi_uid_pk", "Primary key, unique identifier for each button group entry", ""),
("RhPMLTVfPH4y-nnUnxdDSWZ76xT6Gu9zYe7Oey5q79o", "app", "ButtonMulti", "BUTTON_MULTI", "button_type", "Type of button group (e.g., radio, checkbox),", ""),
("nhGhIbC-PJwDo61RC0fRKwJez5wI2LoYqxYcJBA5COQ", "app", "ButtonMulti", "BUTTON_MULTI", "button_name", "Displayed name for the button group", ""),
("fTaSysMk6qQCQOl6GMbu0AP_KhLuidqTx4KNveegnk8", "app", "ButtonMulti", "BUTTON_MULTI", "button_icon", "Binary data representing the button groups icon image", ""),
("JcEa3FCMJrSMxvPBiPW5jTzXDgy0EDZAdlNzay6yLLo", "app", "ButtonMulti", "BUTTON_MULTI", "button_icon_path", "Path to the icon file in the app images directory", ""),
("fFpFf3Xb5kx4qnEbLP6LjRD6bupSPIzOwDFa0ubps78", "app", "ButtonMulti", "BUTTON_MULTI", "frame_uid_fk", "Foreign key linking to the associated frame", ""),
("gfB95QFa9ZGLg_v0UPGmBq5NeaQYFXuDiMciXThxBPo", "app", "ButtonMulti", "BUTTON_MULTI", "window_uid_fk", "Foreign key linking to the associated window", ""),
("89Qlu3hSlQtRRyCUftOZpl-mLShaCtf6PgU068gyMHw", "app", "ButtonMulti", "BUTTON_MULTI", "x", "X-coordinate position of top-left corner relative to the window", ""),
("ZmYeeKmHJbTcQNE2IWbfpo9F3NRVPE8wFIikNWxmVZ4", "app", "ButtonMulti", "BUTTON_MULTI", "y", "Y-coordinate position of top-left corner relative to the window", ""),
("7r8Mv1xk_GXXZtGef8HNQmksXOH5qPIWsRDvWWqJNvI", "app", "ButtonMulti", "BUTTON_MULTI", "enabled_by_default", "True to enable, False to disable the button group", ""),
("vC7sX5ZJeTvSSM5pXQhXrlIcQPbejriNV-7yvOM9BNI", "app", "ButtonMulti", "BUTTON_MULTI", "help_text", "Text to display when the mouse hovers over the button group", ""),
("e0rScs46Pgb9gmy3Zdm0H2urfJeTEvGzS_CmpNiGEKg", "app", "ButtonMulti", "BUTTON_MULTI", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("U8D-G-mPctQqkYun0W4NR4zg1XtbW3YJX5BNqQ9rsL4", "app", "ButtonItem", "BUTTON_ITEM", "button_item_uid_pk", "Primary key, unique identifier for each button item", ""),
("AS7w7tc3HHg1XCQkwkcsyiYrF_u8pLSgXNxwSG2rXSg", "app", "ButtonItem", "BUTTON_ITEM", "button_multi_uid_fk", "Foreign key linking to the associated multi-choice button group", ""),
("FyFyR4Jb_06FHEH6GiX2hVYPivJmPrdtLQINFwjOPuw", "app", "ButtonItem", "BUTTON_ITEM", "button_name", "Displayed name for the button item", ""),
("dhPXlaSRFTqE6Qmd-vSboL3Fqxxrn75S1BNEgr7oTuc", "app", "ButtonItem", "BUTTON_ITEM", "button_icon", "Binary data representing the button items icon image", ""),
("ZgPgDmBL36rtGvdPZP9KciFZr2_dpyLcRJM8BYIkxa4", "app", "ButtonItem", "BUTTON_ITEM", "button_icon_path", "Path to the icon file in the app images directory", ""),
("qn2VVZN-NcyJUAlqUuvuwX9iszQ6dAoXNtOgUxHSI5g", "app", "ButtonItem", "BUTTON_ITEM", "button_order", "Integer defining the display order of the button item within the group", ""),
("xjsonvhU830Koplj42Rvbj84qPQFfV8YQz8Gq8yr6UM", "app", "ButtonItem", "BUTTON_ITEM", "button_action", "Action or command executed when the button is pressed", ""),
("pRaY3K-Xo4-s9X6xdFoO8d6p5KcNa6yq0QxMOVuO-2o", "app", "ButtonItem", "BUTTON_ITEM", "enabled_by_default", "True to enable, False to disable the button item by default", ""),
("mqRdcPwcFeF_VfWzW9-Tmo0CCixTCzsW9TtXHnC-Esg", "app", "ButtonItem", "BUTTON_ITEM", "is_enabled", "Indicates if the button item is currently enabled", ""),
("LwyirEZeJROZFuVrJKOCeCD0uwkACyg0RRS9lgAWSoo", "app", "ButtonItem", "BUTTON_ITEM", "help_text", "Text to display when the mouse hovers over the button item", ""),
("Vf74cCTksEplcbKEoinDe8spHYN7iwl3j4AYB0zHRY4", "app", "ButtonItem", "BUTTON_ITEM", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("_66skYxeAZlK2AI2CyZ21n15oJqQ233O8k1XeKTojMw", "story", "MapRect", "MAP_RECT", "map_rect_uid_pk", "Primary key, unique identifier for each map rectangle", ""),
("6C31SPfuTK77Xh6XxESQ7CxXxioeJ02KCqHLMheIduA", "story", "MapRect", "MAP_RECT", "map_shape", "Shape of the map area (e.g., rectangle, box, sphere),", ""),
("ICzplctRtDbwzBTlWVmCyEKhP2oSjtlY9bOyyFhNkY4", "story", "MapRect", "MAP_RECT", "map_type", "Type of map area (e.g., geo, astro, underwater),", ""),
("pk61pq9prHB1gkDJa-ZhJNJ6GZxRumGHBwC2YF_eIVc", "story", "MapRect", "MAP_RECT", "map_name", "Name of the map rectangle", ""),
("Aqxz4FNzCi7mSejsyK6FK9fl5MjxnoC4upGx97x85hs", "story", "MapRect", "MAP_RECT", "map_desc", "Description of the map rectangle", ""),
("Zf49dNnVm6M8QKTTuwDQNalhrvsiJ5uVXATnCq3Dfwk", "story", "MapRect", "MAP_RECT", "north_lat", "Northern latitude boundary of the map rectangle", ""),
("wbnpPUYBm2J8vrZhTvk6VuNQztmIaJ7MjtjX5Qhvt90", "story", "MapRect", "MAP_RECT", "south_lat", "Southern latitude boundary of the map rectangle", ""),
("D4kyswminSY1krRoa1xSZXEBDqi2K7geVXEsZuBPfWo", "story", "MapRect", "MAP_RECT", "east_lon", "Eastern longitude boundary of the map rectangle", ""),
("vWMosdpEKhGa0eOGw_M2g4YePvKGBT4FMnKrUtAUp2o", "story", "MapRect", "MAP_RECT", "west_lon", "Western longitude boundary of the map rectangle", ""),
("6FMFIVweYotH3YBy4zKVYxJ3wJhR0Nr1mJi7nVyFRNI", "story", "MapRect", "MAP_RECT", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("uErbAnVq8AHM7ErNnZO1Ti8cQTdtPeWTEHiqSDCNq5Q", "story", "MapBox", "MAP_BOX", "map_box_uid_pk", "Primary key, unique identifier for each map box", ""),
("92xf-KT_mSBwKpJChMih_YNYmRB7vsQ6sjCA-fw0o_0", "story", "MapBox", "MAP_BOX", "map_shape", "Shape of the map area (e.g., box),", ""),
("xxgxOS6vvjk0SgQ7jRXWW_XMeQGXNrWLTQpipnlQyFs", "story", "MapBox", "MAP_BOX", "map_type", "Type of map area (e.g., geo, astro, underwater),", ""),
("4wZVTuryLus06cX1j5nfPcGBUlD4ZWpNRaD5ghCV5N8", "story", "MapBox", "MAP_BOX", "map_name", "Name of the map box", ""),
("IMaFc1m7K0AwwZYePJhaGVWPYVL4-Q5UIsfmu6ikNFg", "story", "MapBox", "MAP_BOX", "map_desc", "Description of the map box", ""),
("bgCyQLi3smigjB2S2dXZpFMCvJaawG_Sx-X2ejCCKtw", "story", "MapBox", "MAP_BOX", "north_lat", "Northern latitude boundary of the map box", ""),
("1w20kvMGA2eeki1cf5vnngTqItV5r0ANCDoMfwyD70U", "story", "MapBox", "MAP_BOX", "south_lat", "Southern latitude boundary of the map box", ""),
("mswRTQ-ldcoQ-1nid9pHUx71plXqpWchaZR5_MTqDLU", "story", "MapBox", "MAP_BOX", "east_lon", "Eastern longitude boundary of the map box", ""),
("XFeKiO61Z8e1nD6APyGsWMUWiMGaKM330oX-kpLGq7A", "story", "MapBox", "MAP_BOX", "west_lon", "Western longitude boundary of the map box", ""),
("bqTzIT160IyO0hk62CpXFJMY673gVV2HL35AFx1Ihqk", "story", "MapBox", "MAP_BOX", "up_m", "Maximum meters upwards from the base level", ""),
("hlSj3knWfSrXwB_87OisjJu6u7a0R8j7q6k3-85n7v0", "story", "MapBox", "MAP_BOX", "down_m", "Maximum meters downwards from the base level", ""),
("ZMM5asw4l3k6y4fiUh0ACGleOQqwTDyBF21hRASsfKQ", "story", "MapBox", "MAP_BOX", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("YwRoYlmEGT5Y6t3hqBYaNa3-bB8i0nNlipDlreAEFxA", "story", "MapSphere", "MAP_SPHERE", "map_sphere_uid_pk", "Primary key, unique identifier for each map sphere", ""),
("IxV2S3rBSw8pxetsuDYiqVQO2ORn_ikw5EDXklILbx4", "story", "MapSphere", "MAP_SPHERE", "map_shape", "Shape of the map area (e.g., sphere),", ""),
("9BfMW2427MEpoki1txfQ9wvONrTIWUG74QBVN6bVVyg", "story", "MapSphere", "MAP_SPHERE", "map_type", "Type of map area (e.g., geo, astro, underwater),", ""),
("xyOCQlb0FjxtTIzlF6CrcQ7kHit9thBnwti95VaL2L8", "story", "MapSphere", "MAP_SPHERE", "map_name", "Name of the map sphere", ""),
("3KJqtfvBGMKuUXNrysZgOTX9fKxsLzzPHjBUcI-Je9k", "story", "MapSphere", "MAP_SPHERE", "map_desc", "Description of the map sphere", ""),
("zWdWhyN6K-Gzq6R36ayLXGUZr1l7iebhZWBbZjBhu6U", "story", "MapSphere", "MAP_SPHERE", "origin_lat", "Latitudinal coordinate of the spheres origin", ""),
("8WtfZTxMKS8s1PX_IW7-CUvP6RkZ1QvcGOllXRtCnIg", "story", "MapSphere", "MAP_SPHERE", "origin_lon", "Longitudinal coordinate of the spheres origin", ""),
("lKTosXIMycHwJ3Iz5ZrVSzWIqJhM07jTeHLBBlChd6w", "story", "MapSphere", "MAP_SPHERE", "z_value", "Z coordinate value, indicating height or depth from a reference point", ""),
("GjxzomQxCjsDHh1kpL7ivOfFOV2TKEj4FtYIGKGPFkM", "story", "MapSphere", "MAP_SPHERE", "unit_of_measure", "Unit of measure used for dimensions (e.g., meters, parsecs),", ""),
("8ewBTSXOYSgRCRsMYwm6mKo_VGXtvch4kII20tZYeC0", "story", "MapSphere", "MAP_SPHERE", "sphere_radius", "Radius of the sphere", ""),
("cK7dcsmAyC_exJcSzvfRKijPVu-UGxLHIZxFCO7iWo4", "story", "MapSphere", "MAP_SPHERE", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("rXYLAdwlUI1lTc01jaCgk5qSONHSFXs3qH0U5FF0UH8", "story", "Grid", "GRID", "grid_uid_pk", "Primary key, unique identifier for each grid", ""),
("bJpjBk-LcQf7qfjgt2uEqOTSNlaiM-pW3wRNnKLK3OE", "story", "Grid", "GRID", "grid_name", "Name of the grid", ""),
("R-7CRKZF8fbFhZYPedZ5XJLhngJaTju8_KXh7bdVNt4", "story", "Grid", "GRID", "x_col_cnt", "Number of columns (east-west direction),", ""),
("1b04-irM_HRCE3GZ5ZL96fZkcxAEVv_rkBbK21IgPnA", "story", "Grid", "GRID", "y_row_cnt", "Number of rows (north-south direction),", ""),
("z7thjJT6Hx_Zr7uM0V5o9nSKEYUdruefwIFM2WjyJSw", "story", "Grid", "GRID", "z_up_cnt", "Number of layers above the zeroth row", ""),
("joT6e8lrBvnD4hCteas_kIaVa137ZmR25kOAfl0c45s", "story", "Grid", "GRID", "z_down_cnt", "Number of layers below the zeroth row", ""),
("yqdXV9FlVPpILiCOM70CfMFcPTi2G_UFn61zaI2VF_g", "story", "Grid", "GRID", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("Vc3IbEGDTMlQXg87xjed-F5JDU1pLYTehMgx_GIBqZY", "story", "GridCell", "GRID_CELL", "grid_cell_uid_pk", "Primary key, unique identifier for each grid cell", ""),
("gvDyMBPLgMBBrq_0arG4RAlLPw0Xcgm5INHphUJ1dyY", "story", "GridCell", "GRID_CELL", "grid_uid_fk", "Foreign key linking to the Grid table", ""),
("IJJbbtf0QuHS0hcedbQrRLAFyXd58B61DXVNHQu0YZo", "story", "GridCell", "GRID_CELL", "grid_name", "Name of the grid this cell belongs to", ""),
("bDU7jiA3WL9-1tFtJlLPa0DNlFdznDQIHlHYZyHkk-M", "story", "GridCell", "GRID_CELL", "grid_cell_name", "Optional descriptive name for the grid cell", ""),
("poxbkwX2PYeoJwGeEFxqEzDFUeHqJHduc0wlMGAOzQs", "story", "GridCell", "GRID_CELL", "x_col_ix", "Zero-based column index (east-west direction),", ""),
("S-xxO72kAaRba8LR6A5rYDnBwu545xfL7OYDb-NK8tw", "story", "GridCell", "GRID_CELL", "y_row_ix", "Zero-based row index (north-south direction),", ""),
("kG65Klp1DUN2ANBKlSsAZGCxEYSw1w9QwX3bcQlOrdU", "story", "GridCell", "GRID_CELL", "z_up_down_ix", "Index indicating vertical position (positive for up, negative for down),", ""),
("ihWt9mTzJQxnvHkTQGRf5yuvgvujTbs67vz9Iuvdc1A", "story", "GridCell", "GRID_CELL", "grid_cell_id", "Tuple representing the x, y, z location in the Grid matrix", ""),
("UwJxb7WyzJgieKmQyG_LtN6Ip4nBqX3pJUITlcKzX5c", "story", "GridCell", "GRID_CELL", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("7lw-Z7F7VTnsyym8UMLna1Ld6lBz5J0Y2X8sRwKKBzo", "story", "GridInfo", "GRID_INFO", "grid_info_uid_pk", "Primary key, unique ID for each grid info record", ""),
("MpMvMoY2CazdExKwe9XYCT5x17YZqh1mtjtLnluUPoA", "story", "GridInfo", "GRID_INFO", "grid_uid_fk", "Foreign key linking to the Grid table", ""),
("goPWSeMxqEixD7ZEIobdurnsYwBTfkQrzHZTnSIWAk4", "story", "GridInfo", "GRID_INFO", "grid_cell_uid_fk", "Foreign key linking to the GridCell table", ""),
("B3Ax2vhZTj9pKmMOwRw--zYdtAwGxhDRMeD_YuwhYy0", "story", "GridInfo", "GRID_INFO", "grid_name", "Name of the grid this information belongs to", ""),
("b77P9cDvbruWrqjVi9aoigN5EbbgnKqltM3O6Ehpu0Y", "story", "GridInfo", "GRID_INFO", "grid_cell_name", "Name of grid cell this info is associated with", ""),
("smNJXUyd1Yn5_2lzuoGg4iijHtULOEiCbJMf4h-hljs", "story", "GridInfo", "GRID_INFO", "grid_info_id", "Short descriptive tag for the cell value", ""),
("GUCvTYYJiQJG53LCi8CdjCPz7_XgpHfBDZ5BoebllE4", "story", "GridInfo", "GRID_INFO", "grid_info_data_type", "Data type of the value (e.g., string, integer),", ""),
("d8q5L9YfklsEFzHCvFmVa1y3F84XTXyyzn1fH5GvFsQ", "story", "GridInfo", "GRID_INFO", "grid_info_name", "Label for value, providing context or description", ""),
("LGfFU1yJ-h1leqFir0isvBB_xj_5oFQVrts1FRI2f-8", "story", "GridInfo", "GRID_INFO", "grid_info_value", "Actual value, which might be binary data", ""),
("wahIjOHsS9MWusmdaWEf2Me4pMmKF9yPX96aMP8pXfY", "story", "GridInfo", "GRID_INFO", "grid_info_path", "Path for storing data outside the database", ""),
("Z_F-EkxPsSkAxInSuxBRKAYsAcm0ZignDNEIvK93VWU", "story", "GridInfo", "GRID_INFO", "delete_dt", "Deletion date, when the record was marked for deletion", ""),
("kW9rPLTPogvYyCHoCgHECiFI3mtnCrZarcv0wzWW1HA", "story", "MapXMap", "MAP_X_MAP", "map_x_map_uid_pk", "Primary key, unique ID for each map-to-map association", ""),
("b7AHWv-8aZTpovMX91f1r1z-E9ASLmahpq8mYYCv8RQ", "story", "MapXMap", "MAP_X_MAP", "map_uid_1_vfk", "Virtual foreign key representing the first map in the association", ""),
("_gzuDsSJ8mXLLukMUs-bSGFvt2d7qEnimfIcerwNF5I", "story", "MapXMap", "MAP_X_MAP", "map_uid_2_vfk", "Virtual foreign key representing the second map in the association", ""),
("qtqPaETG3SScQx6adNOkzymqW94b9oF4dcEZh9n58jo", "story", "MapXMap", "MAP_X_MAP", "touch_type", "Describes the relationship type between the two maps (e.g.,", ""),
("x-9WNBIHGDcwRC4isdiVjWpP0ELqiEUe4QGhNZM88bc", "story", "MapXMap", "MAP_X_MAP", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("tKN0B2X0kOH629ysnClWHLU3Ii7UIcm5yYqD38_yb1E", "story", "GridXMap", "GRID_X_MAP", "grid_x_map_uid_pk", "Primary key, unique identifier for", ""),
("3gRJk1rnJscIIQYRefZVv4Mn3HfhUjcncqsAws71ZYw", "story", "GridXMap", "GRID_X_MAP", "grid_uid_fk", "Foreign key representing the associated grid, indexed for performance", ""),
("ORzsgf-6dWugCI9fTgHvcBP5jfLU7HZf0_x7JNsy1u0", "story", "GridXMap", "GRID_X_MAP", "map_uid_vfk", "Virtual foreign key representing the associated map,", ""),
("fBa7EDSFCg7YKnPU7ev2J-w8yI-YVxznCwN4MsvetdE", "story", "GridXMap", "GRID_X_MAP", "delete_dt", "Deletion date, indicating when the record was", ""),
("nfkT5Vz1sNvHZ95_7S6ysq5flirwxWlGh0XTjuMV7Hw", "story", "CharSet", "CHAR_SET", "char_set_uid_pk", "Primary key, unique ID for each character set", ""),
("ffXH7nWxq7FXDAVKSV-fy3uFml3cu6XYMCcyOqfi2-o", "story", "CharSet", "CHAR_SET", "font_name", "Name of the font associated with the character set,", ""),
("_vRxFLLG3y0da_WQdGZ5OfYxq1mnvr8Un8nrhYvjyA8", "story", "CharSet", "CHAR_SET", "char_set_type", "Type of the character set, default is alphabet,", ""),
("59LsaAmoFZR-A5cc3rX19976Wdp8ihX05uaGn7u6d2s", "story", "CharSet", "CHAR_SET", "char_set_desc", "Description of the character set, providing", ""),
("jplQvmlXq7xXy33_WgVf5Yw0hMB6jf36SPU1He6hofE", "story", "CharSet", "CHAR_SET", "delete_dt", "Deletion date, indicating when the record was", ""),
("TsTSUVc5txHu2t4R-KREsuVF0q5BdU5mr7HOWTjSGg0", "story", "CharMember", "CHAR_MEMBER", "char_member_uid_pk", "Primary key, unique identifier for each character member", ""),
("fyw05pf7GDnKZdYdORwr83psw2vzz_NyDSTX7OlFqyA", "story", "CharMember", "CHAR_MEMBER", "char_set_uid_fk", "Foreign key referencing the character set this member belongs to", ""),
("KmxdkVBlNnuFcUxWivD5mLK_jOo_HWFXmcg5kWP9ito", "story", "CharMember", "CHAR_MEMBER", "char_member_name", "Name of the character member", ""),
("YqTgzWzTHPlW9u7grnRM2PpvepZzpgyRbnr0jfXQjSg", "story", "CharMember", "CHAR_MEMBER", "char_member_image", "Binary data representing the image of", ""),
("imBy8_XdxoGKenGF75P7oAfsqikrI200gKnVqVEVdng", "story", "CharMember", "CHAR_MEMBER", "char_member_path", "File path to the image or representation of the character", ""),
("EoBOU1WibE9U0QeugozTBYP-icfW55UEQZQQjsKV62Y", "story", "CharMember", "CHAR_MEMBER", "char_member_desc", "Description providing additional details about the character member", ""),
("Rr4rlxhmPVQtU9ke1H1peV5EvDKHgJ7uwj2RaV43wZE", "story", "CharMember", "CHAR_MEMBER", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("B1TKUbeT4N46niVYMWttEKgt5fvs-RGk2ghef_hSJnU", "story", "LangFamily", "LANG_FAMILY", "lang_family_uid_pk", "Primary key, unique identifier for each language family", ""),
("phqJMRyygur3TU-th0vYrOWzWKp50rQRC2jgKEZ8etY", "story", "LangFamily", "LANG_FAMILY", "char_set_uid_fk", "Foreign key referencing the character set used by the language family", ""),
("xIgr6KyvNOHjepz9cB1kXQhW9XKryHvEf5PWeeg4b4Y", "story", "LangFamily", "LANG_FAMILY", "lang_family_name", "Name of the language family", ""),
("RrP__mlBJkSGwxQy2i0xj5F_i29VQ08twutNeGksCAg", "story", "LangFamily", "LANG_FAMILY", "lang_family_desc", "Description of the language family", ""),
("aDK49fk-bIv_kp0a0nfdBVQCDEab-azv47nyM35Z1kg", "story", "LangFamily", "LANG_FAMILY", "phonetics", "Description of the phonetics of the language family", ""),
("dsNKlPpLSadlwWhfJ-kG7dQJd03edNvBZJg_6S9_Dm4", "story", "LangFamily", "LANG_FAMILY", "cultural_influences", "Description of the cultural influences on the language family", ""),
("VeqgwQaKpqOu4veqwKduHvpWq2WihZ1BLEwcRnTxfAU", "story", "LangFamily", "LANG_FAMILY", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("NSlHdgo9zaCTpOmmorZucK98lhvc8GtdyT27UY4rBT8", "story", "Language", "LANGUAGE", "lang_uid_pk", "Primary key, unique identifier for each language", ""),
("9Xwmrihprqc_UYXU1EZZLAYNfXCX5jzPQzXQqDqgFvs", "story", "Language", "LANGUAGE", "lang_family_uid_fk", "Foreign key referencing the language family this language belongs to", ""),
("mLzL2H5Wn5zRlEloanyFRPsOEJAH8f1-tZhZ6o7mogw", "story", "Language", "LANGUAGE", "lang_name", "Name of the language", ""),
("m-bgNzHDX2x958r-P6zONVEbB1wU9vJW9IMLFRSZbzM", "story", "Language", "LANGUAGE", "lang_desc", "Description of the language", ""),
("86VjhyOEfT33Ykx6Rm8McjvZe9nNFCL2JIZGn1so9kE", "story", "Language", "LANGUAGE", "gramatics", "Description of the gramatics of the language", ""),
("Kusx-_bsDYaNgVm8gjOryjAjrUB38zWScBed9-Ki8SE", "story", "Language", "LANGUAGE", "lexicals", "Description of the lexicals of the language", ""),
("F_InV8T1xFwRY-frbr2ineUF25MtR3L9RFaks7PDCUY", "story", "Language", "LANGUAGE", "social_influences", "Description of the social influences on the language", ""),
("QzvBTEmn5-o1m9hyJJJztZ1tURYY3GHZLQ4sQ5rSbU0", "story", "Language", "LANGUAGE", "word_formations", "Description of the word formations of the language", ""),
("ARYm7bj3oEVRQQXB65ghB54tpce3S8MbW4GZg8SRhAA", "story", "Language", "LANGUAGE", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("RQh_FY-9vs_qmtDGY5xBbFud8Uoj-o0-UOTTaoEO5-8", "story", "LangDialect", "LANG_DIALECT", "dialect_uid_pk", "Primary key, unique identifier for each dialect", ""),
("4WqWzQKGQvVVSsOktofT1O5NWcl9drgj4Qko6yhSDf8", "story", "LangDialect", "LANG_DIALECT", "lang_uid_fk", "Foreign key referencing the language this dialect belongs to", ""),
("k3l_gM0oeEI1g75pjMSpAFNMUA81RwuVSTnxk2mZOzs", "story", "LangDialect", "LANG_DIALECT", "dialect_name", "Name of the dialect", ""),
("maTD7lvpRGeJY7_kdP0NLDIITogo84sa2bqxF87ykWc", "story", "LangDialect", "LANG_DIALECT", "dialect_desc", "Description of the dialect", ""),
("j3Z87pHvRPahU6h1UmN42d-_cO_INeEQZXIEGidHta4", "story", "LangDialect", "LANG_DIALECT", "divergence_factors", "Description of the divergence factors of the dialect", ""),
("oMsaCbu1m0d_VNkspqXDYyRTxEfVYU03IT-SX1tegdE", "story", "LangDialect", "LANG_DIALECT", "syncretic_factors", "Description of the syncretic factors of the dialect", ""),
("oO0FCMr-Msh4h7u5NQ6ZLSbkiEg0rnOFVu8I0hJrpJI", "story", "LangDialect", "LANG_DIALECT", "preservation_factors", "Description of the preservation factors of the dialect", ""),
("BuWvik-3Max9Ffw9TTk_NqJU3vlU5lAF4_KzF8cqwoI", "story", "LangDialect", "LANG_DIALECT", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("skbcTCuNfCMZU6EzbHsFGC6Aoa2EALQUwaZX2aWrElg", "story", "GlossCommon", "GLOSS_COMMON", "gloss_common_uid_pk", "Primary key, unique identifier for each common glossary item", ""),
("j62q_THsIIRN5ow2KjFdwqeQM7JORSf4AnEsJz58DnI", "story", "GlossCommon", "GLOSS_COMMON", "dialect_uid_fk", "Foreign key referencing the dialect this glossary item belongs to", ""),
("mACMzUNNbYmyBoLXZJVG2EviP-HYkPI9JuXpBP6gI7Q", "story", "GlossCommon", "GLOSS_COMMON", "gloss_type", "Type of the glossary item", ""),
("NK83P3fCR7F10S2J2uhwegQQhVs2JnhZDSl8GP6THx8", "story", "GlossCommon", "GLOSS_COMMON", "gloss_name", "Name of the glossary item", ""),
("G4Ph5Afe6zIK203GZZBAr9eGG7gGHbtGzZDu0IK8Zqs", "story", "GlossCommon", "GLOSS_COMMON", "gloss_value", "Value of the glossary item", ""),
("A-DFrQUqh0kjz4ufBqYTZbGB8jwI23yo7rXrKsL8EHA", "story", "GlossCommon", "GLOSS_COMMON", "gloss_uri", "URI of the glossary item", ""),
("tBVKvjiH8ufydvA88lPPCjowgoovpipxLshO359AdKI", "story", "GlossCommon", "GLOSS_COMMON", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("ZslNl1FwlUG2HEz1exDtmxZ7jLNLoZnVDtbwX90JcMA", "story", "Glossary", "GLOSSARY", "glossary_uid_pk", "Primary key, unique identifier for each glossary item", ""),
("5uDO-rivVA_69YH4qoTi8gBwb4MccpeSVuQzMjKptwc", "story", "Glossary", "GLOSSARY", "gloss_common_uid_fk", "Foreign key referencing the common glossary item", ""),
("o9GEJoOJ8Sg9XyWWHJPWom4CKFgGFBgdpqOjp8XIwWc", "story", "Glossary", "GLOSSARY", "dialect_uid_fk", "Foreign key referencing the dialect this glossary item belongs to", ""),
("IvX48aVRLErUgMv1wAn2dBmuxsRdGZHKzUZCvTE-Q8s", "story", "Glossary", "GLOSSARY", "gloss_type", "Type of the glossary item", ""),
("g8I8qlAxfcEZuFnXxJSa8KTHgfWdh61MyEqwQ81opzw", "story", "Glossary", "GLOSSARY", "gloss_name", "Name of the glossary item", ""),
("VcNUcVmJz7oX-Wv3ONUxnJiuJaNReiXjNMTD6d5s7Fg", "story", "Glossary", "GLOSSARY", "gloss_value", "Value of the glossary item", ""),
("ddUq039GwiE4XDptUwZoiINLKozOspO2Ag9uFa7J6rs", "story", "Glossary", "GLOSSARY", "gloss_uri", "URI of the glossary item", ""),
("fIeHVSA9gZJoyHE10KMM1AyC6MkY4KLrvjPDlzHhml4", "story", "Glossary", "GLOSSARY", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("xUBENU_CkU-cLkmGLdYDROQ2Onprl773eATl_NgdZGw", "story", "Universe", "UNIVERSE", "univ_uid_pk", "Primary key, unique identifier for each universe", ""),
("r8HrGjiqnm8CRgcuZpE99ZLcE5DW_BJRetPjUWb15qQ", "story", "Universe", "UNIVERSE", "univ_name", "Name of the universe", ""),
("CeE_Gee917W6HJNL7VFJnt298LkDrDx3SraymO_ycaA", "story", "Universe", "UNIVERSE", "radius_gly", "Radius of the universe in gigalightyears", ""),
("KCqJb9wvpQ3lWqvUyJwOwL2_kcy6-UhQshVUlcS-8XY", "story", "Universe", "UNIVERSE", "volume_gly3", "Volume of the universe in gigalightyears cubed", ""),
("ldxi4fh7kycy6IL3TG4AuiHBZfXveAOyK2A0P67QuFk", "story", "Universe", "UNIVERSE", "volume_pc3", "Volume of the universe in parsecs cubed", ""),
("P9msu0mkdUrIBNqq_DjxvRXSDJnFMFVVvlkiCdaqx3I", "story", "Universe", "UNIVERSE", "age_gyr", "Age of the universe in gigayears", ""),
("FPPCYO76jAh-V-0qddIrHIDjQA3A0ee_QndBgLW6yrk", "story", "Universe", "UNIVERSE", "expansion_rate_kmpsec_per_mpc", "Expansion rate of the universe in km/sec per megaparsec", ""),
("jjBUQXAW5geerSYHLlTuGjxe6t6huQOqFVKwz4UJi6I", "story", "Universe", "UNIVERSE", "total_mass_kg", "Total mass of the universe in kilograms", ""),
("A2n5hUZI8zIv-33XgD_3OfY6KQ5inm-BnVARl6U9xBo", "story", "Universe", "UNIVERSE", "dark_energy_kg", "Amount of dark energy in the universe in kilograms", ""),
("rfoxMgy5JKzwZDt3uhuGEdB3vRoh6SmfRkNDG2g3XLo", "story", "Universe", "UNIVERSE", "dark_matter_kg", "Amount of dark matter in the universe in kilograms", ""),
("jNapi9IUK0PIibfwZu85rWCvSBd6HrSJqor_MNcybA8", "story", "Universe", "UNIVERSE", "baryonic_matter_kg", "Amount of baryonic matter in the universe in kilograms", ""),
("Xt_mADKleNegh-QE25F7x1RtrTAKYwVgoyk6qSI4ySM", "story", "Universe", "UNIVERSE", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("VwJ0RPTiRnLf6CuiDlqwMAj7sKmGrbb217-_S9PSDrk", "story", "ExternalUniv", "EXTERNAL_UNIVERSE", "external_univ_uid_pk", "Primary key, unique identifier for each external universe", ""),
("CowBFU0lr75jNQLtW17lJLin8bH46eNuWVkyTOgnZbU", "story", "ExternalUniv", "EXTERNAL_UNIVERSE", "univ_uid_fk", "Foreign key linking to the Universe table", ""),
("qWg0mO2MvvZ3Azk2PqcqLQXsdl1JO-uge-jnlnnv7y8", "story", "ExternalUniv", "EXTERNAL_UNIVERSE", "external_univ_name", "Name of the external universe", ""),
("E59lfVwoN35RVCdmhFVFMNIp2OMr3V6WJyk-agG2c4w", "story", "ExternalUniv", "EXTERNAL_UNIVERSE", "mass_kg", "Mass of the external universe in kilograms", ""),
("NgGj-_E4A_0b1weq8_nsXo5YnvDa2SdyOfrqWzdPn3s", "story", "ExternalUniv", "EXTERNAL_UNIVERSE", "dark_energy_kg", "Amount of dark energy in the external universe in kilograms", ""),
("n5m6oFCp6S8jjMNHkqPjHjohnAQ9wLyiYRZ_AlXRi9A", "story", "ExternalUniv", "EXTERNAL_UNIVERSE", "dark_matter_kg", "Amount of dark matter in the external universe in kilograms", ""),
("J4CvsKOB0TdmmUG6RLmTmZy1QuSidbJHBlbUJ6s-GEo", "story", "ExternalUniv", "EXTERNAL_UNIVERSE", "baryonic_matter_kg", "Amount of baryonic matter in the external universe in kilograms", ""),
("vvMNQAssG1-m3ay-yz52K2r4JbahF25HdWBK_fH79lo", "story", "ExternalUniv", "EXTERNAL_UNIVERSE", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("szSwGBDPweBJcy-yz4m0sxgJ1nuSgd2WWeMmLGRNdJo", "story", "GalacticCluster", "GALACTIC_CLUSTER", "galactic_cluster_uid_pk", "Primary key, unique identifier for each galactic cluster", ""),
("xeQoau1fJIA7f8MePj3BHUy_gxeeNuiY_-ixBEYqYu4", "story", "GalacticCluster", "GALACTIC_CLUSTER", "univ_uid_fk", "Foreign key linking to the Universe table", ""),
("1raTMO3iyBlbc8781f1g6PyLMH62UtfMzl5zyUUtux0", "story", "GalacticCluster", "GALACTIC_CLUSTER", "galactic_cluster_name", "Name of the galactic cluster", ""),
("dZHRiwMWOJXhJYlgpaH_Lr-PLUxYT1imxB5eXrDwuWQ", "story", "GalacticCluster", "GALACTIC_CLUSTER", "center_from_univ_center_gly_x", "X coordinate of the center of the cluster in gigalightyears", ""),
("LZw0Szan9b7jutcVDRPQKVNz-qXBL9a4gS9Sw7IOVY4", "story", "GalacticCluster", "GALACTIC_CLUSTER", "center_from_univ_center_gly_y", "Y coordinate of the center of the cluster in gigalightyears", ""),
("jilfVeaD-5YAHYyLc5j7y_X4Gtr0Gz5xGMefuuhQqco", "story", "GalacticCluster", "GALACTIC_CLUSTER", "center_from_univ_center_gly_z", "Z coordinate of the center of the cluster in gigalightyears", ""),
("4r-F8itLOUMyJ-Qyl3zaaa7qRT2LQ1QR6GsazMh9V_M", "story", "GalacticCluster", "GALACTIC_CLUSTER", "boundary_gly_x", "X coordinate of the boundary of the cluster in gigalightyears", ""),
("wW2hwlC-Sto0GdG7kbz2OV2cYRr0ssoKSfIuOeFbgJ4", "story", "GalacticCluster", "GALACTIC_CLUSTER", "boundary_gly_y", "Y coordinate of the boundary of the cluster in gigalightyears", ""),
("XuAIsAPtMNeAlIFQgDgojafQ8pFrrT8UAUmtOE0rgxc", "story", "GalacticCluster", "GALACTIC_CLUSTER", "boundary_gly_z", "Z coordinate of the boundary of the cluster in gigalightyears", ""),
("PGVU1mTG4knbuhxGKHzHTUmrsdt8qQ9B47kxJq1ASEo", "story", "GalacticCluster", "GALACTIC_CLUSTER", "cluster_shape", "Shape of the cluster, default is ellipsoid", ""),
("pxu5nWHPMZPBafJo8Cvt0QKe9uL6pLwlxEIzB69XKao", "story", "GalacticCluster", "GALACTIC_CLUSTER", "shape_pc_x", "X coordinate of the shape of the cluster in parsecs", ""),
("_lYiuIssOJdcMrW_eDBmvl4uULLsD6PIJIKBj3yjCZ4", "story", "GalacticCluster", "GALACTIC_CLUSTER", "shape_pc_y", "Y coordinate of the shape of the cluster in parsecs", ""),
("c5GvSYKfDcsUjzEqIeFKpAokKcaI69dNm5ud8jMO9B4", "story", "GalacticCluster", "GALACTIC_CLUSTER", "shape_pc_z", "Z coordinate of the shape of the cluster in parsecs", ""),
("uKs2LoFemVXp4tfvZvSy2OLG_bczOBtoC_vALOdb2co", "story", "GalacticCluster", "GALACTIC_CLUSTER", "shape_axes_a", "Length of the major axis of the cluster in parsecs", ""),
("sTtzDUSqYpxjd2gBtWphY5ymGeidcsqMgygj_yCqD-U", "story", "GalacticCluster", "GALACTIC_CLUSTER", "shape_axes_b", "Length of the minor axis of the cluster in parsecs", ""),
("Mh0tMCGoY-Mo5O3WusPsaQTpTrNg4BoFNdIrkrKb9q4", "story", "GalacticCluster", "GALACTIC_CLUSTER", "shape_axes_c", "Length of the tertiary axis of the cluster in parsecs", ""),
("Sr796BpnezIo91E5wb_8qQ8EdMUlJxzvwH35roPL8aU", "story", "GalacticCluster", "GALACTIC_CLUSTER", "shape_rot_pitch", "Pitch rotation of the cluster in degrees", ""),
("miVefYxjIv5wgT5xH1S2Pp--8EtMVUD_LZ2nCn8EVFE", "story", "GalacticCluster", "GALACTIC_CLUSTER", "shape_rot_yaw", "Yaw rotation of the cluster in degrees", ""),
("1GHZt15GtwePUYWirt-lh3GK2OtbhUAV41Zu6eT6gUQ", "story", "GalacticCluster", "GALACTIC_CLUSTER", "shape_rot_roll", "Roll rotation of the cluster in degrees", ""),
("CjpDsnP0z0poR9LRFLO1ea70jp7glEKJZkDkutaQYeA", "story", "GalacticCluster", "GALACTIC_CLUSTER", "volume_pc3", "Volume of the cluster in parsecs cubed", ""),
("iDXe75wjuncVwPEJLlXqaYV-eBHxlbvoVH24OurF-pw", "story", "GalacticCluster", "GALACTIC_CLUSTER", "mass_kg", "Mass of the cluster in kilograms", ""),
("-SGMoU-AMifXu4Um6QZsWDRYAAZZ2o_DNGVhDVGNIe8", "story", "GalacticCluster", "GALACTIC_CLUSTER", "dark_energy_kg", "Amount of dark energy in the cluster in kilograms", ""),
("fDKlv4QRq5rI6rMZ6i7_Qtz9MIq6RtU-mAW2jk2pHNQ", "story", "GalacticCluster", "GALACTIC_CLUSTER", "dark_matter_kg", "Amount of dark matter in the cluster in kilograms", ""),
("FqX_8dnf6jwpYW-Rbs7erWZcGppyTTbGmoBNx_Omfqc", "story", "GalacticCluster", "GALACTIC_CLUSTER", "baryonic_matter_kg", "Amount of baryonic matter in the cluster in kilograms", ""),
("apEjCOE4BpBgGs0Mhqiqfchl_wVuBLhfInnfhdo2MNs", "story", "GalacticCluster", "GALACTIC_CLUSTER", "timing_pulsar_pulse_per_ms", "Timing of the pulsar pulse in milliseconds", ""),
("ZkVDYEm5EKK8D6Jv668IU3PoknwXtBtWp0XyWVUVdJM", "story", "GalacticCluster", "GALACTIC_CLUSTER", "timing_pulsar_loc_gly_x", "X coordinate of the pulsar location in gigalightyears", ""),
("GGCcA2xo8rxCzUet39beaGuEruza8S2e3gcLNZq94Xw", "story", "GalacticCluster", "GALACTIC_CLUSTER", "timing_pulsar_loc_gly_y", "Y coordinate of the pulsar location in gigalightyears", ""),
("_40cKyAe9a-6hlk7monvlFWeSYgFAvSRrngtlHXy0UE", "story", "GalacticCluster", "GALACTIC_CLUSTER", "timing_pulsar_loc_gly_z", "Z coordinate of the pulsar location in gigalightyears", ""),
("Voy6U9Rw6UEesutHE0RyknEA7BVp6Qs4z9wlDXpZiVw", "story", "GalacticCluster", "GALACTIC_CLUSTER", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("eXiDpRuAXOkyuzdPK6CWT6jKsd7anjiTKXZn8U-gWAQ", "story", "Galaxy", "GALAXY", "galaxy_uid_pk", "Primary key, unique identifier for each galaxy", ""),
("q2H1ISHzbnTcQYmqKyM6fAVyCWobFt99VAzvZmv-PHo", "story", "Galaxy", "GALAXY", "galactic_cluster_uid_fk", "Foreign key linking to the Galactic Cluster table", ""),
("DQSv7m1x6W0t40x6jV-EEqC5GiUBRysk367FVyvzCvQ", "story", "Galaxy", "GALAXY", "galaxy_name", "Name of the galaxy", ""),
("QFh17GDjjypIi5-MHzOpbziOuYGNTYdJ4YY4zfF07L4", "story", "Galaxy", "GALAXY", "relative_size", "Relative size of the galaxy, default is medium", ""),
("divyNdPYyfXnmOKKR0S-70IDN5-ueQmkVLfpEmLlh_Q", "story", "Galaxy", "GALAXY", "center_from_univ_center_kpc_x", "X coordinate of the center of the galaxy in kiloparsecs", ""),
("ygxxK12jtOkr-Nzr4JLUe0gixpgf4YPcUvkeaSB1vjo", "story", "Galaxy", "GALAXY", "center_from_univ_center_kpc_y", "Y coordinate of the center of the galaxy in kiloparsecs", ""),
("JfZEVsUDstnKXJ-NdZhsvilxyDZ1U0FsS7k2dO7yDb4", "story", "Galaxy", "GALAXY", "center_from_univ_center_kpc_z", "Z coordinate of the center of the galaxy in kiloparsecs", ""),
("8_n1gxSqcEUl2PaXdWU-fRyHUS92WXudpikxaPkTouU", "story", "Galaxy", "GALAXY", "halo_radius_pc", "Radius of the halo of the galaxy in parsecs", ""),
("Yp9GMAoSoDuUySaKkdkM9D47a5cqtLE4AjDkHGsgr3c", "story", "Galaxy", "GALAXY", "boundary_pc_x", "X coordinate of the boundary of the galaxy in parsecs", ""),
("shFq9b6Fz9Cv9cjB-q5VGl1X6Adndjtz8AU4BklxQGQ", "story", "Galaxy", "GALAXY", "boundary_pc_y", "Y coordinate of the boundary of the galaxy in parsecs", ""),
("Sc7QRlS0-bhlf1rr0WWa6_uumdATYVmTlfuqoU8hXgM", "story", "Galaxy", "GALAXY", "boundary_pc_z", "Z coordinate of the boundary of the galaxy in parsecs", ""),
("W_tZE3YGnyGgPeNaGGPQv9TnwmeDGX-rrvrpJRY6YZQ", "story", "Galaxy", "GALAXY", "volume_gpc3", "Volume of the galaxy in gigaparsecs cubed", ""),
("tSfpKQvoFLuMkzhs_6El_ErAg0isPN7FoCpBISShpgU", "story", "Galaxy", "GALAXY", "mass_kg", "Mass of the galaxy in kilograms", ""),
("0fCRoQWukzjoaiA5M9Em3tT99FN6o6Xn3CVescFsFw8", "story", "Galaxy", "GALAXY", "bulge_shape", "Shape of the bulge of the galaxy, default is ellipsoid", ""),
("eh7EiRUiOTimSI6yezPpF0LCqRqyh3IyHjIjdmFYZG0", "story", "Galaxy", "GALAXY", "bulge_center_from_center_ly_x", "X coordinate of the center of the bulge", ""),
("OQfNr-yI8mhk-RxCS-19rTiNPj9igFj9aaP7NN_7OfA", "story", "Galaxy", "GALAXY", "bulge_center_from_center_ly_y", "Y coordinate of the center of the bulge", ""),
("GzDIf2hIhnvFR0K_4N6pz5z6hS53E1aF7Ikwd1krZKQ", "story", "Galaxy", "GALAXY", "bulge_center_from_center_ly_z", "Z coordinate of the center of the bulge", ""),
("iCOnMG3BovtuoXFtXbj1tyUn0Va-ysXExrlRvQYvjoM", "story", "Galaxy", "GALAXY", "bulge_dim_axes_a", "Length of the major axis of the bulge in lightyears", ""),
("rml5zxgSw01dNbrY381a4bnLyeg5XYS9_0TnOqKxy38", "story", "Galaxy", "GALAXY", "bulge_dim_axes_b", "Length of the minor axis of the bulge in lightyears", ""),
("eEFuBs0e0j2DNcjabwhx26uwn10Fvrzc4loYSkRUr34", "story", "Galaxy", "GALAXY", "bulge_dim_axes_c", "Length of the tertiary axis of the bulge in lightyears", ""),
("T_PteNWfpA7lWpX95QlbrLHX-INgarPvhLkivmwIRuw", "story", "Galaxy", "GALAXY", "bulge_dim_rot_pitch", "Pitch rotation of the bulge in degrees", ""),
("Cw_DgFyAWY6d7aSBehROwa8adeHFHnOhkUhAgMSP2KA", "story", "Galaxy", "GALAXY", "bulge_dim_rot_yaw", "Yaw rotation of the bulge in degrees", ""),
("-Kxlg4qr0KU4fxyYevLfV_k1dlzjDctQMsf7WUDq5fE", "story", "Galaxy", "GALAXY", "bulge_dim_rot_roll", "Roll rotation of the bulge in degrees", ""),
("M_E7UqfGKbAJsAltvw6OctpdQt2O4XAQ-8Iurx9AYQY", "story", "Galaxy", "GALAXY", "bulge_black_hole_mass_kg", "Mass of the black hole in the bulge in kilograms", ""),
("afw-z0DGei1RiqV4BuvlbvfnWeGkMGPSzIQVtkIHjgI", "story", "Galaxy", "GALAXY", "bulge_volume_ly3", "Volume of the bulge in lightyears cubed", ""),
("KOrJtkCrSQ0kNX1E8eAOy0cSgytpfnn1iR15p7JhSYk", "story", "Galaxy", "GALAXY", "bulge_total_mass_kg", "Total mass of the bulge in kilograms", ""),
("I7TBzR5_FqxLFzSPXzgWac-VuLLCJdeWlo51VLsHSrg", "story", "Galaxy", "GALAXY", "star_field_shape", "Shape of the star field of the galaxy, default is ellipsoid", ""),
("fsu8icZHGKs0YATgfRB2Ga-hH7dUOXSWNwEcamJqFGc", "story", "Galaxy", "GALAXY", "star_field_dim_from_center_ly_x", "X coordinate of the center of the star field", ""),
("ZVwUUW_7L4vDLnS9sVloZiOqk57EckuBoGczExPJEjY", "story", "Galaxy", "GALAXY", "star_field_dim_from_center_ly_y", "Y coordinate of the center of the star field", ""),
("aV8Kj2hV5_-_23oqEaSsGu5dAIzVmOLHSg5ObyPWC0I", "story", "Galaxy", "GALAXY", "star_field_dim_from_center_ly_z", "Z coordinate of the center of the star field", ""),
("b7YKumWECsEz3fU5nY1x622WLLG73YUQ4FjjYMXbnus", "story", "Galaxy", "GALAXY", "star_field_dim_axes_a", "Length of the major axis of the star field in lightyears", ""),
("3-8H-ua9LUDJShwko8_karnzmpJmDqjD23mhDCEl5JQ", "story", "Galaxy", "GALAXY", "star_field_dim_axes_b", "Length of the minor axis of the star field in lightyears", ""),
("JnvMR7l86dKC61ELgNlFnc1uQtpEVL0VMuWegX66C-c", "story", "Galaxy", "GALAXY", "star_field_dim_axes_c", "Length of the tertiary axis of the star field in lightyears", ""),
("-KrBhAcY2ej_70Sy1dFSyVosDIgSH6CBQ6_pA9ZVglc", "story", "Galaxy", "GALAXY", "star_field_dim_rot_pitch", "Pitch rotation of the star field in degrees", ""),
("_q-2xhLnBAfU3i8O_mkyHR4IfTHja3blbCm_qjdyjck", "story", "Galaxy", "GALAXY", "star_field_dim_rot_yaw", "Yaw rotation of the star field in degrees", ""),
("0xtHtQoOfdeGKXNcqC5Lg213-jgztrXbId2-bNTtMgc", "story", "Galaxy", "GALAXY", "star_field_dim_rot_roll", "Roll rotation of the star field in degrees", ""),
("NqKNjura2Vsfe3U6DiI1_JgpZvDKsJwggU26rKfNHws", "story", "Galaxy", "GALAXY", "star_field_vol_ly3", "Volume of the star field in lightyears cubed", ""),
("_VPIyL_e9NOCrcJDizjI4BM6fdh4roNa4TuBqYElbm0", "story", "Galaxy", "GALAXY", "star_field_mass_kg", "Mass of the star field in kilograms", ""),
("-Ac4togk1Mhk_EMw6T323dFO1f_BaQEwxbvzjyhJH70", "story", "Galaxy", "GALAXY", "interstellar_mass_kg", "Mass of", ""),
("2VCmOaPsW44ABLsG14uDYTePsSmNakxtY4zj1eTgOkM", "story", "Galaxy", "GALAXY", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("mcpeX5_k81VeBvdSvxDlCVVNJ_4VNdfzFU4XrSmM9cQ", "story", "StarSystem", "STAR_SYSTEM", "star_system_uid_pk", "Primary key, unique identifier for each star system", ""),
("Va7t7oSuCzyS8sYgw7LMpgTFCPiGAUIpw8Af3htBXfI", "story", "StarSystem", "STAR_SYSTEM", "galaxy_uid_fk", "Foreign key linking to the Galaxy table", ""),
("zyk04uqPXoxgnqvzADz-Esax_MP1JQ0dr1ByzDW-15Y", "story", "StarSystem", "STAR_SYSTEM", "star_system_name", "Name of the star system", ""),
("-ThI-Zut98e5DrT5ypRvnzOcr-Ov-YMtgxEuIpw51bg", "story", "StarSystem", "STAR_SYSTEM", "is_black_hole", "Indicates if the star system contains a black hole", ""),
("NZQ9ZbmF3yeQVewU0KErZZigXZnDrGudM2Au3ho19gc", "story", "StarSystem", "STAR_SYSTEM", "is_pulsar", "Indicates if the star system contains a pulsar", ""),
("VQpmoWf4OSr-oNBGeEQJh3MCNnrFKlZoZxhphUC_V2k", "story", "StarSystem", "STAR_SYSTEM", "boundary_pc_x", "X coordinate of the boundary of the star system in parsecs", ""),
("tBNf_I5h-IHOCx8qZZxf13qsTVKiCAHQVWVjoMqojwc", "story", "StarSystem", "STAR_SYSTEM", "boundary_pc_y", "Y coordinate of the boundary of the star system in parsecs", ""),
("gGXtDtJ1EhNu7aEeAveGhBG5xnb3Myj1xMPOoISukTc", "story", "StarSystem", "STAR_SYSTEM", "boundary_pc_z", "Z coordinate of the boundary of the star system in parsecs", ""),
("ayh1yoQe8Kolom6zpR_iJYCIBfsZBI54oMoS_oodZjs", "story", "StarSystem", "STAR_SYSTEM", "volume_pc3", "Volume of the star system in parsecs cubed", ""),
("DO1zHwVJMAw6Y3PDZm781LaHM121Nh1qnNOcXfYx2qk", "story", "StarSystem", "STAR_SYSTEM", "mass_kg", "Mass of the star system in kilograms", ""),
("vQlRMoMuy25ZTJqKCaEoKi8ykIXmEyCd0iwVzGzBzz8", "story", "StarSystem", "STAR_SYSTEM", "system_shape", "Shape of the star system, default is ellipsoid", ""),
("NoSw1pcW7psSWIn5eEI3_iZOf4Tgh3HSWffvKWkUr3I", "story", "StarSystem", "STAR_SYSTEM", "center_from_galaxy_center_pc_x", "X coordinate of the center of the star system", ""),
("2vsMuW9q31olpWs67qTroI0F9ajOifV-VD7et_fmSr4", "story", "StarSystem", "STAR_SYSTEM", "center_from_galaxy_center_pc_y", "Y coordinate of the center of the star system", ""),
("Zc3OjNVKMcSJQ9lFyLznD6qSRAbRXbV8Ak_n_ZhSeB8", "story", "StarSystem", "STAR_SYSTEM", "center_from_galaxy_center_pc_z", "Z coordinate of the center of the star system", ""),
("hOzKerNUI3B4zZ71sp26uQLiUOlx_5zGIv9Se7-1nxQ", "story", "StarSystem", "STAR_SYSTEM", "system_dim_axes_a", "Length of the major axis of the star system in parsecs", ""),
("I_PqMFsrEVKQHXP4BHcGGer2bZSAGiqsTWeu_WjGSKY", "story", "StarSystem", "STAR_SYSTEM", "system_dim_axes_b", "Length of the minor axis of the star system in parsecs", ""),
("KCrod6PIJ43S0K9-Ts6hyv9BkskUvL11X24a1dIwkkw", "story", "StarSystem", "STAR_SYSTEM", "system_dim_axes_c", "Length of the tertiary axis of the star system in parsecs", ""),
("WZazxDn7CW5a42mXrNYn-BmzNKPFamFzbcBcRKNrJ40", "story", "StarSystem", "STAR_SYSTEM", "system_dim_rot_pitch", "Pitch rotation of the star system in degrees", ""),
("t0JlTuSp4dyFzy1564AyF5vYHh8zJVsQhj20Lt29xac", "story", "StarSystem", "STAR_SYSTEM", "system_dim_rot_yaw", "Yaw rotation of the star system in degrees", ""),
("Q_62Ac49IV0Kdn3Bp0HIP3VuSVrKixDtLKoBOMG3KbE", "story", "StarSystem", "STAR_SYSTEM", "system_dim_rot_roll", "Roll rotation of the star system in degrees", ""),
("nMDbVE-pYItyPIfNjx03M11T4FTKp6nq8gFyI_dju1w", "story", "StarSystem", "STAR_SYSTEM", "relative_size", "Relative size of the star system, default is medium", ""),
("m1ynDnd5U64aUFh_2e8AbXov7vAE4GFxspkhN2ugcMc", "story", "StarSystem", "STAR_SYSTEM", "spectral_class", "Spectral class of the star, default is G", ""),
("u8RYgF32TgqhKPxJ8AaEYrQ0nvk2l4gyRYQ1yDhVx0I", "story", "StarSystem", "STAR_SYSTEM", "aprox_age_gyr", "Approximate age of the star system in gigayears", ""),
("_9UUCiuWM6pWe2jdu1xLtrzLWsNOyuBQ3OcEdW8M6S0", "story", "StarSystem", "STAR_SYSTEM", "luminosity_class", "Luminosity class of the star, default is V", ""),
("x7Yg6wIUDokdTuret8DVz50SGjy7UjriWnQCNnICveY", "story", "StarSystem", "STAR_SYSTEM", "frequency_of_flares", "Frequency of solar flares, default is rare", ""),
("EzKrGJ47rWPRm7vxfephnV_gyuaQAZccDR0g8ESBxww", "story", "StarSystem", "STAR_SYSTEM", "intensity_of_flares", "Intensity of solar flares, default is low", ""),
("1wObnng35lapiGqU-mwqoWAoSx-HA3fa9Pk9OiXlZEc", "story", "StarSystem", "STAR_SYSTEM", "frequency_of_comets", "Frequency of comets, default is rare", ""),
("fDHnzWSlwx7EzcTI98PQnabBKCnutT0EV8x75tNa3ds", "story", "StarSystem", "STAR_SYSTEM", "unbound_planets_cnt", "Number of unbound planets in the star system", ""),
("l4U-PVx01RKBI4iBGzcn-snMilk_MmmUEYHjRElFed0", "story", "StarSystem", "STAR_SYSTEM", "orbiting_planets_cnt", "Number of planets orbiting the star", ""),
("ZHalMHXuZZkIsCNk7F2IT5NGRgirITE0XPCf_uhbCxo", "story", "StarSystem", "STAR_SYSTEM", "inner_habitable_boundary_au", "Inner boundary of the habitable zone in astronomical units", ""),
("NJy14z54Cv0rHGYZVQjcGIdEb034FveSaHCrGFI3I2g", "story", "StarSystem", "STAR_SYSTEM", "outer_habitable_boundary_au", "Outer boundary of the habitable zone in astronomical units", ""),
("X41ry1v1okoKPZ6bGCwbPa2ZayYpqAvbLL-eAUPClFk", "story", "StarSystem", "STAR_SYSTEM", "planetary_orbits_shape", "Shape of the planetary orbits, default is circular", ""),
("IuUmd6pbHhXKGrOTNzWJhdwvfDpOG8qBDJBtbWKuus8", "story", "StarSystem", "STAR_SYSTEM", "orbital_stability", "Stability of the planetary orbits, default is stable", ""),
("mwKoU8dYlKVhZU-sGAIuVbv3XCkh8gdF-4_LLB1ALAY", "story", "StarSystem", "STAR_SYSTEM", "asteroid_belt_density", "Density of the asteroid belt, default is sparse", ""),
("x9HaQS9A9N982bmA0WPRxHhKYkhF46RbIZXVhDTmOkI", "story", "StarSystem", "STAR_SYSTEM", "asteroid_belt_loc", "Location of the asteroid belt, default is inner", ""),
("nsC6PD8jmW-MmqVL3mkwt8p5b1P3tKBqlsZG1o5jcw0", "story", "StarSystem", "STAR_SYSTEM", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("APrP9EDukD2GyhpJLmJy78l5N1ymCDoFz0oCRM4WNVw", "story", "World", "WORLD", "world_uid_pk", "Primary key, unique identifier for each world", ""),
("v6VHBxQce0P6BcdNwziNeY0g6jio0XYWYTT5xaS6WCc", "story", "World", "WORLD", "star_system_uid_fk", "Foreign key referencing the Star System table", ""),
("2Xez76sQBmsmFSoGU-Agd5CBDkJDLET7sz_4gVdNuqM", "story", "World", "WORLD", "world_name", "Name of the world", ""),
("ALPXeXZzBBXEwt08vbYai3cbnebYWkhu2-tQfFE525M", "story", "World", "WORLD", "world_type", "Type of the world, default is habitable", ""),
("j3wheKpdo8faOnWY7rlqjq8J8V4VdjU0QvLQkYfPPzg", "story", "World", "WORLD", "obliquity_dg", "Axial tilt of the world in degrees", ""),
("EaRIqAn9754KCt_nH_HzsNqZiDPJS1KtSV33me1xf9c", "story", "World", "WORLD", "distance_from_star_au", "Distance from the star in astronomical units", ""),
("i33dPSFiJ-wohmUVyKRWI_ozpLE7htp4iAjX5lW6FN0", "story", "World", "WORLD", "distance_from_star_km", "Distance from the star in kilometers", ""),
("fLlcEKUDQYv9DLaih79qPhlHVCxj6iCbNF42MSY9YNw", "story", "World", "WORLD", "radius_km", "Radius of the world in kilometers", ""),
("uPGMR1cWW_z6k8gV5B4f2BHNZnTM7elvZAmRz6aLSWM", "story", "World", "WORLD", "mass_kg", "Mass of the world in kilograms", ""),
("7Y2qTpIb-5t7XgoPZ1v0w_1ohcfXsIoEID87gx6J4fs", "story", "World", "WORLD", "gravity_m_per_s_per_s", "Gravity of the world in meters per second squared", ""),
("M4eC4mjtRM9ii1mAIKnO932NUXBPiaFGrv3BRNVq2xo", "story", "World", "WORLD", "orbit_gdy", "Orbital period of the world in galactic days", ""),
("ps-MwW571DodKa8W1pTk9A0c3wOk65rF9fVjPff0Qek", "story", "World", "WORLD", "orbit_gyr", "Orbital period of the world in galactic years", ""),
("cTW0Vj37BuKCms7Qk_WONC2v0vKMVmCamLKyf4ehJ1Q", "story", "World", "WORLD", "is_tidally_locked", "Indicates if the world is tidally locked", ""),
("1QW57SVkoesK7BtuBNZuUhOvGclXX257AJRfbpq2T6U", "story", "World", "WORLD", "rotation_gdy", "Rotation period of the world in galactic days", ""),
("-kUdwn0HybmektaW1ePCYVy0jgwMu7DEdgSxXxgyg4w", "story", "World", "WORLD", "rotation_direction", "Direction of rotation, default is prograde", ""),
("S1Ru_oSNX_wZw-AoUoRGfEj_0v3WcqUtjS_GQbGK8WA", "story", "World", "WORLD", "orbit_direction", "Direction of orbit, default is prograde", ""),
("QeXAnDEBIBU2oy8Dywtt9KQVsO6SMjE-ycaSj_6JL4w", "story", "World", "WORLD", "moons_cnt", "Number of moons orbiting the world", ""),
("Zibhop1ahb1UXMLaTtSza5K5rvv30Kn9OQOojuV5c5s", "story", "World", "WORLD", "world_desc", "Description of the world", ""),
("0u7khBHZQbkSvlHwTZuMZFybe5a6QoTx_2G8Yzk85xQ", "story", "World", "WORLD", "atmosphere", "Composition of the atmosphere", ""),
("594PTeYcHqw7dvS_AIu0W6M23VAwFn1Xlh9vF4ZAZ3I", "story", "World", "WORLD", "sky_color", "Color of the sky", ""),
("CQJ0DUwnK4yFglsbiQBe9MG-HdzGmSmp7TqRyb5WJzs", "story", "World", "WORLD", "biosphere", "Presence of life forms", ""),
("9bO9G7vLHUpuNdwmHib8-kdnQp3Pb6vjB-3MbgjhyaQ", "story", "World", "WORLD", "sentients", "Presence of intelligent life", ""),
("s8SgH5gEd4zB_W6Lh4su6EPUVmoJD48Majlo_f9sEsk", "story", "World", "WORLD", "climate", "Climate of the world", ""),
("m6zREo43prTxO953bY_p7d7AtmM6X8KFc_NLkxFZcCE", "story", "World", "WORLD", "tech_level", "Technological level of the world", ""),
("OeOU6_y-YfKxBzuBcLQNuab85ymGzzGsSShpIqD0Bt8", "story", "World", "WORLD", "terrain", "Terrain of the world", ""),
("Ljn2ja1LYriDAq1gp69p3RPzeA77gcpFrdRxGOA6_YQ", "story", "World", "WORLD", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("PNzlQ8UXUOjhqaebLps94L5cZvGFE7qH42GPceDVNoY", "story", "Moon", "MOON", "moon_uid_pk", "Primary key, unique identifier for each moon", ""),
("ioBV_Xn6JG9ywalUbrhmUk1tYwrId1IHu4ANN5lQc_4", "story", "Moon", "MOON", "world_uid_fk", "Foreign key referencing the World table", ""),
("76DFgcUKfI3L0JZ8dkzNDV1v3kp67gO5FEZSM535g0E", "story", "Moon", "MOON", "moon_name", "Name of the moon in Common language glossary", ""),
("MzjozLU0A3wDRQKo_WylHhjjoB5iCGpeX5yNy-Fbxwc", "story", "Moon", "MOON", "moon_desc", "Description of the moon", ""),
("1OeEpxMZsF5Az7bi0A2TMOwdnrdOmd8dqmljoV9atnI", "story", "Moon", "MOON", "moon_lore", "Lore of the moon", ""),
("0jPak9EzNcbyCWfpo16XfZtTzN33_8DPE79T41S1QkA", "story", "Moon", "MOON", "center_from_world_center_km", "Distance from the center of the world in kilometers", ""),
("4ZWXZTAHGmS9IRWAoj6pQTWE7bQrGZWO9S5xe1_bw9w", "story", "Moon", "MOON", "mass_kg", "Mass of the moon in kilograms", ""),
("-xZjSDVuP8UwzT2TjV8RwG-wJCh26-mCW-elMfWi_4Y", "story", "Moon", "MOON", "radius_km", "Radius of the moon in kilometers", ""),
("EbT0MLHZ7YcwaUGiR75XsFEFEEreByzqtkISv-floOE", "story", "Moon", "MOON", "obliquity_dg", "Axial tilt of the moon in degrees", ""),
("P63h_DL5lJyyQsoH5jp9t0qhv-QkLK6T3fHZsgMoZwE", "story", "Moon", "MOON", "is_tidally_locked", "Indicates if the moon is tidally locked", ""),
("kxqi9Tfuy-wz9LGLuoHMZQzTUhof09xBsQGre5ziNY0", "story", "Moon", "MOON", "rotation_direction", "Direction of rotation, default is prograde", ""),
("T6avKqalsfuTmLy4TXRXaD0fDD9K_EayqdxDcVUb_Sc", "story", "Moon", "MOON", "orbit_direction", "Direction of orbit, default is prograde", ""),
("infLMvcjtkudEljvJhFPlmoW4-nRf5g4jvzhydsTfsM", "story", "Moon", "MOON", "orbit_world_days", "Orbital period of the moon in world days", ""),
("l7-BlZaREq6_gjFe1RxIbwJFibew141KVxTtaiRKV1Y", "story", "Moon", "MOON", "rotation_world_days", "Rotation period of the moon in world days", ""),
("JbF8I1_4mObubvNhmZThXjYq1YzF_63K-OeqLOHQE-E", "story", "Moon", "MOON", "initial_velocity", "Initial velocity of the moon in meters per second", ""),
("5YCAWeTfQgmeOO8EJd_8_o0LU-37JHPHSuEFX9jmbkA", "story", "Moon", "MOON", "angular_velocity", "Angular velocity of the moon in radians per second", ""),
("mRFt09dOzGcJLHw_heo-OkKURdHds8ITmYhNIWKGThM", "story", "Moon", "MOON", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("ZV0JfEOq2gyd2ajX3vNbvEez7yr5OmmUd_k9Hdcf7I4", "story", "Lake", "LAKE", "lake_uid_pk", "Primary key, unique identifier for each lake", ""),
("zxe-3AVf--BMRWkZXkAmdA9xOZ8RpV8ncRJb-r3ebVc", "story", "Lake", "LAKE", "gloss_common_uid_vfk", "Foreign key linking to the Common Glossary table", ""),
("Kmk7t00AQt8opWMwKakE3soj4SG4iX_FBFZTLbQkYrU", "story", "Lake", "LAKE", "lake_name", "Name of the lake", ""),
("uemwNQhlqjIVtVGmuILbLKhtakUN_kLVKvbgcaTVHrE", "story", "Lake", "LAKE", "lake_shoreline_points_json", "JSON of the lake shoreline points", ""),
("iQ35rFjaV_TAKaUUa61k3WuhMKhnIvMluZhC-ZYR7oo", "story", "Lake", "LAKE", "lake_size", "Size of the lake", ""),
("YRqJTRrmMXVLp_J-amjpUOlvbnETzgty3hehFnI67Hs", "story", "Lake", "LAKE", "water_type", "Type of water", ""),
("KTEYYfPCfnUOHdcpP7P-CmprVHd6h4ZyCeTpDiDm2us", "story", "Lake", "LAKE", "lake_type", "Type of lake", ""),
("xIySSHXPH9Gx4ICmJcGO972p0jX4dwgFFhgcbBa1T84", "story", "Lake", "LAKE", "is_tidal_influence", "Indicates if the lake has tidal influence", ""),
("SA_jXxNX_WU7Nd0Km-_V67pjcF9L3B6TA-UUsni_Gh0", "story", "Lake", "LAKE", "lake_surface_m2", "Surface area of the lake", ""),
("Srmjoz1n9erUCmlWe4Y2waSwt_q73K6Shx6E27Pl0jo", "story", "Lake", "LAKE", "max_depth_m", "Maximum depth of the lake", ""),
("sYeM2_uuLJcRSCP48mjgf-IwT0y-bpnh56Vr7iJ0Y1Y", "story", "Lake", "LAKE", "avg_depth_m", "Average depth of the lake", ""),
("9AxkCJG1cAxLIgRDIxbi6BVRZL1jrlCOtDFKnK6PeOg", "story", "Lake", "LAKE", "lake_altitude_m", "Altitude of the lake", ""),
("5SbFr7lnyrk57GkQ06I1fk8dGNBqIwYipoThWYSZHLs", "story", "Lake", "LAKE", "catchment_area_radius_m", "Catchment area radius of the lake", ""),
("-z8KbKJjMgNBs8e21rqzMATHbhOxFNR2TM2UI_KNzSY", "story", "Lake", "LAKE", "lake_origin", "Origin of the lake", ""),
("9pmpu9SkzseTK2EkZtj4Whgo78uHpg8TO0-A2qhDJ8U", "story", "Lake", "LAKE", "flora_and_fauna", "Flora and fauna of the lake", ""),
("jeKEEFF1gAk61kdJeq5jbEAQXzalU-YUBAPgJmlkgqs", "story", "Lake", "LAKE", "water_color", "Color of the water", ""),
("i9Mm0cD21KYWUgZd8YM6m6amelucw21TNYC4KVnAVSc", "story", "Lake", "LAKE", "accessibility", "Accessibility of the lake", ""),
("ljnn5Aa6-FYXyizs9RzMjPVEbL4SJCwp6w68IJADHzo", "story", "Lake", "LAKE", "special_features", "Special features of the lake", ""),
("pJfZHRA569XEKkz7uyZ3nSa0Cnk3LJPQLRU7_FkyCAo", "story", "Lake", "LAKE", "lake_usage", "Usage of the lake", ""),
("zBqslyV0sWPCNDgY6BYG071yJwcmrBbCT5HrTqWmnpQ", "story", "Lake", "LAKE", "lake_lore", "Legends or myths of the lake", ""),
("YNKVR9jfZD9_m6E4whJkwP8TfWeCJCc4erzf1GAFKb4", "story", "Lake", "LAKE", "lake_history", "History of the lake", ""),
("QPP8K7D9pU5voAT86FyzB-Dcfl5wijEnTKNHn9xOGhs", "story", "Lake", "LAKE", "conservation_status", "Conservation status of the lake", ""),
("k-TluuPngHwXcJ3gapXshZ3RwsUVH5VXD4pItQsR2aU", "story", "Lake", "LAKE", "current_conditions", "Current conditions of the lake", ""),
("pNGKY1yGbDLqpzoOKTYmxG7-X0Bti5pMAgQH-Uj-UB0", "story", "Lake", "LAKE", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("2fTwTM6dzLc7aw7P4GvJynAIMOsShBrL7FQ631YRr1I", "story", "LakeXMap", "LAKE_X_MAP", "lake_x_map_pk", "Primary key, unique identifier for each association", ""),
("ECatPjLFDVOVzrjyxSLU_8wi8s09uRuGHVaK4sSSDY4", "story", "LakeXMap", "LAKE_X_MAP", "lake_uid_fk", "Foreign key linking to the Lake table", ""),
("ATn2v7fAy5yaxB7ArsbOuFGYqTn6sNYFYU1iB6PfxEo", "story", "LakeXMap", "LAKE_X_MAP", "map_uid_fk", "Foreign key linking to the Map table", ""),
("jv5HELjwLt-0gA1FizcZGhq8lENlC27Kc11NfbfhUu0", "story", "LakeXMap", "LAKE_X_MAP", "touch_type", "Type of association", ""),
("WoHfogY5dQHVHoyJ6M6YoPfbNIV0LHAG6XdU9AwSHJ4", "story", "LakeXMap", "LAKE_X_MAP", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("hmrlwwIUsU-viDPW5QmIVz8b51NydlWlfoJPMcA_h8A", "story", "River", "RIVER", "river_uid_pk", "Primary key, unique identifier for each river", ""),
("HGEUm9RORCFwSVJma94gRzYF21l3yPKYZUESbn-kwX8", "story", "River", "RIVER", "gloss_common_uid_vfk", "Foreign key linking to the Common Glossary table", ""),
("Ckwhi5gr9h23HF_DWqKuhnHIfJL9PsPNEiYe7AEzOjo", "story", "River", "RIVER", "river_name", "Name of the river", ""),
("JMPV4ZpOTBXiAetadDuyg1AdBrIRKe-GE2LitOEeJdk", "story", "River", "RIVER", "river_course_points_json", "JSON of the river course points", ""),
("Pg_XDoSh-9l4gkv11lPc9foTHrySH03kO3N5CuyKa_M", "story", "River", "RIVER", "river_bank_points_json", "JSON of the river bank points", ""),
("GbpinFfNQWs2zzanWqnvF1PcjwKDRScvyOperMBWuQw", "story", "River", "RIVER", "river_type", "Type of river", ""),
("3zpkSnWfR3J3F3ZoHzIIVJZyQ9oBHsZggRztvmkHKpk", "story", "River", "RIVER", "avg_width_m", "Average width of the river", ""),
("6yyHt_ImXwBVqFQZK-PcyEQNl071QGxXBGmSxH33uCg", "story", "River", "RIVER", "avg_depth_m", "Average depth of the river", ""),
("KgeYxsX32i4mdBvEktv6aHhcZaYxCy_RmEyk64fmLss", "story", "River", "RIVER", "total_length_km", "Total length of the river", ""),
("SpPDlUMzJGSROBjTXYehWefxm6fh8kMOo25Odyu4_0g", "story", "River", "RIVER", "drainage_basin_km", "Drainage basin of the river", ""),
("MDbaEdyelS5NzojuTZHa2l9RNQ2yuXBTXRYMnbWU3rY", "story", "River", "RIVER", "avg_velocity_m_per_h", "Average velocity of the river", ""),
("b5Oq9g9Wduz7Yua6R_kHNRpsJi0NSY0a7_ise35ZP4s", "story", "River", "RIVER", "gradient_m_per_km", "Gradient of the river", ""),
("CVyf_7LqHyPdLRBZjmuC_rCWmM1WHx0QR8gko-4-9oE", "story", "River", "RIVER", "river_hazards_json", "JSON of the river hazards", ""),
("IwW4HZOounsXG6Tf56Soa_qHvW1eBJMoei5aeQzL1O4", "story", "River", "RIVER", "river_features_json", "JSON of the river features", ""),
("ktxWot9yrhDKxCg1ZzdfdjMu_eS66K4giwxqU-B-U_w", "story", "River", "RIVER", "river_nav_type", "Type of river navigation", ""),
("hvzE8Vrgu3yFHOpkITVm-po6ZiB7IVY6XEfCdHDjlgE", "story", "River", "RIVER", "flora_and_fauna", "Flora and fauna of the river", ""),
("KA_SxjkFzsspjXnkDHG16w9aBgb4KfQ48lO7BWuC1Ho", "story", "River", "RIVER", "water_quality", "Quality of the water", ""),
("ZEXKyqcsGElO8ykX0hlp3FdDAj0QfuOOCrQeBvFPJx4", "story", "River", "RIVER", "historical_events", "Historical events of the river", ""),
("GdIGLWD1hUxfjwd6oC6SmOnspr9lijsACNATzh8aCLY", "story", "River", "RIVER", "current_conditions", "Current conditions of the river", ""),
("cjllyW3tt9puy3aPu46DZHovvpiKw-9Nvz9wL8nqDNk", "story", "River", "RIVER", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("ACT0_W3tWyo7ciCHDg1JPaKzSW4cGCmaQZTPQumPqGs", "story", "RiverXMap", "RIVER_X_MAP", "river_x_map_uid_pk", "Primary key, unique identifier for each association", ""),
("PuOAW0aHmszSOOJjNBQ2c04RDeUIsePxMugGxhyvbtg", "story", "RiverXMap", "RIVER_X_MAP", "river_uid_fk", "Foreign key linking to the River table", ""),
("6Mhx8uO9ZX0wXt0jm4aBjURWp8KmSHglHkH2Y_ZNY24", "story", "RiverXMap", "RIVER_X_MAP", "map_uid_fk", "Foreign key linking to the Map table", ""),
("3cXdVHRL2yZv9mqLOy0Z8H1TJbdh_aeqnB0mWSjsjug", "story", "RiverXMap", "RIVER_X_MAP", "touch_type", "Type of association", ""),
("spF1iVjx5Jl4UZOvt0ZhiKQpjt2fD1LJYPlokbd87mY", "story", "RiverXMap", "RIVER_X_MAP", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("3Jtq_hzD2ckChJ1ZFtaHLL7n_2ON4Q_HimNcjAmyi4c", "story", "OceanBody", "OCEAN_BODY", "ocean_body_uid_pk", "Primary key, unique identifier for each ocean body", ""),
("IQ-1D3v11zXOoirG0TQIE9pqzHKDb_lDF5r6f1nPscI", "story", "OceanBody", "OCEAN_BODY", "gloss_common_uid_vfk", "Foreign key linking to the Common Glossary table", ""),
("0jVjavvZIxlmQ4dEywMyaRCz99oe7Si_6t-1PblAS0Y", "story", "OceanBody", "OCEAN_BODY", "ocean_body_name", "Name of the ocean body", ""),
("TeZz3t2D_JMPKu-bHHsUQPHGoglpIXUX819Xqpf3wnA", "story", "OceanBody", "OCEAN_BODY", "body_shoreline_points_json", "JSON of the body shoreline points", ""),
("MDpdruwZdqQk67qf4Kf6sLM2Ust2optJXt8sEQs8Q5E", "story", "OceanBody", "OCEAN_BODY", "is_coastal", "Indicates if the body is coastal", ""),
("0jN8n_QvHGdJpBYtWklwefp4zr1TyCcFq_fiKTA2HQI", "story", "OceanBody", "OCEAN_BODY", "is_frozen", "Indicates if the body is frozen", ""),
("XFd_YWAOTjlk7zJbDqdW7JLvk2D8Ii_bPV-KS8G6RSo", "story", "OceanBody", "OCEAN_BODY", "ocean_body_type", "Type of ocean body", ""),
("V0hVVem6AAQoQCsUUXi90-OgsZ-hIkC-0fjLRrSaA1U", "story", "OceanBody", "OCEAN_BODY", "water_type", "Type of water", ""),
("B2CABf3zaTlwecVKQKg9H3DEAqmQ4-x9dVp4_iyh8JI", "story", "OceanBody", "OCEAN_BODY", "is_tidal_influence", "Indicates if the body has tidal influence", ""),
("DGIkKCksLwxJUSq5PhhWN4CGt4brJ_8qqTIHB5kn7nY", "story", "OceanBody", "OCEAN_BODY", "tidal_flows_per_day", "Number of tidal flows per day", ""),
("tusn6_hR78c-CVyqzeCfDeYNHEn9SCWxwoVh7ysHmD8", "story", "OceanBody", "OCEAN_BODY", "avg_high_tide_m", "Average high tide", ""),
("lDRYoUVCwL0yDGJz_IDT8bUWHuLKtUR5YCv0PfsPKJU", "story", "OceanBody", "OCEAN_BODY", "avg_low_tide_m", "Average low tide", ""),
("t8_cbB_aDFr_xdBA5u0mXBM_Wuezt8yBML_1aT5tCO4", "story", "OceanBody", "OCEAN_BODY", "max_high_tide_m", "Maximum high tide", ""),
("e68dTljF0mM5B9ClLPcpB1EeuT_Mg9SY_okLlkSwkFw", "story", "OceanBody", "OCEAN_BODY", "ocean_wave_type", "Type of ocean wave", ""),
("0KVUUdTxr112jD75JBEGulN5P1YRImhDOJRYuLiLcN8", "story", "OceanBody", "OCEAN_BODY", "body_surface_area_m2", "Surface area of the body", ""),
("XvLsKUQp64erf92jDjl9PZGmI3yWOeUu0ABFeObaLXY", "story", "OceanBody", "OCEAN_BODY", "body_surface_altitude_m", "Altitude of the body", ""),
("AA_j5kr0tWQUKRfIgUO8v81lpGEhzbyRnNNI-GHUm0k", "story", "OceanBody", "OCEAN_BODY", "max_depth_m", "Maximum depth of the body", ""),
("7Rw-fD6nY9LOkNe795yJENH0kc_X_GUNTI4gxSmTVV4", "story", "OceanBody", "OCEAN_BODY", "avg_depth_m", "Average depth of the body", ""),
("T-Hh3uLclVuwZpRdUK1A1FWBVf_wW4lmf6pAyx2NSD8", "story", "OceanBody", "OCEAN_BODY", "ocean_hazards_json", "JSON of the ocean hazards", ""),
("HbU8xItka8soRbPiadyDcPpTBFci2CnoxF1h8J95d3k", "story", "OceanBody", "OCEAN_BODY", "ocean_features_json", "JSON of the ocean features", ""),
("vbZo1TLBZa4UlqBL1hI-mso8gIa82VW9qV0CJ6NWvXw", "story", "OceanBody", "OCEAN_BODY", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("EhwQPl8S-JzimNGj4qaGXy4ZqltVxCwmQ9FdjZ10_xY", "story", "OceanBodyXMap", "OCEAN_BODY_X_MAP", "ocean_body_x_map_uid_pk", "Primary key, unique identifier for each association", ""),
("Oz1MAXqk-PGZr7Y0B7dT8d9j1XS9TlViWVClXLztOFg", "story", "OceanBodyXMap", "OCEAN_BODY_X_MAP", "ocean_body_uid_fk", "Foreign key linking to the Ocean Body table", ""),
("g4WJVNmAxVnhBXzZmnD0JMiKaeTG2z5iAKWtHfOfrw8", "story", "OceanBodyXMap", "OCEAN_BODY_X_MAP", "map_uid_fk", "Foreign key linking to the Map table", ""),
("vB4sQsEaY-Z_ETzexKdNT1HAjfbYTMfQJxGSDkPBIQU", "story", "OceanBodyXMap", "OCEAN_BODY_X_MAP", "touch_type", "Type of association", ""),
("5qzr41XV9s4JcWUd1mU09WK6AY7v5EppPeHEfyTEoK4", "story", "OceanBodyXMap", "OCEAN_BODY_X_MAP", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("6Utm_UXxb9yHH8GEoXhpkHFwa4MP1n4drgdNmOB_fuI", "story", "OceanBodyXRiver", "OCEAN_BODY_X_RIVER", "ocean_body_x_river_uid_pk", "Primary key, unique identifier for each association", ""),
("RxeU45U9MTsBdhx8ncUb4nnXepk4rfyCK30KTIP2kiI", "story", "OceanBodyXRiver", "OCEAN_BODY_X_RIVER", "ocean_body_uid_fk", "Foreign key linking to the Ocean Body table", ""),
("1PgiyZoCXarKBr-vUY1CwaL2_ekM4hTjMYzjxkw0G7E", "story", "OceanBodyXRiver", "OCEAN_BODY_X_RIVER", "river_uid_fk", "Foreign key linking to the River table", ""),
("mFqVAL68JXAH5ibJigr6XU_FAJjYXfCJ195gN3eX2Ig", "story", "OceanBodyXRiver", "OCEAN_BODY_X_RIVER", "touch_type", "Type of association", ""),
("t1VO7YWFG0PAqMYMFqqoBv-umubMde5-waWOiGev7kw", "story", "OceanBodyXRiver", "OCEAN_BODY_X_RIVER", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("oFwUKXlH__zgfT9vP55ANElOEKAnMRD47NpBSm7TP6w", "story", "LandBody", "LAND_BODY", "land_body_uid_pk", "Primary key, unique identifier for each land body", ""),
("vLduOjVHhk-m3wr2QOjOVkJB518CBAFX0Qtq4Bb7bac", "story", "LandBody", "LAND_BODY", "gloss_common_uid_vfk", "Foreign key linking to the Common Glossary table", ""),
("ZtR3wgBr2-ghThkPgwTVpBonQdEmxmR5YKVf845O88w", "story", "LandBody", "LAND_BODY", "land_body_name", "Name of the land body", ""),
("lldU4ueLR5W42m0BmOY0i-b9G493aHT6VELFK57Yhkc", "story", "LandBody", "LAND_BODY", "body_landline_points_json", "JSON of the land body line points", ""),
("zellTc3oyLlh6ZEim3ds4kUdMNh96ZFN6es0WW_GY6M", "story", "LandBody", "LAND_BODY", "land_body_type", "Type of land body", ""),
("m2iChWx-PavH1wmeRRDp2bfZg6z0Qr3FazaIzww1RCU", "story", "LandBody", "LAND_BODY", "land_body_surface_area_m2", "Surface area of the land body", ""),
("w_Acsy4gxxYZpJ_ofCrxhOOYE9aJYENTC3-jFEtG1Fs", "story", "LandBody", "LAND_BODY", "land_body_surface_avg_altitude_m", "Average altitude of the land body", ""),
("oL_-Qa1IeNqV9rN7WZyfovmmNMHkr9e4pXnYYkhi3eI", "story", "LandBody", "LAND_BODY", "max_altitude_m", "Maximum altitude of the land body", ""),
("TlUN3jLuwxRmZRUl-4B328CR9kuu44KpQeYeeeGb7Cc", "story", "LandBody", "LAND_BODY", "min_altitude_m", "Minimum altitude of the land body", ""),
("O9Iv9y8p6T_JlCJ8a2EhxAu131PopjDI1-rhpYAqNl8", "story", "LandBody", "LAND_BODY", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("Ga7i-n_PRQSUa0cOk6rTM6L-y4E3Iejv4m_IKpvGo90", "story", "LandBodyXMap", "LAND_BODY_X_MAP", "land_body_x_map_uid_pk", "Primary key, unique identifier for each association", ""),
("STXmmc2uMHJ81E5pt1mokyZxkiI1U72jSg0s9VxnPkE", "story", "LandBodyXMap", "LAND_BODY_X_MAP", "land_body_uid_fk", "Foreign key linking to the Land Body table", ""),
("GQG_K4f-MQFS2gcEhR5uGmtRWPhtURivZ5OiWHTiTVo", "story", "LandBodyXMap", "LAND_BODY_X_MAP", "map_uid_fk", "Foreign key linking to the Map table", ""),
("xDErWYIdfFfS-98J8rBi7OnT1jH59EnaH3cmy5CBcYE", "story", "LandBodyXMap", "LAND_BODY_X_MAP", "touch_type", "Type of association", ""),
("9V8ZBO5xAKPF3Te4JrthL0kXbOUZASLUVB2Um7sqjf8", "story", "LandBodyXMap", "LAND_BODY_X_MAP", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("x9QTICQ7o1BxC_bTekj1m869kt7b9aSLx2J9zLtqJlY", "story", "LandBodyXLandBody", "LAND_BODY_X_LAND_BODY", "land_body_x_land_body_uid_pk", "Primary key, unique identifier for each association", ""),
("tiYm3DhfkPmwaAnJ8tiZmWV_gNUyK97TzqmNqHGgZ5U", "story", "LandBodyXLandBody", "LAND_BODY_X_LAND_BODY", "land_body_1_uid_fk", "Foreign key linking to the Land Body table", ""),
("7oj6EP4TVuaqXlo1apxInPEG2vt-OeedXbOyTqpeUB4", "story", "LandBodyXLandBody", "LAND_BODY_X_LAND_BODY", "land_body_2_uid_fk", "Foreign key linking to the Land Body table", ""),
("a3X3vYzCuetJrgngnZkOtW8C4aUL7rQ9bG96UaHoSEU", "story", "LandBodyXLandBody", "LAND_BODY_X_LAND_BODY", "land_land_relation_type", "Type of land-land relation", ""),
("vBE8qUuZDPhKqfAQGGvZgtdk1bFlvRJO_uZ3XbJq-qA", "story", "LandBodyXLandBody", "LAND_BODY_X_LAND_BODY", "touch_type", "Type of association", ""),
("uW_alTmPlu_o3LmYI-_VrYByBbMc-zGEf0j_5Qr62MM", "story", "LandBodyXLandBody", "LAND_BODY_X_LAND_BODY", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("UBo5nrebnQkOaBBg-qzDeu_kTDh7kiddjCI4aN80FJw", "story", "LandBodyXOceanBody", "LAND_BODY_X_OCEAN_BODY", "land_body_x_ocean_body_uid_pk", "Primary key, unique identifier for each association", ""),
("8L2_2qRAKaFu9ArUJ2Ru6GMsPtnAgrFlf1Bzv5OE1T8", "story", "LandBodyXOceanBody", "LAND_BODY_X_OCEAN_BODY", "land_body_uid_fk", "Foreign key linking to the Land Body table", ""),
("haquSLf9WUhm8llVHbQddodZzhiq_keqOJORHBjmxkk", "story", "LandBodyXOceanBody", "LAND_BODY_X_OCEAN_BODY", "ocean_body_uid_fk", "Foreign key linking to the Ocean Body table", ""),
("jvDNxxJdBzmy5bccyFERn71HLMq7rR8JdOPLGEYyuj8", "story", "LandBodyXOceanBody", "LAND_BODY_X_OCEAN_BODY", "land_ocean_relation_type", "Type of land-ocean relation", ""),
("wsjowYIkA4u2KSnymAO6_CZFWMq7O70HXM_TzqIoBgw", "story", "LandBodyXOceanBody", "LAND_BODY_X_OCEAN_BODY", "touch_type", "Type of association", ""),
("EPlyZgjgs-eGWy7chMfaGFssc-sKbsO-j2eQeQQ7c6Y", "story", "LandBodyXOceanBody", "LAND_BODY_X_OCEAN_BODY", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("VfKJeND3DI75C7PJ4p2JOVSSIR46YaD0A8Dgo63ppUQ", "story", "SolarYear", "SOLAR_YEAR", "solar_year_uid_pk", "Primary key, unique identifier for each solar year", ""),
("I6bMk9rGL_YcJpIbtK7xPxztFYCCbpep7Z0v_QC5kvE", "story", "SolarYear", "SOLAR_YEAR", "world_uid_fk", "Foreign key linking to the World table", ""),
("rDr-RAqt4V7xj1tFMWMcNPRnkUE0dEMPd6MOsIm2ICQ", "story", "SolarYear", "SOLAR_YEAR", "lang_uid_fk", "Foreign key linking to the Language table", ""),
("pitFsdsCrP_Z1W9e2doOTFbUex28kNO0jpLnGAXTLSI", "story", "SolarYear", "SOLAR_YEAR", "solar_year_key", "Key for the solar year", ""),
("YjaRi1AH8A6Yg5RLXsgko9L0Cc8vcnlDMqZM8J574Yc", "story", "SolarYear", "SOLAR_YEAR", "version_id", "Version of the solar year", ""),
("PmiTxb7svnrYe4zNc0EcvAOOl4HShoStXxDmB1FiZAw", "story", "SolarYear", "SOLAR_YEAR", "solar_year_name", "Name of the solar year", ""),
("fw14guaa-3-P1LHrbQX5_CcoidCtuGbbohye3cQKs7I", "story", "SolarYear", "SOLAR_YEAR", "solar_year_desc", "Description of the solar year", ""),
("QPCyRh-1f4J2WbYdJdNxrkgNoStlM_v4sCQFBS8klnU", "story", "SolarYear", "SOLAR_YEAR", "solar_year_span", "Number of solar revolutions in the year", ""),
("FmRT4nwXFf3dlpvaqTWIz6yBmzjWX0tOb-yl8umzmuQ", "story", "SolarYear", "SOLAR_YEAR", "days_in_solar_year", "Number of days in the solar year", ""),
("BGDVtEXeXhtw8wvAMWPv2CpBnHff6bOPHBNb3aCdk_4", "story", "SolarYear", "SOLAR_YEAR", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("w9g9_e-IM2vz5_KMQt8ZQIxO67as38dcjhTaVwjxze4", "story", "Season", "SEASON", "season_uid_pk", "Primary key, unique identifier for each season", ""),
("VkOJvh21BwyNjy_Etwy4uTRGnvPfBJPg4VaNvoavdRo", "story", "Season", "SEASON", "solar_year_uid_fk", "Foreign key linking to the Solar Year table", ""),
("5jhkkKLPiN7Wblq816geEVG554XK7-5DbJbSgXNSuVY", "story", "Season", "SEASON", "gloss_common_uid_vfk", "Virtual foreign key linking to the Common Glossary table", ""),
("A0oOhRdcfJxOpZWUzsUbyuPXNpNI4_Vl4W6p54GIHjg", "story", "Season", "SEASON", "season_type", "Type of the season", ""),
("dJMGmehBlKzGJFL_-vkA0sMVBauHnYlzgSQTlEoBlp4", "story", "Season", "SEASON", "hemisphere_type", "Hemisphere of the season", ""),
("NDJ0f6zpdMRQHrJzsEEy1DrD0CXCvnpYMwFvGXx64Hg", "story", "Season", "SEASON", "years_in_season", "Number of years in the season", ""),
("1qUNPoRcE23L2yevsDeeIa38H3E2IavNyxo4JtONfjc", "story", "Season", "SEASON", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("dOhEdtPAKxDKdNRwuhST60n79o4M8hn6CmlpLpDrGI8", "story", "LunarYear", "LUNAR_YEAR", "lunar_year_uid_pk", "Primary key, unique identifier for each lunar year", ""),
("ncFQ143N0ldx9UQ84VxPGYWQSoa7x32gboCm-UATcnU", "story", "LunarYear", "LUNAR_YEAR", "world_uid_fk", "Foreign key linking to the World table", ""),
("73MCxXy2FtM8Y8M4O25JJkTLXET5Y2wnybrj5UeO-SU", "story", "LunarYear", "LUNAR_YEAR", "lang_uid_vfk", "Virtual foreign key linking to the Language table", ""),
("IovHF9wFGqRSyVUtkM8A0OW6-xlgsISGpzazfYFuq8M", "story", "LunarYear", "LUNAR_YEAR", "lunar_year_name", "Name of the lunar year", ""),
("-Rgh9I4I2k6NCgVVgDn4my2TYqd4rgcpCDk0fUfnzrU", "story", "LunarYear", "LUNAR_YEAR", "lunar_year_desc", "Description of the lunar year", ""),
("A1QYdSjTr3orGRZvbi40cl6eCS3J3ClAsHmCZoDkYJI", "story", "LunarYear", "LUNAR_YEAR", "days_in_lunar_year", "Number of days in the lunar year", ""),
("9EGr9nmhD79OK3jzCYZhr0J0IqmGSLJURMv1gYMe3jU", "story", "LunarYear", "LUNAR_YEAR", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("96ZwjNjPnKwg1AAhEd9nVLLHKQ_AkLY4Y67qpwvI7VY", "story", "LunarYearXMoon", "LUNAR_YEAR_X_MOON", "lunar_year_x_moon_uid_pk", "Primary key, unique identifier for each association", ""),
("OYUcP-bj7FwrYDKRid7LKvxKdhnaog7079FFI7rSwlQ", "story", "LunarYearXMoon", "LUNAR_YEAR_X_MOON", "lunar_year_uid_fk", "Foreign key linking to the Lunar Year table", ""),
("j0_fnlSwiwIWMbs3paztY4XlbT0l15_BiqvFI7n6Uew", "story", "LunarYearXMoon", "LUNAR_YEAR_X_MOON", "moon_uid_fk", "Foreign key linking to the Moon table", ""),
("-qnEj_d8zPUDJVDSY31z49eFtds6Bn9BsLYzic9CNIQ", "story", "LunarYearXMoon", "LUNAR_YEAR_X_MOON", "touch_type", "Type of association", ""),
("nwORRBGTu8jNuPR_r5LL1sGkhPJ88gNjGQF8bJIhxnQ", "story", "LunarYearXMoon", "LUNAR_YEAR_X_MOON", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("IeaVTRaLSM4uZ_Ud5WIGB-nSPihy4h4BaK3ayFU7BV0", "story", "SolarCalendar", "SOLAR_CALENDAR", "solar_calendar_uid_pk", "Primary key, unique identifier for each solar calendar", ""),
("nh9kTlMncquLp3fPeYLnvytS1_f8Jr8nykXYqhmV4ts", "story", "SolarCalendar", "SOLAR_CALENDAR", "solar_year_uid_fk", "Foreign key linking to the Solar Year table", ""),
("YutBM1-O3gW3O8EJUIInhWoEgk7tnGNeg5bduPcBhN4", "story", "SolarCalendar", "SOLAR_CALENDAR", "year_name_gloss_common_uid_vfk", "Virtual foreign key linking to the Common Glossary table", ""),
("WRkRtidfcssQGvLUisxY2FWLWgEymkuSc84j605Q93w", "story", "SolarCalendar", "SOLAR_CALENDAR", "season_start_uid_fk", "Foreign key linking to the Season table", ""),
("3yIyAPlNZ9_1n5k59J5BqJQjZOwvTNLrIuxpjBTCEVM", "story", "SolarCalendar", "SOLAR_CALENDAR", "solar_calendar_name", "Name of the solar calendar", ""),
("O8opv-GNz41va1XHuJnbBOujE832S7ol0a0meWUBaFU", "story", "SolarCalendar", "SOLAR_CALENDAR", "solar_calendar_desc", "Description of the solar calendar", ""),
("wFzL3yznXopBvkpCC-I8Ci4gp1KcdZfQc8YdOGGlj2k", "story", "SolarCalendar", "SOLAR_CALENDAR", "epoch_start_offset", "Offset from the epoch start year", ""),
("-qFWSClXW8uMXYsrLsjHyReDCvT5gwfCOeVIDf7yKRQ", "story", "SolarCalendar", "SOLAR_CALENDAR", "months_in_year", "Number of months in the year", ""),
("RILTbAlz_g6GVxUSKcxbdSPsKQJB5y0U3v-39dB1M0g", "story", "SolarCalendar", "SOLAR_CALENDAR", "watches_in_day", "Number of watches in the day", ""),
("dWC-F7259B9SmTjSbCeBGL6FnIUkGmIfX2R3U5Fh-uE", "story", "SolarCalendar", "SOLAR_CALENDAR", "hours_in_watch", "Number of hours in the watch", ""),
("yt8klqkoDzcQdUpnlR3kqYqoBH1VJ5VFMGBe6ASiiXE", "story", "SolarCalendar", "SOLAR_CALENDAR", "minutes_in_hour", "Number of minutes in the hour", ""),
("1SgB6kY6iC3OjCVyemMTI86sxyL0NM4axV65HxwsfCo", "story", "SolarCalendar", "SOLAR_CALENDAR", "seconds_in_minute", "Number of seconds in the minute", ""),
("grcTQFSprLg5-JYO_6EJGP3-Z2qFs_bqX69_hlm9H68", "story", "SolarCalendar", "SOLAR_CALENDAR", "leap_year", "Number of leap years", ""),
("SQIMHF6pezJPpaEElDgCQifjA1QrpW2rlHuZVAVM644", "story", "SolarCalendar", "SOLAR_CALENDAR", "leap_month", "Number of leap months", ""),
("JBRJSGT_EaxtAaVtTxv_RXFeZDMlJr9aroDx_u1HisE", "story", "SolarCalendar", "SOLAR_CALENDAR", "leap_days", "Number of leap days", ""),
("1VusXPiUdM9faNaB-m-I2xZj37B1kSgeuTYQg2uskVg", "story", "SolarCalendar", "SOLAR_CALENDAR", "leap_rule", "Rule for handling leap years", ""),
("Gtls5zBugAJUOvfkpqUm8l0tDjwmRqt9Tuv1JZrskHo", "story", "SolarCalendar", "SOLAR_CALENDAR", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("_bvnb543cDpc74KAmhP5qSR989XdckiCWEwxtunEcps", "story", "LunarCalendar", "LUNAR_CALENDAR", "lunar_calendar_uid_pk", "Primary key, unique identifier for each lunar calendar", ""),
("abh8FzHjgyI3PDfCx7pF8_JVbv1Rl1M9VtocjyzHQaA", "story", "LunarCalendar", "LUNAR_CALENDAR", "lunar_year_uid_fk", "Foreign key linking to the Lunar Year table", ""),
("KMXVcjkQO9I_pPveW8188m-mGS0WLFYsxvQ0cygnC3U", "story", "LunarCalendar", "LUNAR_CALENDAR", "lunar_year_name_gloss_common_uid_vfk", "Virtual foreign key linking to the Common Glossary table", ""),
("2XQVE1XOwBl4GeOLj1tPaqJoA1fzq1LiYUIeDu7BPec", "story", "LunarCalendar", "LUNAR_CALENDAR", "lunar_calendar_name", "Name of the lunar calendar", ""),
("rJsvxIq1l7n2grqpmvfnVP8K6Bh3fcsVtFKEbMxgG-w", "story", "LunarCalendar", "LUNAR_CALENDAR", "lunar_calendar_desc", "Description of the lunar calendar", ""),
("BIhkPdbp89Wxh1MhCHXpBAR1nY-H9Rpwlidqur6Qk2g", "story", "LunarCalendar", "LUNAR_CALENDAR", "epoch_start_offset", "Offset from the epoch start year", ""),
("MPQ9jgv6hpNQatbLHLW3EzZHqrDbG6vmT8MdtLeYQKE", "story", "LunarCalendar", "LUNAR_CALENDAR", "days_in_month", "Number of days in the month", ""),
("5RSZczWS4JmbT2yfZS7YssroPenwiN0Y09tuvyHZqbc", "story", "LunarCalendar", "LUNAR_CALENDAR", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("tJ-K828bdnFgSZzQ-CMayJNt5PUdJT6St7do-RZ0HyA", "story", "Month", "MONTH", "month_uid_pk", "Primary key, unique identifier for each month", ""),
("SbB_Qf-Kxqt7MeE1IrFgHzorR3RE8JwgHiFFTWSkplo", "story", "Month", "MONTH", "month_name_gloss_common_uid_vfk", "Virtual foreign key linking to the Common Glossary table", ""),
("Prl5m04sEuG82MjHgciYMgdfZuRJZdMFfUYjM75IZ_c", "story", "Month", "MONTH", "month_name", "Name of the month", ""),
("AOxIsmB3AMIVHvW3lnD8zz8Nl1Rcbzd6lijpWU-ZZdA", "story", "Month", "MONTH", "days_in_month", "Number of World days in the month", ""),
("Va0Lu_mP3n5oiSqhPKq20JhLGxqfwCcR2XUSPpP0CXM", "story", "Month", "MONTH", "month_order", "Ordinal number of the month", ""),
("KpGHPqkH1c6Gzx47UraEoQkpPVw6XLhT7eJky-clKgg", "story", "Month", "MONTH", "is_leap_day_month", "Indicates if the month contains leap day/s", ""),
("MJVNoPVGfs8O92pYoxJUX07V4i1stJOix2K_FZtWgG4", "story", "Month", "MONTH", "is_leap_month", "Indicates if the entire month is leap days", ""),
("Aoz6-3szDs6K0J0Dk63D4D0e3SjIJrWZecwjzVOQ-bo", "story", "Month", "MONTH", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("XY1gzEulwcNKy0eSN7OpI3RwsnnHpDAhePzOOkRshCE", "story", "LunarCalendarXMonth", "LUNAR_CALENDAR_X_MONTH", "lunar_calendar_x_moon_uid_pk", "Primary key, unique identifier for each association", ""),
("1TktDX9p7d57a0-qNxhIdLFoy7oPN-y0dkewh31uiIE", "story", "LunarCalendarXMonth", "LUNAR_CALENDAR_X_MONTH", "lunar_calendar_uid_fk", "Foreign key linking to the Lunar Calendar table", ""),
("wxBOHxajMv7MFpmh6MOLw6oB3Zq5aDUXBEvTE0wskd8", "story", "LunarCalendarXMonth", "LUNAR_CALENDAR_X_MONTH", "month_uid_fk", "Foreign key linking to the Month table", ""),
("_t3km5q75fat7c-AJoAIrluTX3mLkeCXvkOFdhrdjqE", "story", "LunarCalendarXMonth", "LUNAR_CALENDAR_X_MONTH", "touch_type", "Type of association", ""),
("-pDCc1Q4YB7nVXe9QXkvL-65uFzBQIzsG5AouNZUbG4", "story", "LunarCalendarXMonth", "LUNAR_CALENDAR_X_MONTH", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("zsa66Cg7DF_zCnt6cDXDgc3lgvewBSJGZP8-CZVB6Dg", "story", "SolarCalendarXMonth", "SOLAR_CALENDAR_X_MONTH", "solar_calendar_x_moon_uid_pk", "Primary key, unique identifier for each association", ""),
("75k9jGWabmB_wx3w_pFG5K49bfHwh4s-xTORTRFzt0M", "story", "SolarCalendarXMonth", "SOLAR_CALENDAR_X_MONTH", "solar_calendar_uid_fk", "Foreign key linking to the Solar Calendar table", ""),
("UdXLJe1tTTdGkRMMXO1WZAMvNQm1pOdsluTY-S6DNm0", "story", "SolarCalendarXMonth", "SOLAR_CALENDAR_X_MONTH", "month_uid_fk", "Foreign key linking to the Month table", ""),
("sjddeu4TnDmJF-XwLd9__d5FWFdK6I7xNFtmKdiUAXw", "story", "SolarCalendarXMonth", "SOLAR_CALENDAR_X_MONTH", "touch_type", "Type of association", ""),
("7dGNMj19fStB5_XAD3J77ZN1s3nI7U_CU1-JtOwQqWk", "story", "SolarCalendarXMonth", "SOLAR_CALENDAR_X_MONTH", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("6sXWQvoa9WxbKNofInNr2vA1mdBdvD9b_ekpQgyEV4E", "story", "WeekTime", "WEEK_TIME", "week_time_uid_pk", "Primary key, unique identifier for each week time", ""),
("-mZRc9f2M5ouf-sWDSDkH_eP20NO4Df0m1l6OGY7_hs", "story", "WeekTime", "WEEK_TIME", "week_time_name_gloss_common_uid_vfk", "Virtual foreign key linking to the Common Glossary table", ""),
("1vpqOEYUhPkRF9UWdAA7Lssf3GcUL7yHOeT2lMVg8tE", "story", "WeekTime", "WEEK_TIME", "week_time_name", "Name of the week time", ""),
("kZEKcygCTK3JNaDLBZ-aNZSlvOA2ytg86F5zVQjCCkw", "story", "WeekTime", "WEEK_TIME", "week_time_desc", "Description of the week time", ""),
("UWP8akbOA6RA8pGdQPKiMBz1c8UufWrnjXywW4kAX14", "story", "WeekTime", "WEEK_TIME", "days_in_week_time", "Number of days in the week time", ""),
("hbqh9zPk9bH-PTckFut40knkkTtbZiFaTbZe-6hxadI", "story", "WeekTime", "WEEK_TIME", "week_time_order", "Order of the week time", ""),
("h3DIimrATi4ReC3JfGF35pE8tQlqDP93f4UXrEHodOQ", "story", "WeekTime", "WEEK_TIME", "is_leap_week_time", "Indicates if the week time contains leap day/s", ""),
("ZJhK1fgCvrhe8Ox5r4-NHvj0PgDpxAHzqo9UAgYOOVQ", "story", "WeekTime", "WEEK_TIME", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("vy6g_McFBBj_iL_cmCwsVGhTBb8IoMkpv47lc-BT-LE", "story", "LunarCalendarXWeekTime", "LUNAR_CALENDAR_X_WEEK_TIME", "lunar_calendar_x_week_time_uid_pk", "Primary key, unique identifier for each association", ""),
("SHdEIfuy9kqAXZ48b3Hirye85z89yE6M3Ap6LmqUwxc", "story", "LunarCalendarXWeekTime", "LUNAR_CALENDAR_X_WEEK_TIME", "lunar_calendar_uid_fk", "Foreign key linking to the Lunar Calendar table", ""),
("Ywj0GihQeJ7O2SnzL75ZguxDLv1zhRy4UJMG1JCJfeM", "story", "LunarCalendarXWeekTime", "LUNAR_CALENDAR_X_WEEK_TIME", "week_time_uid_fk", "Foreign key linking to the Week Time table", ""),
("STcVyIdE3LT-Pxh7WnAoz9e4Bz5Xxfosevw4Ok7oplI", "story", "LunarCalendarXWeekTime", "LUNAR_CALENDAR_X_WEEK_TIME", "touch_type", "Type of association", ""),
("y51zJPFH8xh1zNiyWLIQbE0Fq-WEfpa9m6RF0TZxu-4", "story", "LunarCalendarXWeekTime", "LUNAR_CALENDAR_X_WEEK_TIME", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("zNCPer59KM-IvHRnKC32471-kl5-8SwbMuG3W_tFA98", "story", "SolarCalendarXWeekTime", "SOLAR_CALENDAR_X_WEEK_TIME", "solar_calendar_x_week_time_uid_pk", "Primary key, unique identifier for each association", ""),
("9f6SRVzRRQ--U1vl6u-WgFnVyOhKHDF7sS18XFNZDFs", "story", "SolarCalendarXWeekTime", "SOLAR_CALENDAR_X_WEEK_TIME", "solar_calendar_uid_fk", "Foreign key linking to the Solar Calendar table", ""),
("f76NMO3h1he3YLPtzMEgJFuHMWXSr0RJCZ1LRVbd0vU", "story", "SolarCalendarXWeekTime", "SOLAR_CALENDAR_X_WEEK_TIME", "week_time_uid_fk", "Foreign key linking to the Week Time table", ""),
("-otn88fW6_oPYmXd6jpNu-WSESNtJXpd8doF3OexrKA", "story", "SolarCalendarXWeekTime", "SOLAR_CALENDAR_X_WEEK_TIME", "touch_type", "Type of association", ""),
("koParfCAGgdz5cSWMMYyoy2qu-ePH4I9r2lQf44-jf8", "story", "SolarCalendarXWeekTime", "SOLAR_CALENDAR_X_WEEK_TIME", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("sy_bn30kOWSRH1f_pRENM-8m-_LWb9NN_l5uM3HTOm0", "story", "DayTime", "DAY_TIME", "day_time_uid_pk", "Primary key, unique identifier for each day time", ""),
("MY0BNC5vpxOWS10cxdEkQ2PPD7WZYwVW2l0KGm9I7YE", "story", "DayTime", "DAY_TIME", "day_time_name_gloss_common_uid_vfk", "Virtual foreign key linking to the Common Glossary table", ""),
("MHIkeTMxDhiGizIwG7CmR6flKVdQA8qtApS7OBBUDJI", "story", "DayTime", "DAY_TIME", "day_time_name", "Name of the day time", ""),
("6EwcORDRJnxrum8cj_QZs_chfvzfeNG0hvbIqU8TRDE", "story", "DayTime", "DAY_TIME", "day_time_desc", "Description of the day time", ""),
("dJJF9IN5x16j1zpxzW09MRr38Q1nkQWaS85Etgy-Etc", "story", "DayTime", "DAY_TIME", "hours_in_day_time", "Number of hours in the day time", ""),
("pwX-er7noPraGXhYh41Gl2H8AjrU2se2FwaTBLz8TyU", "story", "DayTime", "DAY_TIME", "day_time_number", "Order of the day in a week", ""),
("6ZF3AwVdThwwm996xsTACuKMz_ww37E_-uxkfGuwT4g", "story", "DayTime", "DAY_TIME", "is_leap_day_time", "Indicates if the day time is only a leap day", ""),
("p0fK1n1QHfbAYHqD01AnDK49oJQDuSJ1rwTi6DkNKIU", "story", "DayTime", "DAY_TIME", "delete_dt", "Deletion date, indicating when the record was marked for deletion", ""),
("Kobz3t_dq3jPDi8k5_GBAhmMQ9HFLBjYPB3hCScEGo0", "story", "WeekTimeXDayTime", "WEEK_TIME_X_DAY_TIME", "week_time_x_day_time_uid_pk", "Primary key, unique identifier for each association", ""),
("DsZFl8Y1PhAgb2sLNnbDOXJkgDKYgaDhIXALwUuX0Yw", "story", "WeekTimeXDayTime", "WEEK_TIME_X_DAY_TIME", "week_time_uid_fk", "Foreign key linking to the Week Time table", ""),
("GoFrb50-UN8sBsXjJg5kSxBJsB6mfucmHwtNsfGxRVQ", "story", "WeekTimeXDayTime", "WEEK_TIME_X_DAY_TIME", "day_time_uid_fk", "Foreign key linking to the Day Time table", ""),
("XlSE_fhpPQOIUsMXUeMGLr5ziBje4eAINdiVVIxRJm0", "story", "WeekTimeXDayTime", "WEEK_TIME_X_DAY_TIME", "touch_type", "Type of association", ""),
("E4npXAwV54Pifj6NyDLbXo2FdDhDyopJZex0oDGRCvw", "story", "WeekTimeXDayTime", "WEEK_TIME_X_DAY_TIME", "delete_dt", "Deletion date, indicating when the record was marked for deletion", "");