CREATE TABLE IF NOT EXISTS WORLD (
world_uid_pk TEXT DEFAULT '',
star_system_uid_fk TEXT DEFAULT '',
world_name TEXT DEFAULT '',
world_type TEXT DEFAULT 'habitable',
obliquity_dg NUMERIC DEFAULT 0.0,
distance_from_star_au NUMERIC DEFAULT 0.0,
distance_from_star_km NUMERIC DEFAULT 0.0,
radius_km NUMERIC DEFAULT 0.0,
mass_kg NUMERIC DEFAULT 0.0,
gravity_m_per_s_per_s NUMERIC DEFAULT 0.0,
orbit_gdy NUMERIC DEFAULT 0.0,
orbit_gyr NUMERIC DEFAULT 0.0,
is_tidally_locked BOOLEAN DEFAULT 0,
rotation_gdy NUMERIC DEFAULT 0.0,
rotation_direction TEXT DEFAULT 'prograde',
orbit_direction TEXT DEFAULT 'prograde',
moons_cnt INTEGER DEFAULT 0,
world_desc TEXT DEFAULT '',
atmosphere TEXT DEFAULT '',
sky_color TEXT DEFAULT 'blue',
biosphere TEXT DEFAULT '',
sentients TEXT DEFAULT '',
climate TEXT DEFAULT '',
tech_level TEXT DEFAULT '',
terrain TEXT DEFAULT '',
CHECK (world_type IN ('habitable', 'gas giant', 'rocky', 'desert', 'oceanic', 'ice planet', 'molten', 'other')),
CHECK (rotation_direction IN ('prograde', 'retrograde')),
CHECK (orbit_direction IN ('prograde', 'retrograde')),
FOREIGN KEY (star_system_uid_fk) REFERENCES STAR_SYSTEM(star_system_uid_pk) ON DELETE CASCADE,
PRIMARY KEY (world_uid_pk));
